eic/EICrecon

src/cmake/jana_plugin.cmake
src/tests/data_flow_test/CMakeLists.txt

Makes fmt added to target_link_libraries for plugins by default

Made fmt default for plugins

---

src/detectors/BEMC/CMakeLists.txt

BEMC cmake uses plugin_add

---

.gitignore
README.md
src/cmake/jana_plugin.cmake
src/detectors/BEMC/CMakeLists.txt

Fixes #18
The documentation is added to README.md (while there is no yet documentation website)

Add WITH_STATIC_LIBRARY flag to plugin_add

---

.github/workflows/linux-eic-shell.yml

Build and install against the most recent jana2@2.0.6 in the eic-shell environment on cvmfs.

CI workflows for EICrecon build tests

---

README.md

Updates manual build instructions for ACTS
No
No

Add ACTS_BUILD_PLUGIN_JSON=ON flag to ACTS build instructions.

---

README.md

Add build instructions for lcio and have dd4hep build in support for lcio and edm4hep.
No
No

Add instructions for building lcio and lcio support into dd4hep.

---

src/algorithms/calorimetry/CalorimeterClusterMerger.cc
src/algorithms/calorimetry/CalorimeterClusterMerger.h
src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc
src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h
src/algorithms/calorimetry/CalorimeterHitDigi.cc
src/algorithms/calorimetry/CalorimeterHitDigi.h
src/algorithms/calorimetry/CalorimeterHitReco.cc
src/algorithms/calorimetry/CalorimeterHitReco.h
src/algorithms/calorimetry/CalorimeterIslandCluster.cc
src/algorithms/calorimetry/CalorimeterIslandCluster.h
src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelNRawHits.h
src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapNRecHits.h
src/detectors/EEMC/Cluster_factory_EcalEndcapNClusters.h
src/detectors/EEMC/Cluster_factory_EcalEndcapNMergedClusters.h
src/detectors/EEMC/ProtoCluster_factory_EcalEndcapNIslandProtoClusters.h
src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapNRawHits.h
src/detectors/EEMC/TruthCluster_factory_EcalEndcapNTruthProtoClusters.h

- [x ] New feature (spdlog)
no, down the road supplying a logger level may be needed,,,but this maintains compatibility
no

LOG_X replaced with an spdlog

---

CMakeLists.txt
src/benchmarks/CMakeLists.txt
src/benchmarks/reconstruction/TRACKINGcheck/CMakeLists.txt
src/benchmarks/reconstruction/TRACKINGcheck/TRACKINGcheck.C
src/benchmarks/reconstruction/TRACKINGcheck/TRACKINGcheckProcessor.cc
src/benchmarks/reconstruction/TRACKINGcheck/TRACKINGcheckProcessor.h
src/global/tracking/CMakeLists.txt

Fixes issue with -lEG not being found in out of eic-shell builds
Adds TRACKINGcheck benchmark plugin.
No
No

Davidl tracking

---

src/benchmarks/reconstruction/tracking_occupancy/TrackingOccupancyAnalysis.h
src/detectors/BTRK/BTRK.cc
src/detectors/ECTRK/ECTRK.cc
src/detectors/MPGD/MPGD.cc
src/tests/tracking_test/README.md

Fix input collection names

---

src/detectors/CMakeLists.txt
src/detectors/ZDC/CMakeLists.txt
src/detectors/ZDC/CalorimeterHit_factory_ZDCEcalRecHits.h
src/detectors/ZDC/Cluster_factory_ZDCEcalClusters.h
src/detectors/ZDC/Cluster_factory_ZDCEcalMergedClusters.h
src/detectors/ZDC/Cluster_factory_ZDCEcalMergedTruthClusters.h
src/detectors/ZDC/Cluster_factory_ZDCEcalTruthClusters.h
src/detectors/ZDC/ProtoCluster_factory_ZDCEcalIslandProtoClusters.h
src/detectors/ZDC/ProtoCluster_factory_ZDCEcalTruthProtoClusters.h
src/detectors/ZDC/RawCalorimeterHit_factory_ZDCEcalRawHits.h
src/detectors/ZDC/ZDC.cc
src/services/io/podio/RootWriter.cc
src/services/io/podio/RootWriter.h
src/utilities/eicrecon/eicrecon.cc

This does 2 things:
1. Add Zero Degree Calorimeter reconstruction (ZDC detector)
2. Fix (sort of) issue where first event is able to prepare buffers for writing but a subsequent event fails to.
No
Yes

Davidl zdc

---

docs/Logging.md
src/extensions/spdlog/SpdlogMixin.h
src/global/tracking/TrackerHitCollector_factory.cc
src/global/tracking/tracking.cc

SpdlogMixin class that automates boilerplate logging initizliation
No
No

Spdlog Mixin

---

src/algorithms/digi/SmearedFarForwardParticles.h
src/global/digi/ReconstructedParticle_factory_SmearedFarForwardParticles.h
src/global/digi/digi.cc
src/utilities/eicrecon/eicrecon.cc

This ports the SmearedFarForwardParticles algorithm from Juggler and uses it to make the SmearedFarForwardParticles collection.
No
No.

Add SmearedFarForwardParticles.

---

src/algorithms/tracking/ActsGeometryProvider.cc
src/algorithms/tracking/TrackParamTruthInit.cc
src/extensions/spdlog/SpdlogMixin.h
src/global/digi/SiliconTrackerDigi_factory.cc
src/global/reco/MatchClusters_factory.cc
src/global/tracking/ParticlesWithTruthPID_factory.cc
src/global/tracking/TrackParamTruthInit_factory.cc
src/global/tracking/TrackParameters_factory.cc
src/global/tracking/TrackParameters_factory.h
src/global/tracking/TrackerHitReconstruction_factory.cc
src/global/tracking/TrackerReconstructedParticle_factory.cc
src/global/tracking/TrackingResult_factory.cc
src/global/tracking/TrackingResult_factory.h
src/global/tracking/TruthTrackSeeding_factory.cc
src/global/tracking/tracking.cc
src/services/geometry/acts/ACTSGeo_service.cc

Fixes charge value conversion from ROOT ParticleDB in TrackingTruthInit. 
PR also introduces minor Logging and error reporting improvements
NO
NO

Fix incorrect charge conversion, improve logging

---

.github/workflows/doxygen.yml

Add doc folder as a static site with doxygen subdirectory
The third point of https://github.com/eic/EICrecon/issues/182
NO
NO

Add doc folder as a static site with doxygen subdirectory

---

.gitignore

Ignore local `install/` prefix, which is another common convention for testing builds.
No
No

chore: add local `install/` prefix to `.gitignore`

---

docs/_sidebar.md
docs/design/common_flags_env.md
docs/design/flags/acts.md
docs/design/flags/dd4hep.md
docs/design/flags/jana2.md
docs/howto/add_factory.md
docs/howto/make_plugin.md
docs/misc/references.md
docs/misc/this_website.md

Includes documentation updates
NO
NO

Flags documentation update

---

src/utilities/eicrecon/eicrecon_cli.cpp

Set EICrecon version to 0.2.2

---

src/algorithms/calorimetry/CalorimeterHitDigi.cc

This PR fixes an issue of forward Ecal smearing.
No breaking changes. Users do not need to change their code.
No.

Fix forward homogeneous Ecal smearing (Issue #205)

---

src/global/reco/MC2SmearedParticle_factory.cc

Fix segfault arising in MC2SmearedParticle_factory

---

.github/workflows/linux-eic-shell.yml

The CI is currently not testing functionality, just compilation. This adds two jobs on a simple simulation file for default geometry:
- `eicrecon`
- `run_eicrecon_all_flags.py`
No.
No.

ci: run short ddsim and reconstruction

---

.github/workflows/linux-eic-shell.yml

Error in https://github.com/eic/EICrecon/actions/runs/3293093194/jobs/5429225000, due to stupid mistake in `$DETECTOR_${{ matrix.detector_config }}` which leads to evaluation of `$DETECTOR_arches`... Braces added.
No.
No.

fix(ci): avoid DETECTOR_arches miscombinations

---

cmake/jana_plugin.cmake

Fixes undefined symbol error in issue #256 .
Note that this implements just one of the changes included in PR #252 as suggested in the discussion. 
No
No

Fix undefined link error for TDatabasePDG::TDatabasePDG()

---

src/algorithms/digi/PhotoMultiplierHitDigi.cc
src/algorithms/digi/PhotoMultiplierHitDigi.h

adds in the PhotoMultiplierDigi algorithm to start off the PID detectors
- [ x] New feature (issue #__)
nope
nope

added the PhotoMultiplier algorithm

---

src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapNRecHits.h
src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapNRawHits.h
src/tools/default_flags_table/reco_flags.py

Update values for backward hcal endcap suggested in issue #251 
No
No

Changes from issue #251

---

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h
src/detectors/HCAL/CalorimeterHit_factory_HcalBarrelMergedHits.h
src/global/digi/SiliconTrackerDigi_factory.cc

Fixes some issues with error messages when running eicrecon without the reco_flags.py
No
No

Davidl error messages fixes

---

src/algorithms/calorimetry/CalorimeterHitDigi.cc
src/algorithms/calorimetry/CalorimeterHitReco.cc
src/algorithms/calorimetry/CalorimeterHitsMerger.cc
src/algorithms/calorimetry/ImagingPixelReco.h
src/services/geometry/dd4hep/JDD4hep_service.cc
src/services/io/podio/JEventProcessorPODIO.cc
src/services/io/podio/RootWriter.cc
src/utilities/dump_flags/DumpFlags_processor.cc
src/utilities/dump_flags/DumpFlags_processor.h

This cleans up the output of eicrecon a bit to make it easy to see real problems. This includes:
- This turns a lot of the non-fatal error messages into warning messages.
- Check that XML geometry file exists and quit with informative error if not.
- Make printing of summary all config. parameters at end of job optional with default not to print.
No
Yes, but mainly cosmetic.

Davidl warnings errors

---

.github/workflows/linux-eic-shell.yml

This replaces the e- simulations with pi- simulations. Only pions will also reach the Hcals reliably, hopefully surfacing issues in the Hcals earlier.
No.
No.

ci: change to pi- simulations for tests

---

src/benchmarks/reconstruction/tof_efficiency/TofEfficiency_processor.cc
src/benchmarks/reconstruction/tof_efficiency/TofEfficiency_processor.h

- [ x] New feature (issue #__)

matching points along track segments with TOF hits

---

docs/howto/visualize_callgraph.md

Fixes a couple of typos and formatting in callgraph visualization documentation. Tightens up some explainations.
No
No

Fix some typos and formatting in callgraph visualization documentation.

---

src/examples/track_matching/reco_particles_track_matching.cc

Typo in documentation update

---

src/algorithms/tracking/TrackPropagation.cc
src/algorithms/tracking/TrackPropagation.h
src/tests/track_propagation_test/TrackPropagationTest_processor.cc
src/tests/track_propagation_test/TrackPropagationTest_processor.h

TrackPropagation algorithm is fully in and working
NO
NO

358 track projection summary

---

src/tools/default_flags_table/reco_flags.py

This PR aims to fix the imaging calorimeter cluster finding in the v0.3.6 release cycle.
No.
No, not in a negative way.

Fix imaging calorimeter cluster finding in v0.3.6 release cycle

---

src/extensions/spdlog/SpdlogExtensions.h
src/extensions/spdlog/SpdlogToActs.h

Silences warning in every file that includes this header.
No.
No.

fix: treat all enum in SpdlogExtensions

---

src/algorithms/calorimetry/CalorimeterHitDigi.cc
src/algorithms/calorimetry/CalorimeterIslandCluster.cc
src/algorithms/digi/PhotoMultiplierHitDigi.cc
src/services/geometry/dd4hep/JDD4hep_service.cc
src/services/io/podio/JEventSourcePODIO.cc

Fixes: #495
Hopefully, yes
Yes

treewide: replace silent exits with exception throws

---

src/algorithms/tracking/OrthogonalTrackSeedingConfig.h
src/algorithms/tracking/TrackSeeding.cc

This fixes a unit in the calculation of the track seed momentum.

Fixed radius units in seeding

---

src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPInsertRecHits.h

This changes the values of the HCal insert's sampling fraction and threshold factors.
No.
Aside from changing the above values, no.

Changed hcal insert sampling fraction and threshold values

---

.github/workflows/linux-eic-shell.yml

Resolves: #567
Closes: #568
See https://github.com/eic/EICrecon/issues/567#issuecomment-1483564126

HOTFIX ci: remove broken test for --version

---

src/examples/log_example/CMakeLists.txt
src/services/geometry/acts/CMakeLists.txt
src/utilities/eicrecon/CMakeLists.txt

This is the smallest set of changes needed to make EICrecon compile when using JANA2 2.1.0 with USE_PODIO=On. 
This doesn't use the new features, which will come in a separate pull request.
No.
No.

JANA2.1.0 compiles with USE_PODIO=On

---

src/scripts/CMakeLists.txt

fix: `source eicrecon-this.sh` returns `readlink: missing operand` error

---

src/detectors/BEMC/Cluster_factory_EcalBarrelSciGlassClusters.h

Update the correction based on a simple study
No
Yes

Cluster_factory_EcalBarrelSciGlassClusters: adjust m_sampFrac

---

CMakeLists.txt
custom_environment_example.sh
docs/_sidebar.md
docs/get-started/manual-build.md
src/scripts/eicrecon-this.sh.in
src/services/geometry/dd4hep/JDD4hep_service.cc

Remove references to ip6 geometry or environment/cmake variables that don't do anything.
No.
No.

docs: various fixes to align with current practice on DETECTOR_PATH etc.

---

src/algorithms/calorimetry/CalorimeterIslandCluster.cc

Prevents users from seeing confusing error messages.

CalorimeterIslandCluster: fix evaluator error format string

---

.github/workflows/linux-eic-shell.yml

A minor fix for a failure seen on main.

linux-eic-shell.yml: fix llvm-cov when running on a branch

---

README.md

This adds a DOI badge pointing to the zenodo page for the latest tagged release for EICrecon. This can be used to cite the EICrecon code.
No
No

README.md: Add zenodo DOI badge that points to latest release

---

docs/get-started/manual-build.md

The fmt section of the manual build page was incorrectly displaying due to missing format tags around it. This just adds those.
No
No

Fix formatting of fmt section

---

.github/workflows/linux-eic-shell.yml

This provides a more complete code coverage report across all algorithm libraries: in CI status and in codecov_report artifact.

linux-eic-shell.yml: estimate coverage for each algorithm library

---

src/global/digi/PhotoMultiplierHitDigi_factory.cc
src/global/digi/PhotoMultiplierHitDigi_factory.h
src/global/pid/IrtCherenkovParticleID_factory.cc
src/global/pid/IrtCherenkovParticleID_factory.h
src/global/pid/MergeTrack_factory.cc
src/global/pid/MergeTrack_factory.h
src/global/pid/RichTrack_factory.cc
src/global/pid/RichTrack_factory.h

fix: respect new `JChainMultifactoryT::GetPrefix()` return value

---

.github/asan.supp
.github/lsan.supp
.github/workflows/linux-eic-shell.yml

This adds asan and lsan suppressions files for use in CI.
No.
No.

ci: asan and lsan suppressions

---

src/services/geometry/richgeo/ReadoutGeo.cc
src/services/geometry/richgeo/ReadoutGeo.h
src/services/geometry/richgeo/RichGeo.h

fix https://github.com/eic/EICrecon/issues/738
no
no

fix(richgeo): DD4hep CellID type

---

.github/workflows/linux-eic-shell.yml

For our betterment.
No.
Let's hope so. Wait, this probably doesn't refer to the behavior of developers...

ci: run clang-tidy on PR diff and post suggestions

---

.github/workflows/linux-eic-shell.yml

Fixes an issue reported in https://github.com/eic/EICrecon/pull/751#issuecomment-1627448876

linux-eic-shell.yml: fix llvm-cov for PRs from fork

---

.github/workflows/linux-eic-shell.yml

This switches the CI pipelines from arches/brycecanyon to brycecanyon/craterlake.
No.
No.

ci: default to brycecanyon, craterlake

---

src/extensions/jana/JChainFactoryGeneratorT.h

I don't think this is referenced anywhere, but better to fix it as a dedicated commit in case it is.
No.
No.

fix: typo in JChainFactoryGeneratorT type

---

src/algorithms/LICENSE

This clarifies that the algorithms (and arguably everything else here) was always LGPL as per the upstream license conditions of juggler.
No.
No.

fix: restore LGPL license for algorithms

---

src/algorithms/calorimetry/CalorimeterIslandCluster.cc
src/algorithms/calorimetry/CalorimeterIslandCluster.h
src/detectors/B0ECAL/ProtoCluster_factory_B0ECalIslandProtoClusters.h
src/detectors/BEMC/ProtoCluster_factory_EcalBarrelScFiProtoClusters.h
src/detectors/BHCAL/ProtoCluster_factory_HcalBarrelIslandProtoClusters.h
src/detectors/EEMC/ProtoCluster_factory_EcalEndcapNIslandProtoClusters.h
src/detectors/EHCAL/ProtoCluster_factory_HcalEndcapNIslandProtoClusters.h
src/detectors/FEMC/ProtoCluster_factory_EcalEndcapPInsertIslandProtoClusters.h
src/detectors/FEMC/ProtoCluster_factory_EcalEndcapPIslandProtoClusters.h
src/detectors/FHCAL/ProtoCluster_factory_HcalEndcapPInsertIslandProtoClusters.h
src/detectors/FHCAL/ProtoCluster_factory_HcalEndcapPIslandProtoClusters.h
src/detectors/FHCAL/ProtoCluster_factory_LFHCALIslandProtoClusters.h
src/detectors/LUMISPECCAL/ProtoCluster_factory_EcalLumiSpecIslandProtoClusters.h
src/detectors/ZDC/ProtoCluster_factory_ZDCEcalIslandProtoClusters.h
src/tests/algorithms_test/calorimetry_CalorimeterIslandCluster.cc

algorithms/calorimetry/CalorimeterIslandCluster: pass PODIO collections instead of std::vector

---

src/algorithms/calorimetry/CalorimeterHitDigi.cc
src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc

Move from index based loops to range-based loops where appropriate.
See https://clang.llvm.org/extra/clang-tidy/checks/modernize/loop-convert.html
No.
No.

fix: clang-tidy modernize-loop-convert

---

.github/workflows/linux-eic-shell.yml

This moves the definitions of ASAN_OPTIONS and LSAN_OPTIONS from individual jobs up to the workflow level. This will ensure consistency.
No.
No.

ci: set {ASAN/LSAN}_OPTIONS for whole workflow

---

src/algorithms/calorimetry/CalorimeterIslandCluster.cc

From https://eicweb.phy.anl.gov/EIC/juggler/-/blob/master/JugReco/src/components/CalorimeterIslandCluster.cpp#L10-13
no
no

CalorimeterIslandCluster: add back the references

---

.github/labeler.yml
.github/workflows/labeler.yml

Automatic PR labeling like https://github.com/eic/epic/pull/268
No
No

add .github/workflows/labeler.yml

---

src/algorithms/reco/ChargedParticleSelector.cxx
src/algorithms/reco/ChargedParticleSelector.h
src/global/reco/ChargedParticleSelector_factory.h
src/global/reco/reco.cc

This adds charged jets that may be more usable for physics studies until hadronic subtraction is implemented.

reco: add *ChargedJets

---

.github/workflows/linux-eic-shell.yml

We're starting to get swamped again. This should enable [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
No.
No.

feat(ci): allow merge queues

---

src/detectors/B0TRK/B0TRK.cc
src/detectors/BTOF/BTOF.cc
src/detectors/BTRK/BTRK.cc
src/detectors/BVTX/BVTX.cc
src/detectors/ECGEM/ECGEM.cc
src/detectors/ECTOF/ECTOF.cc
src/detectors/ECTRK/ECTRK.cc

Moving silicon detector thresholds documented in https://docs.google.com/spreadsheets/d/1s8oXj36SqIh7TJeHFH89gQ_ayU1_SVEpWQNkx6sETKs/edit#gid=238482234
from npsim into digitization.
No.
Yes.

Silicon thresholds

---

src/global/reco/InclusiveKinematicsDA_factory.cc
src/global/reco/InclusiveKinematicsDA_factory.h
src/global/reco/InclusiveKinematicsElectron_factory.cc
src/global/reco/InclusiveKinematicsElectron_factory.h
src/global/reco/InclusiveKinematicsJB_factory.cc
src/global/reco/InclusiveKinematicsJB_factory.h
src/global/reco/InclusiveKinematicsSigma_factory.cc
src/global/reco/InclusiveKinematicsSigma_factory.h
src/global/reco/InclusiveKinematicsTruth_factory.cc
src/global/reco/InclusiveKinematicsTruth_factory.h
src/global/reco/InclusiveKinematicseSigma_factory.cc
src/global/reco/InclusiveKinematicseSigma_factory.h
src/global/reco/reco.cc

This migrates all InclusiveKinematics factories from legacy JChainFactory to the newer JChainMultifactory. 
No.
No.

fix: migrate InclusiveKinematics to JChainMultifactory

---

.github/workflows/linux-eic-shell.yml

Hope this makes collect-docs faster.

fix: rm doxygen from PRs

---

.github/workflows/pr-backport.yml

Can't use github user to submit PRs with Github Actions
This is needed to avoid situations like #952

pr-backport.yml: add github token

---

.github/workflows/linux-eic-shell.yml

Addresses an issue brought up in https://github.com/eic/EICrecon/pull/964#issuecomment-1720001570

linux-eic-shell.yml: enable on maintenance branches

---

.pre-commit-config.yaml

Run clang-format on pre-commit. Hopefully leads to fewer missing spaces and incorrect indentation.
No.
No.

ci: pre-commit clang-format (but not CI)

---

src/utilities/eicrecon/eicrecon_cli.cpp

Fixes overlow when running `eicrecon -c`, `--configs` (display configuration parameters). For small `max_key_length`, `max_key_length-4` wraps around.
```
Configuration Parameters:
terminate called after throwing an instance of 'std::length_error'
what():  basic_string::_M_create
Program received signal SIGABRT, Aborted.
0x00007ffff7aacd3c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7aacd3c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7a5df32 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7a48472 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff7cc2919 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7ccde1a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7ccde85 in …
```

fix: overflow in eicrecon_cli.cpp

---

.github/asan.supp
.github/workflows/linux-eic-shell.yml

This adds a job step in `build` and in `eicrecon-gun` to print `ldd` for all regular libraries and plugins.
No.
No.

feat(ci): correct LD_LIBRARY_PATH prefix and add job step to print `ldd *.so`

---

.github/workflows/linux-eic-shell.yml

fix(ci): cancel-in-progress false for main

---

.github/workflows/linux-eic-shell.yml

This fell bewteen the cracks. Leads to errors like https://github.com/eic/EICrecon/actions/runs/6249479829/job/16966875149#step:5:182.
No.
No.

fix: set LD_LIBRARY_PATH for benchmark tests

---

src/detectors/FOFFMTRK/OffMomentumReconstruction_factory.cc
src/detectors/FOFFMTRK/OffMomentumReconstruction_factory.h
src/detectors/RPOTS/RomanPotsReconstruction_factory.cc
src/detectors/RPOTS/RomanPotsReconstruction_factory.h
src/factories/calorimetry/CalorimeterClusterRecoCoG_factoryT.h
src/factories/calorimetry/CalorimeterHitDigi_factoryT.h
src/factories/calorimetry/CalorimeterHitReco_factoryT.h
src/factories/calorimetry/CalorimeterHitsMerger_factoryT.h
src/factories/calorimetry/CalorimeterIslandCluster_factoryT.h
src/factories/fardetectors/MatrixTransferStatic_factoryT.h
src/factories/tracking/TrackerHitReconstruction_factoryT.h
src/global/digi/PhotoMultiplierHitDigi_factory.cc
src/global/tracking/CKFTracking_factory.cc
src/global/tracking/IterativeVertexFinder_factory.cc
src/global/tracking/TrackPropagation_factory.cc
src/global/tracking/TrackPropagation_factory.h
src/global/tracking/TrackerSourceLinker_factory.cc
src/services/geometry/acts/ACTSGeo_service.cc
src/services/geometry/dd4hep/DD4hep_service.cc
src/services/geometry/dd4hep/DD4hep_service.h
src/services/geometry/dd4hep/dd4hep.cc
src/services/geometry/richgeo/RichGeo_service.cc
src/services/geometry/richgeo/RichGeo_service.h

Rename JDD4hep_service to DD4hep_service to avoid the implication that JDD4hep_service is part of JANA2.
TODO:
No.
No.

fix: rename JDD4hep_service to DD4hep_service

---

src/utilities/eicrecon/eicrecon_cli.cpp

Resolves issue
https://github.com/eic/EICrecon/pull/1002#issuecomment-1727866709
seen in https://github.com/eic/EICrecon/actions/runs/6249479829/job/16966883258#step:5:182

eicrecon_cli: return exit code when exception is detected

---

src/algorithms/fardetectors/MatrixTransferStaticConfig.h

Typo in PID assignment for RP reconstruction - now fixed.
- [ x] Bug fix (issue #__)
No.
Yes, assigns the right PID for the RP reconstruction.

fixed incorrect PDG assignment

---

.github/release.yml

Sets up release notes to have categories. Note sure how to test...
No.
No.

feat(ci): release notes definition

---

.github/workflows/linux-eic-shell.yml

Potentially resolves this, per https://github.com/google/sanitizers/issues/1322...
No.
No.

fix(ci): avoid lsan crashes with intercept_tls_get_addr=0

---

.github/workflows/linux-eic-shell.yml
src/scripts/eicmkplugin.py

This adds a CI test for the eicmkplugin script (under the philosophy that if it's not tested, it is probably broken).
No.
No.

feat(ci): test eicmkplugin in CI

---

src/global/tracking/TrackPropagation_factory.cc

https://github.com/eic/EICrecon/actions/runs/6421965316/job/17439067008?pr=1053#step:5:577 as discovered in https://github.com/eic/EICrecon/pull/1053
This fixes track propagations.

TrackPropagation_factory: HcalEndcapN_* is not defined anymore, use LFHCAL

---

src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.h
src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.h

Minor fix that at some point iwyu will be able to catch on its own... but for now requires manual intervention.
No.
No.

fix: remove unused TrackPropagation header with indirect dd4hep::BitFieldCoder definition

---

.github/workflows/linux-eic-shell.yml

The project now considers craterlake to be the default configuration. This removes brycecanyon from the main configurations tested in CI.
TODO:
No.
No.

feat: remove epic_brycecanyon as main configuration

---

src/algorithms/tracking/ActsGeometryProvider.cc

This will prevent more confusion.
No.
No.

fix: print magnetic field strength in correct units in ActsGeometryProvider

---

.github/workflows/linux-eic-shell.yml

This allows changing the image that is used for CI jobs.
No.
No.

feat(ci): allow changing jug_xl:nightly as basis for CI jobs

---

src/detectors/LOWQ2/LOWQ2.cc

Updated LOWQ2 thresholds to match the [digitization table from 10/2023](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g)
No.
Yes.

updated LOWQ2 threshold

---

src/detectors/B0TRK/B0TRK.cc

Updated B0 LGAD thresholds to match the [digitization table from 10/2023](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g)
No.
Yes.

updated B0 LGAD threshold

---

src/detectors/ECTOF/ECTOF.cc

Updated ECTOF thresholds to match the [digitization table from 10/2023](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g)
No.
Yes.

updated ECTOF threshold

---

src/detectors/BTOF/BTOF.cc

Updated BTOF thresholds to match the [digitization table from 10/2023](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g)
No.
Yes.

updated BTOF threshold

---

src/detectors/BTRK/BTRK.cc
src/detectors/BVTX/BVTX.cc
src/detectors/ECTRK/ECTRK.cc

Updated MAPS thresholds to match the [digitization table from 10/2023](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g)
No.
Yes.

updated MAPS threshold

---

cmake/jana_plugin.cmake

Fixes build on macOS where suffix is .dylib

jana_plugin.cmake: respect CMAKE_SHARED_LIBRARY_{PREFIX,SUFFIX}

---

.github/workflows/linux-eic-shell.yml

The mismatch between what users are and what CI sees is not helpful.
No.
No.

fix: change back to eic-shell nightly

---

.github/iwyu.imp
src/algorithms/calorimetry/CalorimeterIslandCluster.cc
src/algorithms/calorimetry/CalorimeterIslandCluster.h
src/algorithms/tracking/TrackerMeasurementFromHits.cc
src/benchmarks/reconstruction/tracking_efficiency/TrackingEfficiency_processor.cc
src/benchmarks/reconstruction/tracking_occupancy/HitReconstructionAnalysis.cc
src/benchmarks/reconstruction/tracking_occupancy/TrackingOccupancyAnalysis.cc
src/detectors/DIRC/DIRC.cc
src/detectors/DRICH/DRICH.cc
src/global/digi/PhotoMultiplierHitDigi_factory.h
src/global/pid/MergeCherenkovParticleID_factory.h
src/global/pid/MergeTrack_factory.h
src/global/pid/ParticlesWithPID_factory.h
src/global/reco/GeneratedJets_factory.h
src/global/reco/InclusiveKinematicsDA_factory.h
src/global/reco/InclusiveKinematicsElectron_factory.h
src/global/reco/InclusiveKinematicsJB_factory.h
src/global/reco/InclusiveKinematicsSigma_factory.h
src/global/reco/InclusiveKinematicsTruth_factory.h
src/global/reco/InclusiveKinematicseSigma_factory.h
src/global/reco/MC2SmearedParticle_factory.h
src/global/reco/MatchClusters_factory.h
src/global/reco/ReconstructedJets_factory.h
src/global/tracking/TrackParamTruthInit_factory.h
src/global/tracking/TrackSeeding_factory.h
src/global/tracking/TrackerMeasurementFromHits_factory.h
src/services/geometry/richgeo/IrtGeo.cc
src/services/io/podio/JEventProcessorPODIO.cc
src/tests/reco_test/GlobalReconstructionTest_processor.cc
src/tests/tracking_test/TrackingTest_processor.cc

This line wasn't added and may prevent suggested addition of spurious headers.
No.
No.

fix: add missing Measurement2D line in iwyu.imp

---

.github/workflows/linux-eic-shell.yml
CMakeLists.txt

In CI, test the eicmkplugin with the local build, not system install. 
(Alternative is to modify eicmkplugin to write the install prefix into the CMakeList as a HINT, but that requires adding too much to eicmkplugin. It is also not a requirement so it would still fall back to system installs.)
No.
No.

fix(ci): test eicmkplugin with EICrecon_ROOT=install/

---

src/algorithms/tracking/OrthogonalTrackSeedingConfig.h

Fixes a parameter type in the seeder to match the expected type in Acts.
No
No

fix: correct parameter type

---

src/algorithms/calorimetry/CalorimeterIslandCluster.cc
src/algorithms/calorimetry/CalorimeterIslandCluster.h
src/factories/calorimetry/CalorimeterIslandCluster_factory.h
src/tests/algorithms_test/calorimetry_CalorimeterIslandCluster.cc

This PR adopt algorithms:: interface in CalorimeterIslandCluster. In addition to the algorithm, also the unit tests are updated.
No.
No.

fix: adopt algorithms:: interface in CalorimeterIslandCluster

---

src/algorithms/calorimetry/ImagingClusterReco.h
src/factories/calorimetry/ImagingClusterReco_factory.h

Another algorithm converted to the standard interface.
No.
No.

fix: convert ImagingClusterReco to algorithms interface

---

src/algorithms/calorimetry/CalorimeterTruthClustering.cc
src/algorithms/calorimetry/CalorimeterTruthClustering.h
src/factories/calorimetry/CalorimeterTruthClustering_factory.h

Another algorithm converted to the standard interface.
No.
No.

feat: convert CalorimeterTruthClustering to algorithms interface

---

src/algorithms/calorimetry/ImagingTopoCluster.h
src/factories/calorimetry/ImagingTopoCluster_factory.h

Another algorithm converted to the standard interface.
No.
No.

fix: convert ImagingTopoCluster to algorithms interface

---

src/algorithms/calorimetry/TruthEnergyPositionClusterMerger.h
src/factories/calorimetry/TruthEnergyPositionClusterMerger_factory.h

Another algorithm converted to the standard interface.
No.
No.

fix: convert TruthEnergyPositionClusterMerger to algorithms interface

---

src/algorithms/reco/Beam.h
src/algorithms/reco/InclusiveKinematicsDA.cc
src/algorithms/reco/InclusiveKinematicsDA.h
src/algorithms/reco/InclusiveKinematicsElectron.cc
src/algorithms/reco/InclusiveKinematicsElectron.h
src/algorithms/reco/InclusiveKinematicsJB.cc
src/algorithms/reco/InclusiveKinematicsJB.h
src/algorithms/reco/InclusiveKinematicsSigma.cc
src/algorithms/reco/InclusiveKinematicsSigma.h
src/algorithms/reco/InclusiveKinematicsTruth.cc
src/algorithms/reco/InclusiveKinematicsTruth.h
src/algorithms/reco/InclusiveKinematicseSigma.cc
src/algorithms/reco/InclusiveKinematicseSigma.h
src/global/reco/InclusiveKinematicsDA_factory.h
src/global/reco/InclusiveKinematicsElectron_factory.h
src/global/reco/InclusiveKinematicsJB_factory.h
src/global/reco/InclusiveKinematicsSigma_factory.h
src/global/reco/InclusiveKinematicsTruth_factory.h
src/global/reco/InclusiveKinematicseSigma_factory.h

This converts the InclusiveKinematics algorithms to use the algorithms interface.
No.
No.

feat: convert InclusiveKinematics to use algorithms:: interface

---

src/algorithms/fardetectors/MatrixTransferStatic.cc
src/algorithms/fardetectors/MatrixTransferStatic.h
src/factories/fardetectors/MatrixTransferStatic_factory.h

This converts the MatrixTransferStatic algorithms to use the algorithms interface.
No.
No.

feat: convert MatrixTransferStatic to use algorithms:: interface

---

src/algorithms/pid/MergeParticleID.cc
src/algorithms/pid/MergeParticleID.h
src/global/pid/MergeCherenkovParticleID_factory.cc
src/global/pid/MergeCherenkovParticleID_factory.h
src/tests/algorithms_test/pid_MergeParticleID.cc

This PR converts the MergeParticleID algorithm in PID to use the algorithms:: interface
No.
No.

feat: convert MergeParticleID to use algorithms:: interface

---

.github/workflows/linux-eic-shell.yml

In order to have a reasonably recent main branch run to compare pull requests to, run the CI pipelines on main every 8 hours.
No.
No.

fix(ci): run regularly on main

---

.github/labeler.yml

labeler.yml: fix config for v5

---

src/algorithms/tracking/TrackProjector.cc

This uses the target surface jacobian to convert the covariance in bound coordinates to the free covariance that can be used to obtain the local position error on the projected point on the target surface.
No.
No.

fix: use jacobian to convert bound covariance to free 3d position error

---

src/global/tracking/TrackPropagation_factory.cc

TrackPropagation_factory.cc: fix LFHCAL subsystem ID

---

src/algorithms/tracking/ActsGeometryProvider.cc
src/algorithms/tracking/ActsGeometryProvider.h

Issue warning if surface not planar in draw surfaces

Issue warning if surface not planar in draw surfaces

---

.github/workflows/linux-eic-shell.yml

Specifying the workflow name with dawidd6/action-download-artifact avoids an API request by bypassing https://github.com/dawidd6/action-download-artifact/blob/master/main.js#L61. This PR uses the current workflow name which will be correct as long as we don't change the workflow name.
No.
No.

fix(ci): reduce API requests by specifying workflow name

---

src/services/algorithms_init/AlgorithmsInit_service.h

Minor update to change the logger name to AlgorithmsInit.
No.
No.

fix: logger name ServiceSvc to AlgorithmsInit

---

.github/workflows/linux-eic-shell.yml

This will show us what slows down the reconstruction.

linux-eic-shell.yml: run eicrecon with janatop

---

.github/labeler.yml

Handles some recently introduced labels

labeler.yml: handle digitization and jets topics

---

.github/workflows/linux-eic-shell.yml

Doesn't seem to be needed anymore.

linux-eic-shell.yml: drop use of alpine

---

src/benchmarks/reconstruction/tracking_occupancy/HitReconstructionAnalysis.h
src/benchmarks/reconstruction/tracking_occupancy/TrackingOccupancyAnalysis.h
src/detectors/MPGD/MPGD.cc
src/services/io/podio/JEventProcessorPODIO.cc

Was removed together with epic_arches in epic 24.04
https://github.com/eic/epic/commit/8b961fb831cd5996ed91acdf96320de258152f61#diff-fef1650e18afe361953f0cda8c20f06bd26fdf40f2bb991904ed48ed9c5520d9L1

MPGD: retire MPGDDIRC

---

src/detectors/CMakeLists.txt
src/detectors/PFRICH/CMakeLists.txt
src/detectors/PFRICH/PFRICH.cc
src/services/io/podio/JEventProcessorPODIO.cc

This PR introduces PFRICH digitization based on the DRICH digitization. No thought went into the parameters; just setting up the plugin for someone to change the numbers :-)
No.
Yes, will expected PFRICH input collections, which are available as of https://github.com/eic/epic/pull/664.

feat: PFRICH digitization plugin

---

.github/workflows/linux-eic-shell.yml

This PR removes the old/slow/exhaustive capybara diff.
No.
No.

fix: rm old epic-capybara

---

src/algorithms/calorimetry/CalorimeterHitDigi.cc
src/algorithms/calorimetry/CalorimeterHitDigi.h
src/algorithms/calorimetry/CalorimeterHitDigiConfig.h
src/detectors/B0ECAL/B0ECAL.cc
src/detectors/BEMC/BEMC.cc
src/detectors/BHCAL/BHCAL.cc
src/detectors/EEMC/EEMC.cc
src/detectors/EHCAL/EHCAL.cc
src/detectors/FEMC/FEMC.cc
src/detectors/FHCAL/FHCAL.cc
src/detectors/LUMISPECCAL/LUMISPECCAL.cc
src/detectors/ZDC/ZDC.cc
src/factories/calorimetry/CalorimeterHitDigi_factory.h
src/tests/algorithms_test/algorithmsInit.cc
src/tests/algorithms_test/calorimetry_CalorimeterHitDigi.cc

This is a sequel to #1349, now for digitization.

CalorimeterHitDigi: use EvaluatorSvc for corrMeanScale

---

src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc
src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc
src/factories/calorimetry/CalorimeterHitDigi_factory.h
src/factories/calorimetry/CalorimeterHitsMerger_factory.h
src/factories/fardetectors/FarDetectorLinearProjection_factory.h
src/global/pid/MergeTrack_factory.h
src/global/pid/RichTrack_factory.h
src/global/tracking/CKFTracking_factory.h
src/global/tracking/TrackParamTruthInit_factory.h
src/global/tracking/TrackPropagation_factory.h
src/global/tracking/TrackerMeasurementFromHits_factory.h

This PR removes the unused includes of SpdlogMixin in various factories.
No.
No.

fix: rm include unused SpdlogMixin

---

src/detectors/RPOTS/RPOTS.cc

Fix bug in old positions for RP sensors in EICrecon.
- [x ] Bug fix (issue #__)
- [ x] Tests for the changes have been added
No.
Yes - this will make RP tracks work again.
Co-authored-by: Alexander Jentsch <ajentsch@bnl.gov>
(cherry picked from commit f9ad4941f97421ccdda5655f036d842f93dbed1c)

[v1.13] correct z positions of hits for RP

---

.github/workflows/linux-eic-shell.yml
docs/get-started/eic-shell.md
docs/howto/full_chain_simulation.md
docs/howto/run_dd4hep_simulation.md
docs/howto/use_docker.md
docs/howto/use_singularity.md
docs/tutorial/02-work-environment.md
src/services/geometry/dd4hep/DD4hep_service.cc
src/tests/tracking_test/README.md

This PR changes all references to setup.sh to bin/thisepic.sh.
No.
No.

fix: setup.sh -> bin/thisepic.sh

---

.github/workflows/linux-eic-shell.yml

https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/921

Update linux-eic-shell.yml: PIPELINE_NAME_CONTAINER -> PIPELINE_NAME

---

.github/eicrecon.json
.github/workflows/linux-eic-shell.yml

This PR adds a logging matcher for EICrecon errors.
No.
No.

feat(ci): eicrecon error matcher

---

.github/workflows/linux-eic-shell.yml
src/services/algorithms_init/AlgorithmsInit_service.h

Trying to test for and fix #1507

AlgorithmsInit_service: fix crashes when algorithms are re-created

---

.github/workflows/linux-eic-shell.yml

Reduce pointless load on eicweb.

linux-eic-shell.yml: don't trigger eic_container builds on schedule

---

.github/workflows/linux-eic-shell.yml

linux-eic-shell.yml: build against 24.05.2-stable container

---

src/algorithms/calorimetry/CalorimeterIslandCluster.cc
src/algorithms/calorimetry/CalorimeterIslandCluster.h

CalorimeterIslandCluster: switch to use EvaluatorSvc

---

src/global/tracking/tracking.cc

Remove no longer used MPGDDIRC hit collection
Removes no longer used hit collection MPGDDIRC hits from tracking.cc
- [x ] Other: __
- [x ] Changes have been communicated to collaborators
No
No

Remove MPGDDIRC hits from tracking.cc

---

src/algorithms/reco/InclusiveKinematicsESigma.cc
src/algorithms/reco/InclusiveKinematicsESigma.h
src/global/reco/reco.cc
src/services/io/podio/JEventProcessorPODIO.cc

This helps to highlight a difference to electron $\Sigma$ method vs $\Sigma$ method to avoid confusion (there were questions on mattermost).

InclusiveKinematicseSigma -> InclusiveKinematicsESigma

---

.github/workflows/linux-eic-shell.yml

This PR fixes, hopefully, an issue with too many open files in e.g. https://github.com/eic/EICrecon/actions/runs/10486195490/job/29045183375#step:2:111.
Tracking https://github.com/actions/upload-artifact/issues/485 for this.
No.
No.

fix(ci): pin upload-artifact/merge to v4.3.5

---

.github/workflows/linux-eic-shell.yml

The issues with rendering the factory graph are cropping in. Example PRs: #1577 #1576

linux-eic-shell.yml: continue-on-error for graphviz rendering

---

src/algorithms/reco/ScatteredElectronsEMinusPz.cc
src/algorithms/reco/ScatteredElectronsEMinusPz.h
src/global/reco/ScatteredElectronsEMinusPz_factory.h

Refactor to use algorithms interface and ParticleSvc.
No
No

ScatteredElectronsEMinusPz: refactor to use algorithms interface and ParticleSvc

---

docs/howto/use_docker.md
docs/howto/use_singularity.md
docs/tutorial/02-work-environment.md

This PR updates documentation to refer consistently to `eic_xl` as the container image to use.
No.
No.

doc: jug_xl -> eic_xl

---

.github/lsan.supp

Suppress a recently added leak.

lsan.supp: add leak:dd4hep::detail::VolumeManager_Populator::scanPhysicalVolume

---

src/algorithms/reco/UndoAfterBurner.cc

This provides a file size reduction:
```
before 3.1M
after 2.7M
```
Unlikely.
Yes

UndoAfterBurner: skip particles that are not created by generator

---

.github/workflows/linux-eic-shell.yml

This PR updates the target operating system for CI jobs, from ubuntu-latest to a more explicit ubuntu-22.04. This is in part to avoid the automatic update of implicit ubuntu-latest that will break everything (https://github.com/eic/EICrecon/pull/1686), and in part because it makes sense to be explicit about the target operating system.
No.
No.

feat(ci): runs-on: ubuntu-latest -> ubuntu-22.04

---

src/algorithms/interfaces/ActsSvc.h
src/algorithms/tracking/ActsGeometryProvider.cc
src/algorithms/tracking/ActsGeometryProvider.h
src/algorithms/tracking/TrackProjector.cc
src/algorithms/tracking/TrackProjector.h
src/global/tracking/TrackProjector_factory.h
src/services/algorithms_init/AlgorithmsInit_service.h

Implementing additional associations will require adding an additional input #1730. The algorithm has not yet been converted to comply with the algorithms interface, so we do that here.
No
No

TrackProjector: adopt algorithms interface

---

.github/workflows/linux-eic-shell.yml
docs/howto/visualize_callgraph.md

This PR changes references to /work/eic2 into /volatile/eic to get our CI unstuck.
No.
No.

fix: /work/eic2 -> /volatile/eic

---

src/services/geometry/acts/ACTSGeo_service.h

This PR replaces a header by a forward declare in ACTSGeo_Service.h
No.
No.

fix: forward declare in ACTSGeo_service.h

---

src/algorithms/fardetectors/FarDetectorLinearTracking.cc

Too much output is produced currently, production will not like it.

FarDetectorLinearTracking: convert "no hits" message to `trace` verbosity

---

.github/workflows/linux-eic-shell.yml

linux-eic-shell.yml: add CXX setting for 25.01.1-stable build

---

src/detectors/LOWQ2/LOWQ2.cc

Fixes the Low-Q2 reconstruction problems outlined here:
https://github.com/eic/EICrecon/pull/1762#issuecomment-2798888885
Really not sure how these changes snuck in to start with, some bad merging.

Restore TaggerTrackerRecHits

---

.github/iwyu.imp

This PR fixes iwyu by pointing to the right directories for mappings.
No.
No.

fix: iwyu.imp: /usr/local -> /opt/local

---

src/algorithms/fardetectors/MatrixTransferStatic.cc
src/algorithms/fardetectors/MatrixTransferStaticConfig.h
src/detectors/FOFFMTRK/FOFFMTRK.cc
src/detectors/RPOTS/RPOTS.cc
src/factories/fardetectors/MatrixTransferStatic_factory.h

[Backport v1.24] MatrixTransferStatic: move matrix configurations to config, implement OMD config for 130 GeV

---

src/algorithms/meta/SubDivideFunctors.h
src/services/geometry/richgeo/ReadoutGeo.cc

This PR corrects the class initialization ordering to conform to the order in which actual initialization happens.
No.
No.

fix: correct class initializer ordering

---

src/algorithms/digi/PulseNoise.cc
src/algorithms/digi/PulseNoise.h
src/algorithms/fardetectors/FarDetectorMLReconstruction.cc
src/algorithms/fardetectors/FarDetectorMLReconstruction.h
src/algorithms/fardetectors/FarDetectorTransportationPreML.cc
src/algorithms/fardetectors/FarDetectorTransportationPreML.h

This PR ensures that `process` functions of algorithms are const (enables easier multi-threaded operations). Some initialization that is only possible on first event is marked mutable.
No.
No.

fix: ensure algorithms satisfy const process function

---

src/algorithms/calorimetry/CalorimeterHitReco.cc
src/algorithms/calorimetry/TrackClusterMergeSplitter.h
src/algorithms/fardetectors/FarDetectorMLReconstruction.cc
src/algorithms/pid/MatchToRICHPID.cc
src/detectors/LOWQ2/LOWQ2.cc
src/tests/algorithms_test/digi_EICROCDigitization.cc
src/tests/algorithms_test/digi_SiliconPulseGeneration.cc

This PR fixes a few remaining signed comparisons and unused variable warnings.
No.
No.

fix: remaining signed comparisons and unused variable warnings

---

.github/lsan.supp

This PR fixes a new DD4hep-1.31 memory leak.
No.
No

fix(ci): leak; hide first fix later

---

.github/workflows/linux-eic-shell.yml

Since we specify in CMakeLists.txt that this project uses CXX only, we don't need to provide CC. This simplifies the yml file a bit.
No.
No.

fix(ci): remove CC, only use CXX

---

.github/workflows/linux-eic-shell.yml

This PR experiments with using a reusable workflow for (in this instance) list-open-prs. By placing this in a dedicate actions repository, it can be more easily reused across our repositories.
No.
No.

feat(ci): use reusable workflow call for list-open-prs

---

.github/lsan.supp

This PR suppresses a memory leak from upstream. Working on better monitoring for this upstream, but let's get this here unstuck.
No.
No.

fix: suppress upstream memory leak

---

.github/workflows/linux-eic-shell.yml
src/algorithms/calorimetry/ImagingClusterReco.h
src/extensions/jana/JOmniFactory.h
src/services/log/Log_service.cc

This PR ensures that we catch `#if EDM4EIC_VERSION_MAJOR >= 7` where `EDM4eicVersion.h` is not first included.
No.
No.

fix(ci): compile with -Wundef

---

src/algorithms/digi/CMakeLists.txt
src/services/geometry/dd4hep/DD4hep_service.h

Resolve missing symbols when loading plugins

---

.github/workflows/linux-eic-shell.yml

This PR adds a.
No.
Yes, will start posting clang-tidy comments again.

fix: add a

---

src/algorithms/tracking/DD4hepBField.h

This PR removes a code branch that is only taken for Acts versions that we don't support anymore.
No.
No.

fix: rm Acts<32 code branch

---

src/algorithms/interfaces/ActsSvc.h
src/algorithms/tracking/TrackSeeding.cc
src/algorithms/tracking/TrackSeeding.h
src/factories/tracking/TrackSeeding_factory.h

This PR switches the TrackSeeing algorithm over to the algorithms interface.
No.
No.

feat: switch TrackSeeding algorithm/factory to algorithms interface

---

src/algorithms/interfaces/ActsSvc.h
src/algorithms/tracking/TrackParamTruthInit.cc
src/algorithms/tracking/TrackParamTruthInit.h
src/factories/tracking/TrackParamTruthInit_factory.h

This PR switches the TrackParamTruthInit algorithm over to the algorithms interface.
No.
No.

feat: switch TrackParamTruthInit algorithm/factory to algorithms interface

---

src/algorithms/interfaces/ActsSvc.h
src/algorithms/tracking/TrackerMeasurementFromHits.cc
src/algorithms/tracking/TrackerMeasurementFromHits.h
src/factories/tracking/TrackerMeasurementFromHits_factory.h

This PR converts the TrackerMeasurementFromHits algorithm/factory to the proper algorithms interface syntax.
No.
No.

feat: switch TrackerMeasurementFromHits to algorithms interface

---

docs/design/tracking.md

This updates the track reconstruction documentation to reflect the latest status. This updated documentation was presented at the latest collaboration meeting. In the future, we will work to implement automated versions of these workflow charts.
No.
No.

Update track reconstruction documentation

---

.gitignore

This PR ignores calibrations, fieldmaps, gdml directories so they don't get accidentally committed, see https://github.com/eic/EICrecon/commit/f5ea2589771fa99222cf094f6c146e13ea79845d.
No.
No.

fix: .gitignore calibrations, fieldmaps, gdml

---

src/algorithms/tracking/AmbiguitySolver.cc

This PR adapts to https://github.com/acts-project/acts/pull/4570 in the EICrecon pipeline triggered by ACTS.
No.
No.

fix: AmbiguitySolver: avoid deprecated call on ACTS main

---

src/algorithms/tracking/ActsGeometryProvider.cc

This PR adapts to https://github.com/acts-project/acts/pull/4640 by including the right header and using the right namespace.
No.
No.

fix: adapt to acts#4640 which introduces ActsPlugins as namespace

---

src/algorithms/reco/ScatteredElectronsEMinusPz.h

This PR exposes the public `WithPodConfig` members in `ScatteredElectronsEMinusPz`.
No.
No.

Make WithPodConfig public in `ScatteredElectronsEMinusPz`

---

src/factories/reco/ScatteredElectronsEMinusPz_factory.h

This PR adds the parameter ref's and config application to the `ScatteredElectronsEMinusPz` factory.
No.
No.

Add missing config declaration/application to `ScatteredElectronsEMinusPz_factory`
