eic/EICrecon

.gitignore, src/CMakeLists.txt, src/cmake/jana_plugin.cmake, src/tests/CMakeLists.txt, src/tests/data_flow_test/CMakeLists.txt, src/tests/data_flow_test/OccupancyAnalysis.cc, src/tests/data_flow_test/OccupancyAnalysis.h, src/tests/data_flow_test/README.md, src/tests/data_flow_test/data_flow_test.cc
- **ecce is replaced with epic (BREAKING)**
- Some meta improvements in CMake system
- Plugin boilerplate macros-es are introduced:
- plugin_add, 
- plugin_glob_all, 
- plugin_include_direcotries, 
- plugin_link_libraries
- Example plugin is made
So I've made that plugin_* macros that minimizes plugins boilerplate to: 
```cmake
get_filename_component(PLUGIN_NAME ${CMAKE_CURRENT_LIST_DIR} NAME)
print_header(">>>>   P L U G I N :   ${PLUGIN_NAME}    <<<<")       # Fancy printing
plugin_add(${PLUGIN_NAME})
find_package(JANA REQUIRED)
find_package(EDM4HEP REQUIRED)
find_package(podio REQUIRED)
find_package(DD4hep REQUIRED)
find_package(ROOT REQUIRED)
plugin_glob_all(${PLUGIN_NAME})
plugin_include_directories(${PLUGIN_NAME} SYSTEM PUBLIC ${JANA_INCLUDE_DIR} ${podio_INCLUDE_DIR} …
```
=> CMake improvements with plugin example

src/detectors/BEMC/CMakeLists.txt, src/tests/data_flow_test/CMakeLists.txt
Linker on macOS does not allow unresolved symbols by default.
=> BEMC,data_flow_test: add missing library dependencies on fmt, DD4hep,EDM4HEP

src/detectors/BEMC/CMakeLists.txt
=> BEMC: add missing library dependencies on DD4hep and EDM4HEP

.gitignore, CMakeLists.txt, README.md, src/algorithms/CMakeLists.txt, src/detectors/BEMC/CMakeLists.txt, src/services/geometry/dd4hep/CMakeLists.txt, src/services/io/podio/CMakeLists.txt, src/services/randomgenerator/CMakeLists.txt, src/tests/BEMC_test/CMakeLists.txt, src/utilities/eicrecon/CMakeLists.txt, src/utilities/podio_copy/CMakeLists.txt, src/utilities/podio_read/CMakeLists.txt
- CMake minimum is 3.16
- CMP0074 policy is removed (since it is not needed anymore)
- Bug fixes
Closes: #28 #36 #33
=> CMake minimum is 3.16. Bug fixes

CMakeLists.txt, README.md, src/scripts/CMakeLists.txt, src/scripts/eicrecon-this.csh.in, src/scripts/eicrecon-this.sh.in, src/services/geometry/dd4hep/CMakeLists.txt, src/services/io/podio/CMakeLists.txt, src/services/randomgenerator/CMakeLists.txt, src/tests/BEMC_test/CMakeLists.txt
This moves the plugins installation directory to be inside the lib/EICrecon directory. This follows issue #136 posted to the JANA2 repository suggesting this in order to allow installing into a common directory tree, including /usr when installing in containers.
This also implements generation of a eicrecon-this.sh environment setup file using cmake variables used in the build. This may be used to reproduce enough of the environment to build a user end plugin that is compatible. (Currently, it is not setting the compiler since that is a more complicated issue).
=> Move plugins installation directory

CMakeLists.txt, README.md, src/scripts/eicrecon-this.sh.in, src/services/io/podio/CMakeLists.txt, src/services/io/podio/JEventSourcePODIOsimple.cc, src/services/io/podio/make_datamodel_glue.py, src/tests/BEMC_test/CMakeLists.txt, src/tools/cmake_wrapper.sh
This puts in support for EICD. This includes build instructions and integration into the podio event source.
This PR also includes:
1. fixes to cmake_wrapper.sh for integrating with CLion
2. Fix to BEMC_test install location
3. Disabling of the podio version checking (which seems to be broken on the podio side, yet, seemed to work previously?)
4. Bug fixes to the generated eicrecon.sh script
5. Up the version number for JANA to v2.0.7 in the documentation (no in cmake configuration yet)
6. Installation of the cmake tools to the EICrecon install directory so they can be used for out-of-repository plugin builds.
7. Updated README with instructions for building spdlog
=> EICD support

src/services/io/podio/JEventSourcePODIOsimple.cc, src/services/io/podio/JEventSourcePODIOsimple.h, src/services/io/podio/README.md, src/services/io/podio/podio.cc
This allows the user to specify a second podio file containing background events that are to be merged in with the primary events at the event source. User may also specify how many background events to merge in.
This currently merges ALL objects in the background event, including generated particles. 
No
No. One needs to specify the podio:background_filename to activate the new feature.
=> Add ability to merge background events in with the primary.

.gitignore, src/utilities/eicrecon/eicrecon.cc, src/utilities/eicrecon/eicrecon_cli.cpp, src/utilities/eicrecon/eicrecon_cli.h, src/utilities/eicrecon/print_info.h
- Add "-L"/"--list_factories" as a cli option. Print the factories given by [JComponentSummary](https://github.com/cissieAB/JANA2/blob/master/src/libraries/JANA/JApplication.h#L98). Use [JTablePrinter](https://github.com/cissieAB/JANA2/blob/master/src/libraries/JANA/Utils/JTablePrinter.h) to do the work.
- Turn off the irrelevant logger information given this option.
- Keep "-Ppodio:print_type_table=1" working with this option
Unclear. It better to split the jana::Flag into two categories: run and not run app. Otherwise when the option number increases, the logic will become too complicated to manage.
Eg. the behavior of "-b -L"
If this option is given, the application will not run.
=> Add cli option "-L"/"--list_factories"

docs/Use_with_eic_shell.md
Try to address #74. Cont. of #111 #113.
Fix the linked address of the bare-metal manual build guide.
No
No
=> Fix the linked address of the manual build guide

src/utilities/eicrecon/eicrecon.cc, src/utilities/eicrecon/eicrecon_cli.cpp, src/utilities/eicrecon/eicrecon_cli.h, src/utilities/eicrecon/print_info.h
- eicrecon "-h"/"-v" cleanup
- Replace "jana" with "eicrecon" in eicrecon helper info.
- Remove "-Phistsfile=file.root" in CLI option print info.
- Set eicrecon version to 0.0.0 instead of jana version.
- Add CLI options to list plugins
-  "--list_default_plugins": list the default plugins without running
- "--list_available_plugins": list all the plugins at $JANA_PLUGIN_PATH and $EICrecon_MY without running
No
No
=> Add cli options "--list_default_plugins" and "--list_available_plugins"

src/utilities/eicrecon/eicrecon_cli.cpp
Try to address issue #120. 
Use strcmp() to compare a const char * and a string, where the latter will cause warnings.
Also change the function names to be more consistent.
NA
NA
=> Use strcmp() to compare const char * and string

src/utilities/eicrecon/eicrecon_cli.cpp
In #119, if
- $EICrecon_MY is set but there is no $EICrecon/plugins
- $EICrecon/plugin is empty
The "--list_available_plugins" will give error msg.
Add the handler for the above two cases.
No
No
=> Fix getting plugins in empty or invalid paths

src/utilities/eicrecon/eicrecon.cc, src/utilities/eicrecon/eicrecon_cli.cpp, src/utilities/eicrecon/eicrecon_cli.h
Try to address issue #90 
> eicrecon currently adds a set of default plugins by having a line calling AddPlugin for each. This list should be placed into a vector so it can be listed and manipulated with command line options. 
Instead of manually adding the default plugins with `japp->AddPlugin()`, wrap it into a jana member function.
```C++
japp = jana::CreateJApplication(options);
japp->AddPlugin( "podio"            );
japp->AddPlugin( "..."            );
```
```C++
japp = jana::CreateJApplication(options);
jana::AddDefaultPluginsToJApplication(japp, default_plugins);
```
---
=> Update the way to add default plugins

src/services/io/podio/EICRootWriterSimple.cc, src/services/io/podio/JEventSourcePODIOsimple.cc, src/utilities/eicrecon/eicrecon_cli.cpp
=> Move podio params to "eicrecon -c" list

src/detectors/BEMC/TruthCluster_factory_EcalBarrelTruthProtoClusters.h, src/detectors/EEMC/TruthCluster_factory_EcalEndcapNTruthProtoClusters.h
EICD is defunct and not included in the containers anymore. It is only a matter of time before this fails (unless it's dead code).
@faustus123 The containers without eicd are probably still rolling out to cvmfs servers around the world. I check to make sure you are not depending on this anymore in CMakeLists.txt, but apparently it still has a few occurences in source files, likely included 'by accident' through some other convoluted path.
No.
No.
=> fix: eicd -> edm4eic

src/utilities/eicrecon/eicrecon.cc, src/utilities/eicrecon/eicrecon_cli.cpp, src/utilities/eicrecon/eicrecon_cli.h
The default plugins and $EICrecon_MY plugins were added by JApplictaion::AddPLugin(). They are not managed by the JParameterManager(), thus they will not be shown at the "eicrecon -c" option.
Now add the default and MY plugins via the cli option. Specifically, if there is a cli option says "-Pplugins_to_ignore=default", eicrecon would exclude all the default plugins. Note that we have to keep the original sequence of adding the default plugins, otherwise there would be troubles.
The default and MY plugins will be shown.
```bash 
nightly> xmei@xmei-lpt-wifi:~/eic/dev/EICrecon$ eicrecon -c
...
[INFO] Configuration Parameters
-------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Update the way to add default and MY plugins

src/global/tracking/ReconstructedParticle_factory.cc, src/global/tracking/ReconstructedParticle_factory.h, src/global/tracking/TrackParameters_factory.cc, src/global/tracking/TrackParameters_factory.h, src/global/tracking/TrackingResult_factory.cc, src/global/tracking/TrackingResult_factory.h, src/global/tracking/tracking.cc, src/tests/tracking_test/TrackingTest_processor.cc
Currently ReconstructedParticles are created out of tracking results. But PID and other info should be filled also, so there should be a split in data flow to two more entities ReconstructedParticles_factory and TrackParameters_factory. It also will let easy save of data to the resulting file
No
No
=> Add ReconstructedParticle and TrackParameters factories

src/scripts/eicmkplugin.py, src/utilities/eicrecon/eicrecon_cli.cpp
This fixes three issues:
1. Disables `eicrecon` from automatically attaching all plugins from `EICrecon_MY`
2. eicmkplugin.py generates code that links `spdlog` which is now needed by other core plugins
3. eicmkplugin.py generates code that uses the `rootfile` service for creating histograms in user histogram file.
No
Fixes some issues.
=> Davidl eicmkplugin eicrecon fixes

src/services/io/podio/JEventProcessorPODIO.cc, src/services/io/podio/JEventProcessorPODIO.h, src/utilities/eicrecon/eicrecon_cli.cpp
Fixes two problems encountered recently:
1. PODIO writer wouldn't call factory->Create() even if user explicitly asked for it via `podio:output_include_collections`
2. eicrecon timed out when nthreads>1 (See issue #87)
No
It changes the default thread timeout to 60 seconds.
=> PODIO writer now activates explicitly included factories

src/services/io/podio/JEventProcessorPODIO.cc, src/services/io/podio/RootWriter.cc, src/services/io/podio/RootWriter.h, src/tests/podio_test/podio_test.cpp
This addresses an issue that causes podio to throw an exception when collections that have one to many relations are being written to the output file, but the relation objects themselves are marked as "untracked".
No
Yes. Program will proceed with an error message now, but does not crash.
=> Fix bug that causes crashes when trying to write certain collections

src/algorithms/digi/SiliconTrackerDigi.cc
This fixes two bugs in the SiliconTrackerDigi algorithm.
1. The value for charge was being written into the timestamp and vice versa
2. The time units for the central value were changed from fs to ps. This also fixes an issue with the Gaussian smearing being in ps while the central value was in fs.
The digitized units should be revisited since 1fs LSB seems way too good. Especially for a devise that expects to have ~8ns resolution.
No
=> Fix bugs in SiliconTrackerDigi

src/global/tracking/TrackerHitCollector_factory.cc, src/global/tracking/tracking.cc
Made TrackerHitCollector to be in the right order of the tracking chain. Also set TrackerHitCollector  to not to own TrackerHits links closing #169
NO
NO
=> Fixing #169 and make correct order of tracking data flow

src/services/io/podio/JEventProcessorPODIO.cc, src/services/io/podio/JEventSourcePODIOsimple.cc, src/services/io/podio/podio.cc
This adds a default list of output collections to eicrecon so that it can be run with only a single argument: the input file. It will now automatically write most of the useful collections to the output.
This also adds a check that the input file exists before trying to open it with podio::RootReader. (I swear this is the 3rd time I've fixed this!) It will now print a bold error message and to a hard, immediate exit to ensure it is the last output from the program.
No.
Yes.
=> Davidl default outputs

src/algorithms/digi/SmearedFarForwardParticles.h, src/global/digi/ReconstructedParticle_factory_SmearedFarForwardParticles.h, src/global/digi/digi.cc, src/utilities/eicrecon/eicrecon.cc
This adds the SmearedFarForwardParticles to the list of default outputs. It should be merged after PR #179 .
No
Yes.
=> Add SmearedFarForwardParticles to default outputs

src/algorithms/reco/ParticlesWithAssociation.h, src/algorithms/tracking/ParticlesWithTruthPID.cpp, src/algorithms/tracking/ParticlesWithTruthPID.h, src/global/tracking/ParticlesWithTruthPID_factory.cc, src/global/tracking/ReconstructedChargedParticles_factory.cc, src/global/tracking/ReconstructedChargedParticles_factory.h, src/global/tracking/tracking.cc, src/tests/tracking_test/TrackingTest_processor.cc
Introduced `edm4eic::ReconstructedParticles` with tag `ReconstructedChargedParticles` which correspond to the same thing from Juggler. This data comes from MCParticles matching with tracks and has true PID. 
There are also minor improvement on tracking association of particles and its validation
NO
NO
=> Introduced ReconstructedChargedParticles factory

docs/_sidebar.md, docs/design/common_flags.md, docs/design/common_flags_env.md, src/services/geometry/dd4hep/JDD4hep_service.cc, src/services/geometry/dd4hep/JDD4hep_service.h
- Add DETECTOR_CONFIG 
- DETECTOR env still there but deprecated
- Improve how DETECTOR_PATH is used with `dd4hep:xml_files`. From docs: 
**dd4hep:xml_files** - Comma separated list of XML files describing the DD4hep geometry.
If xml_files are given and DETECTOR_PATH is set, then EICrecon first tries to open xml_file\[i\] if it fails, it tries
`${DETECTOR_PATH}/file`
```bash
eicrecon ... -Pdd4hep:xml_files=/full/path/epic.xml   # good
eicrecon ... -Pdd4hep:xml_files=epic.xml              # good if $DETECTOR_PATH is set /full/path/
eicrecon ... -Pdd4hep:xml_files=epic                  # fail, contrary to DETECTOR_CONFIG, this should be with extension
```
NO
NO
=> Improve DD4Hep service control by environment variables

src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelRawHits.h, src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapNRecHits.h, src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapPRecHits.h, src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapNRawHits.h, src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapPRawHits.h, src/detectors/HCAL/CalorimeterHit_factory_HcalBarrelRecHits.h, src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapNRecHits.h, src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPInsertRecHits.h, src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPRecHits.h, src/detectors/HCAL/RawCalorimeterHit_factory_HcalBarrelRawHits.h, src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapNRawHits.h, src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapPInsertRawHits.h, src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapPRawHits.h, src/detectors/ZDC/CalorimeterHit_factory_ZDCEcalRecHits.h, src/detectors/ZDC/RawCalorimeterHit_factory_ZDCEcalRawHits.h
corrects a smattering of issues with default parameters.  From the lack of instantiation of u_eRes, u_fields, u_refs to the miss tagging (especially in the HCAL).  Further several factories did not call app->SetDefaultParameter() on all of the parameters
- [x ] Bug fix (issue #__)
nothing
no, unless you count proper default instantiations as a change in behavior
=> a smattering of fixes for uninstantiated variables to miss taggings

.github/workflows/linux-eic-shell.yml
This upated the build-gcc job and adds a build-clang test. Also removes the unused `DETECTOR_LIBS_EPIC` options.
No.
No.
=> ci: update build-gcc and add build-clang tests

src/tools/default_flags_table/reco_flags.py
Shujie in det-tracking on Mattermost has requested a chi2 cutoff of 15 for track reconstruction, based on figures demonstrated there.
No.
Yes, lower chi2 cutoff, fewer outliers stored in output as accepted tracks.
=> tracking:CentralCKFTrajectories:Chi2CutOff = 15

src/services/io/podio/JEventProcessorPODIO.cc
Adds the HcalBarrelRawHits and HcalBarrelRecHits to default podio output. This well allow debug and testing of the clustering parameters with the first simulation campaign output. All the other calorimeters seem to have the corresponding quantities in the output, just not the barrel HCAL. 
No known breaking changes. 
Yes, the  HcalBarrelRawHits and HcalBarrelRecHits are now output by default
=> Add HcalBarrel raw and reco hits to output

.github/workflows/doxygen.yml, .github/workflows/linux-eic-shell.yml
Instead of using the version of eicrecon in the $PATH, the CI job needs the explicit path to both executable and plugins that points to the extracted artifact.
Also, remove apt_cache from artifacts and upgrade actions/checkout to v3 to avoid set-output warning.
No.
No.
=> fix(CI): use local install, not /usr/local

cmake/jana_plugin.cmake, docs/get-started/manual-build.md, src/detectors/CMakeLists.txt, src/detectors/RICH/CMakeLists.txt, src/detectors/RICH/CherenkovParticleID_factory_IrtParticleID.h, src/detectors/RICH/ParticleID_factory_IrtHypothesis.h, src/detectors/RICH/RICH.cc, src/scripts/eicrecon-this.sh.in, src/services/CMakeLists.txt, src/services/geometry/irt/CMakeLists.txt, src/services/geometry/irt/IrtGeo_service.cc, src/services/geometry/irt/IrtGeo_service.h, src/services/geometry/irt/irt.cc, src/services/geometry/irt/irtgeo/IrtGeo.cc, src/services/geometry/irt/irtgeo/IrtGeo.h, src/services/geometry/irt/irtgeo/IrtGeoDRICH.cc, src/services/geometry/irt/irtgeo/IrtGeoDRICH.h, src/services/geometry/irt/irtgeo/IrtGeoPFRICH.cc, src/services/geometry/irt/irtgeo/IrtGeoPFRICH.h
- introduces dependence on the standalone `irt` library (viz. `libIRT`)
- add `IrtGeo` class hierarchy for binding `dd4hep` geometry and `irt` geometry; these `IrtGeo` classes can also be used standalone, outside of `EICrecon`
- adds new service `geometry/irt`, similar to `geometry/acts`; it uses `IrtGeo` to produce the necessary `libIRT` objects from the `DD4hep` geometry
- begin `RICH` factories, to test the new `geometry/irt` service
To test, run:
```bash
eicrecon -Pplugins=irt,RICH -Ppodio:output_include_collections=IrtHypothesis [simulation file with DRICHHits]
```
No
No
=> feat!: add IRT geometry service for RICH PID

.github/workflows/linux-eic-shell.yml
This fixes the assumption in the CI workflows, and now doesn't overwrite `JANA_HOME` anymore but properly prepends `JANA_PLUGIN_PATH`.
No.
No.
=> fix(ci): prepend JANA_PLUGIN_PATH, not JANA_HOME

src/services/geometry/irt/irtgeo/IrtGeo.h
`irt` headers are installed in their own subdirectory, so `#include` directives should be consistent with this.
No
No
=> fix: use `IRT/` path for `irt` include directives

src/utilities/eicrecon/eicrecon.cc
This reshufles plugin order in EICRECON_DEFAULT_PLUGINS to fix the following error:
```
[ERROR] JPluginLoader: Couldn't load plugin 'acts.so'
Make sure that JANA_HOME and/or JANA_PLUGIN_PATH environment variables are set correctly.
Paths checked:
/lib/EICrecon/plugins//dd4hep.so  =>  Loaded successfully
/lib/EICrecon/plugins//acts.so  =>  Loading failure: /lib/EICrecon/plugins//acts.so: undefined symbol: _ZN11Log_service6loggerERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
./acts.so  =>  File not found
[FATAL] Exception: Couldn't find plugin 'acts.so'
```
=> utilities/eicrecon: load log plugin before others

src/utilities/dump_flags/DumpFlags_processor.h
The `std::ptr_fun` was deprecated since C++11 and removed in C++17
```
src/utilities/dump_flags/DumpFlags_processor.h:83:84: error: no member named 'ptr_fun' in namespace 'std'
std::transform(flag_name.begin(), flag_name.end(), flag_name.begin(), std::ptr_fun<int, int>(std::tolower));
~~~~~^
```
=> utilities/dump_flags: fix compilation with C++17

CMakeLists.txt, src/utilities/eicrecon/CMakeLists.txt, src/utilities/eicrecon/eicrecon_cli.cpp
The result of  `eicrecon --version` is set from root CMakeLists.txt
The version is now connected to CMake global project version
The version is now connected to CMake global project version
=> eicrecon version is set by root CMake project version

CMakeLists.txt, src/detectors/RICH/CMakeLists.txt, src/utilities/eicrecon/CMakeLists.txt, src/utilities/eicrecon/eicrecon_cli.cpp
Otherwise it fails not finding DD4Hep headers. Probably it works in container as headers are installed in system directories there. Or IDK. 
NO
NO
=> 288 rich detector needs dd4hep dependence

src/tools/default_flags_table/reco_flags.py, src/utilities/dump_flags/DumpFlags_processor.h
Now one can pass -P flags to reco_flags.py or run_eicrecon_reco_flags.py
```bash
python3 reco_flags.py -Pjana:timeout=0 input.edm4hep.root output_base_name
```
NO
NO
=> reco_flags.py now accepts -P parameter flags

src/tools/default_flags_table/reco_flags.py
Fixes #313. If an empty variable is explicitly defined in `reco_flags.py` then we should pass it.
No.
Yes, empty values are now passed to eicrecon. This may or may not lead to the same behavior as before... but at least now it is consistent behavior.
=> fix: pass empty flags as defined in `reco_flags.py`

src/tools/default_flags_table/reco_flags.py
Fixes #304. When we loop over `sys.argv` and remove the current entry of `sys.argv` inside that loop, then we will skip elements in the loop. This loops over a copy, and removes from the original `sys.argv`.
No.
No.
=> fix: copy sys.argv before element removal in loop

src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapPInsertRecHits.h, src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapPRecHits.h, src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapNRecHits.h, src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPInsertRecHits.h, src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPRecHits.h, src/detectors/HCAL/tmp2/CalorimeterHit_factory_HcalEndcapNRecHits.h, src/detectors/ZDC/CalorimeterHit_factory_ZDCEcalRecHits.h, src/tools/default_flags_table/reco_flags.py
Requires #314. Fixes #312. Set the `sectorField`
TODO:
No.
Yes. Should avoid warnings in running.
=> fix: define sector as empty string in reco_flags.py

src/detectors/RPOTS/ReconstructedParticle_factory_ForwardRomanPotParticles.h, src/detectors/RPOTS/TrackerHit_factory_ForwardRomanPotRecHits.h, src/tools/default_flags_table/reco_flags.py
- Fix the config. param names of the RPOTS factories to match collection names.
- Add RPOTS config. params to reco_flags.py
No
No
=> Correct RPOTS config param names and add them to reco_flags.py

src/utilities/dump_flags/DumpFlags_processor.h
The `std::ptr_fun` was deprecated since C++11 and removed in C++17
```
src/utilities/dump_flags/DumpFlags_processor.h:83:84: error: no member named 'ptr_fun' in namespace 'std'
std::transform(flag_name.begin(), flag_name.end(), flag_name.begin(), std::ptr_fun<int, int>(std::tolower));
~~~~~^
```
Additional regression since #286
=> utilities/dump_flags: fix compilation with C++17 (second pass)

src/services/geometry/dd4hep/JDD4hep_service.cc, src/services/io/podio/JEventSourcePODIOsimple.cc
Fixes compilation errors on macOS:
```
src/services/geometry/dd4hep/JDD4hep_service.cc:146:17: error: use of undeclared identifier '_exit'
_exit(-1);  // TODO isn't unhandled JException is a better way to abort the application
^
```
No
No
=> treewide: use std::exit

src/services/geometry/dd4hep/JDD4hep_service.cc, src/services/io/podio/JEventSourcePODIOsimple.cc
This reverses the change in PR #331 so that _exit is used unless running on macos. The use of _exit was very deliberately chosen so that the root exit handlers are bypassed, ensuring the last message on the screen is the one indicating the cause of the exit. When just using std::exit, you will get messages like the following printed *after* the message that the file doesn't exist:
~~~
Error in <TClass::LoadClassInfo>: no interpreter information for class TVirtualStreamerInfo is available even though it has a TClass initialization routine.
~~~
No
No
=> Restore use of _exit

src/services/io/podio/JEventProcessorPODIO.cc, src/utilities/eicrecon/eicrecon_cli.cpp, src/utilities/eicrecon/eicrecon_cli.h
- Change how objects from factories are retrieved for podio:output_include_collections so the call graph is properly recorded by JAN internal tracking feature.
- Add -j,--janaversion command line option to eicrecon so one can see the version of JANA it was compiled against.
No
No
=> Davidl janaversion

src/algorithms/calorimetry/ImagingPixelReco.h, src/detectors/BEMC/CalorimeterHit_factory_EcalBarrelImagingRecHits.h, src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelImagingRawHits.h
- Fix C++ parameters to match reco_flags.py 
- Fix where units are converted for dyRangeADC (only for EcalBarrelImagingRecHits)
No
No
=> Fix parameter values for Imaging Barrel. Fix where units are applied.

src/detectors/BEMC/BEMC.cc, src/detectors/BEMC/ProtoCluster_factory_EcalBarrelSciGlassTruthProtoClusters.h
This fixes the name of the `EcalBarrelTruthSciGlassProtoClusters` collection which should have been `EcalBarrelSciGlassTruthProtoClusters`.
No
No
=> Fix naming of EcalBarrelSciGlassTruthProtoClusters.

src/algorithms/calorimetry/ImagingClusterReco.h, src/algorithms/calorimetry/TruthEnergyPositionClusterMerger.h, src/detectors/BEMC/CalorimeterHit_factory_EcalBarrelScFiRecHits.h, src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelImagingRawHits.h, src/services/io/podio/RootWriter.cc, src/tools/default_flags_table/reco_flags.py
This fixes the Imaging Barrel calorimeter so that the `EcalBarrelImagingClusters` and `EcalBarrelImagingMergedClusters` are written out. This was tested with single 10GeV e- events (see attached plots). 
The main issue was with podio refusing to write collections that references "untracked" objects. This is a known issue with the podio+JANA2 implementation. The "fix" was to disable adding the references to the cluster objects.
No
Yes, it makes it work.
=> Fix Imaging Barrel Ecal Clustering

src/detectors/B0ECAL/Cluster_factory_B0ECalClusters.h, src/detectors/B0ECAL/Cluster_factory_B0ECalMergedClusters.h
E.g. reco_flags defines `B0ECAL:B0ECalClusters:depthCorrection` but parameter is not called that. This makes sure the parameters also have B0ECAL prefixes.
No.
No.
=> fix: use B0ECAL not EEMC in B0EcalClusters

src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapNRecHits.h, src/detectors/EEMC/Cluster_factory_EcalEndcapNTruthClusters.h, src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapNRawHits.h
This propagates the EcalEndcapN parameters from reco_flags.py to the factories.
=> fix: add default Ecal Endcap N params in factories

src/detectors/MPGD/MPGD.cc
Make MPGD defaults consistent with reco_flags. See https://github.com/eic/EICrecon/blob/main/src/tools/default_flags_table/reco_flags.py#L722-L724. @mposik1983 
No.
Yes, consistent with reco_flags.
=> fix: MPGDTrackerHit:TimeResolution default 8 ns

.github/workflows/linux-eic-shell.yml
This introduces the CI test to ensure flags are propagated to the factories. Then it will also include the propagation of those flags.
No.
Yes. It will make default behavior correct.
=> fix: ensure reco_flags.py are propagated to defaults in factories

src/utilities/eicrecon/eicrecon_cli.cpp
Warn if a parameter is defined twice (and ignored the second time). Fixes #370.
No.
No.
=> fix: warn when duplicate parameter is ignored

.github/workflows/linux-eic-shell.yml
The build takes 15 minutes, and likely most files don't change frequently. We can use ccache to speed up. Rather than implementing the caching twice, this moves the builds with gcc and clang into a matrix build. This improves build times to 3 minutes:
No.
No.
=> ci: build as matrix; use ccache

.github/workflows/linux-eic-shell.yml, src/tools/default_flags_table/reco_flags.py
Allow the user to override default parameters specified by `reco_flags.py` by putting them first. Fixes #370.
No.
No.
=> fix: define default parameters after user parameters in `reco_flags.py`

.github/workflows/linux-eic-shell.yml
Removes "report" step and generation of python files with flags and flags.md page. This all has been replaced by using output flags.json directly (from eicrecon run with dump_flags). Report step can be re-instantiated later... when there will be something else to report. 
NO
NO
=> Fix CI failure on redundatnt flags python generation

src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/digi/PhotoMultiplierHitDigi.h, src/algorithms/digi/PhotoMultiplierHitDigiConfig.h, src/global/digi/PhotoMultiplierHitDigi_factory.cc, src/global/digi/PhotoMultiplierHitDigi_factory.h
Add the ability to cut on the boundaries of an XY-segmented SiPM sensor, to simulate gaps between SiPM pixels. Also adds an overall safety factor, to account for the non-ideal reality.
no
no
=> feat: SiPM pixel gap cuts

cmake/jana_plugin.cmake, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTracking.h, src/algorithms/tracking/CKFTrackingFunction.cc, src/algorithms/tracking/JugTrack/Measurement.hpp, src/algorithms/tracking/JugTrack/TrackingResultTrajectory.hpp, src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackPropagation.cc
In order to test the EPIC geometry upgrade to use Acts-20 construction, we need to have a reconstruction framework that is able to work with that Acts version. This upgrades EICrecon tracking algorithms to work with Acts-20.2.0 and beyond.
Yes, there is no backwards compatibility for older Acts versions.
No.
=> feat: support Acts-20.2.0 and beyond (within 20.x release series)

.github/workflows/linux-eic-shell.yml
Introduce CI job that runs `valgrind --tool=memcheck`. No automatic CI pipeline failure on memory leaks.
No.
No.
=> ci: valgrind memcheck on eicrecon

src/algorithms/calorimetry/CalorimeterClusterMerger.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterTruthClustering.cc
This removes some of the memory leaks, in particular in the calorimetry algorithms. This does **not** address #414 since that requires a but if a different approach than simply matching a `delete` to each `new`.
Fixes #412. Fixes #413.
No.
No.
=> fix: remove memory leaks in calorimetry algorithms

src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPInsertMergedHits.h
Issue #410 is resolved by replacing the tag name with the correct name instead of defining it twice in different factories.
=> fix: use HcalEndcapPInsertMergedHits tag in factory

src/detectors/EEMC/ProtoCluster_factory_EcalEndcapPInsertIslandProtoClusters.h, src/detectors/EEMC/ProtoCluster_factory_EcalEndcapPIslandProtoClusters.h
The name of all EEMC:EcalEndcapPIslandProtoClusters:* parameters was encoded as EEMC:EcalEndcapPClusters:* in the factories. That means none of those settings in reco_flags were actually taking effect.
No.
No.
=> fix: EEMC:EcalEndcapPIslandProtoClusters:* parameters

.github/workflows/linux-eic-shell.yml, src/algorithms/tracking/OrthogonalTrackSeedingConfig.h, src/algorithms/tracking/TrackSeeding.cc, src/algorithms/tracking/TrackSeeding.h, src/global/tracking/TrackSeeding_factory.cc
This PR allows users to configure the seeding parameters from the command line when running eicrecon. This should enable easier testing/tuning so that eicrecon doesn't have to be compiled each time someone wants to change one of the seeding algorithm parameters.
No
No
=> Command line configuration of seeding parameters

src/algorithms/calorimetry/CalorimeterIslandCluster.h
In CalorimeterIslandClustering, we compare the hit distances with the sector distance `sectorDist`. The EDM4hep units (hits) are mm = 1 while the dd4hep units (sectorDist parameter) are cm = 1. We need an explicit conversion.
No.
Yes, some other calorimeter parameters would need changing if they are determined only on the basis of observed clusters.
=> fix: ensure sectorDist is compared with hit distance in right units.

src/utilities/dump_flags/DumpFlags_processor.cc, src/utilities/dump_flags/DumpFlags_processor.h
This modifies the dump_flags plugin.
This adds writing of the JANA configuration at the end of a job in the standard format of a JANA config. file. This supplements the existing options of writing JSON, Python and dumping to screen.  
No
No
=> Add writing default JANA config file format.

src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/digi/PhotoMultiplierHitDigi.h, src/algorithms/digi/PhotoMultiplierHitDigiConfig.h, src/detectors/DRICH/DRICH.cc, src/global/pid/RichTrack_factory.cc, src/tools/default_flags_table/reco_flags.py
Since we have moved away from `reco_flags.py` and _still_ do not have a simple way to set user parameters (e.g. #346), this PR sets the default parameters for the dRICH by hard-coding them in C++ (in other words, https://github.com/eic/EICrecon/pull/408 for the dRICH)
no
no
=> fix: set default dRICH config in `c++`

src/algorithms/tracking/TrackParamTruthInit.h
`m_cfg` was defined with same type in both CRTP base (protected) and derived (public), but somehow no compiler was warning. This caused the settings for the truth seeding to not take hold.
Fun with godbolt, https://godbolt.org/z/e3W4j41Wv
No.
No.
=> fix: avoid m_cfg shadowing

src/global/reco/MatchClusters_factory.h, src/global/reco/reco.cc
~~This enables cluster matching with tracks in all calorimeters, not just the negative endcap and sciglass. This should allow the kinematics determination to work for brycecanyon too, since it requires the output of the cluster matching to find the electron track.~~
Cluster matching is not actually implemented or run at all. The only thing the MatchCluster factory does is pass the charged particles and associations. But because it requires sciglass clusters as input, it fails to complete even this minimal task for brycecanyon.
No.
Yes. Brycecanyon should get some more kinematics output.
=> feat: cluster matching is not actually implemented, so don't make sciglass a requirement

src/algorithms/tracking/OrthogonalTrackSeedingConfig.h
Checked and defined macro names don't match
=> OrthogonalTrackSeedingConfig.h: fix invalid include guard

src/algorithms/calorimetry/CalorimeterIslandCluster.cc, src/algorithms/calorimetry/CalorimeterIslandCluster.h, src/detectors/BEMC/ProtoCluster_factory_EcalBarrelScFiProtoClusters.h, src/detectors/BEMC/ProtoCluster_factory_EcalBarrelSciGlassProtoClusters.h, src/detectors/EEMC/ProtoCluster_factory_EcalEndcapNIslandProtoClusters.h, src/detectors/EEMC/ProtoCluster_factory_EcalEndcapPInsertIslandProtoClusters.h, src/detectors/EEMC/ProtoCluster_factory_EcalEndcapPIslandProtoClusters.h, src/detectors/HCAL/ProtoCluster_factory_HcalBarrelIslandProtoClusters.h, src/detectors/HCAL/ProtoCluster_factory_HcalEndcapNIslandProtoClusters.h, src/detectors/HCAL/ProtoCluster_factory_HcalEndcapPInsertIslandProtoClusters.h, src/detectors/HCAL/ProtoCluster_factory_HcalEndcapPIslandProtoClusters.h
This introduces the adjacency matrix into calorimeter island clustering and is a port of https://github.com/eic/juggler/pull/2 into eicrecon. Copying the comments from original author @veprbl into this PR.
The issue with the current implementation is that `is_neighbour()` relies on geometrical dimensions of a calorimeter being used. This makes it cumbersome and error-prone to enable clustering for different detectors. The goal is to instead use readout cellID fields.
This PR suggests a following interface for doing that: A new parameter `adjacencyMatrix` is added to describe the adjacency of the sensitive elements. It can be used replace the existing settings like `localDistXY`. The value specified must be a string expression (to be evaluated by DD4hep evaluator) that returns a "boolean" …
=> feat: add adjacency matrix in calorimeter clustering

src/services/geometry/rich/richgeo/IrtGeo.h
```
src/services/geometry/rich/RichGeo_service.cc:73:18: warning: delete called on 'rich::IrtGeo' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
if(m_irtGeo) delete m_irtGeo;
^
```
No
No
=> IrtGeo: mark destructor as virtual

src/detectors/B0ECAL/ProtoCluster_factory_B0ECalIslandProtoClusters.h, src/detectors/ZDC/ProtoCluster_factory_ZDCEcalIslandProtoClusters.h
We hadn't propagated the adjacency matrix addition to the B0ECAL and ZDC island clustering factories.
No.
No.
=> fix: propagate adjacency matrix to B0ECAL and ZDC island clustering

src/detectors/BEMC/ProtoCluster_factory_EcalBarrelSciGlassProtoClusters.h
When there are spaces in the adjacency matrix string expression's default value, JANA2 chops at the first space. This results in many warnings, i.e. https://github.com/eic/EICrecon/actions/runs/4121127389/jobs/7116665443.
The issue seems to be in the `SetDefaultParameter` call, since modifying `u_adjacencyMatrix` in the algorithm didn't have any impact. At that point the string has already been chopped.
No.
No.
=> fix: remove spaces in adjacency matrix expression

.github/workflows/linux-eic-shell.yml
I'd been wondering why the artifacts kept increasing in size... Default directory even after checkout is in ~ which is also where .ccache lives.
No.
No.
=> fix(ci): keep .git and .ccache out of artifacts

.github/workflows/linux-eic-shell.yml
It would seem like the first command should start an empty file
Found a very minor defect while staring at diff of #489
No
No
=> ci: avoid duplicating entries in ccache.conf

src/algorithms/calorimetry/CalorimeterHitReco.cc, src/algorithms/calorimetry/CalorimeterHitReco.h, src/detectors/BEMC/CalorimeterHit_factory_EcalBarrelScFiRecHits.h, src/detectors/BEMC/ProtoCluster_factory_EcalBarrelScFiProtoClusters.h
It's part of the solution to #499 
related to https://github.com/eic/epic/pull/370
No, it adds an option to use the mother volume's position of a hit
No, by default this option is turned off.
=> add position masks for hit reco

src/algorithms/calorimetry/CalorimeterIslandCluster.h
Relational operators have higher precedence than logical, so this is purely for readability
=> CalorimeterIslandCluster.h: add brackets

.github/workflows/linux-eic-shell.yml
=> linux-eic-shell.yml: give some steps better names

src/detectors/BEMC/ProtoCluster_factory_EcalBarrelSciGlassProtoClusters.h
A critical bug is present in the original expression:
`(abs(dx) + (abs(dy) == 1) + (abs(dy) = 1234)) == 1`
Allows for arbitrary `dy` in range `[2, 1233]` as long as `abs(dx) == 1`. That caused merging of the clusters in across the azimuthal direction.
No
No
=> BUGFIX: ProtoCluster_factory_EcalBarrelSciGlassProtoClusters: fix adjacencyMatrix

src/algorithms/calorimetry/CalorimeterHitReco.cc
As hoc fix for now. We should evaluate this in more detail later: what is the dimension stored for, and why as a 3D bounding box in some cases and as a 2D surface-constrained coordinate in other cases?
=> fix: OOB read of cellDimensions

src/examples/track_matching/reco_particles_track_matching.cc
Fixes the following warning:
```
EICrecon/src/examples/track_matching/reco_particles_track_matching.cc: In function ‘int main()’:
EICrecon/src/examples/track_matching/reco_particles_track_matching.cc:59:35: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
59 |     reco_particles_track_matching("/home/romanov/eic/soft/eicrecon/main/src/examples/test_data_generator/2022-11-15_pgun_pi-_epic_arches_e0.01-30GeV_alldir_4prt_1000evt_reco.tree.edm4eic.root");
|                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
no
no
=> fix: forbidden string conversion warning from `reco_particles_track_matching.cc`

src/algorithms/calorimetry/CalorimeterIslandCluster.h
Wrap around for when |delta phi| >= pi (helps to not miss cases when delta phi \approx \pm 2pi)
No
No
=> CalorimeterIslandCluster: wrap around azimuthal distance

src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelScFiRawHits.h
The current value was introduced in 13b9c92188d9cacedc5c4b9ca0c80404c21f1c3e. There should have been three values, and using units for those doesn't make sense from the dimensional analysis point (terms are divided by sqrt(E), 1 and E respectively). Each element of the array would need to have its own unit, but the commonly accepted convention is to use fractions and assume GeV. The actual behavior in reconstruction is not changed by this PR, because the values stay the same.
See also https://github.com/eic/EICrecon/issues/573
=> EcalBarrelScFiRawHits: revert back to unitless definitions

src/algorithms/digi/SiliconTrackerDigi.cc, src/global/digi/SiliconTrackerDigi_factory.h, src/global/tracking/TrackerHitReconstruction_factory.h
Remove unused headers.
No.
No.
=> fix: remove references to TGeoSystemOfUnits

src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapNRawHits.h
The MeV multipliers were introduced in #408, but they don't make sense from the dimensional analysis point (terms are divided by sqrt(E), 1 and E respectively). Each element of the array would need to have its own unit, but the commonly accepted convention is to use fractions and assume GeV. This commit restores that convention. The actual behavior in reconstruction is not changed by this PR, because the values stay the same.
cc #573
=> EcalEndcapNRawHits: revert back to unitless definitions

src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterHitDigi.h, src/detectors/B0ECAL/RawCalorimeterHit_factory_B0ECalRawHits.h, src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelImagingRawHits.h, src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelScFiRawHits.h, src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelSciGlassRawHits.h, src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapNRawHits.h, src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapPInsertRawHits.h, src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapPRawHits.h
The purpose of this change is to provide explicit units for different smearing terms.
This removes CalorimeterHitDigi::eRes that is declared as unitless.
This is as suggested by @wdconinc in https://github.com/eic/EICrecon/pull/582#issuecomment-1498337700
Closes: #585
Fixes: #573
=> RawCalorimeterHit_factory_: specify u_eRes with units

src/algorithms/reco/JetReconstruction.cc
Move constraint on particle transverse momentum from the recording of constituents to restricting what particles are included in the clustering.
No
No
=> JetReconstruction: apply pT constraints before running jet algorithm

src/algorithms/tracking/OrthogonalTrackSeedingConfig.h
This PR modifies the calculation of the transverse momentum per unit radius so that it is now in ACTS units. The original equation seems to have been copied from here:
https://github.com/acts-project/acts/blob/main/Core/include/Acts/Seeding/SeedFinderConfig.hpp#L258
It is mentioned there that the calculation should be updated to ACTS units.
In any event, this change seems to have a negligible effect on the output of the seed finder.
No
No
=> Updated a calculation in seeder configuration to ACTS units

src/detectors/EEMC/ProtoCluster_factory_EcalEndcapNIslandProtoClusters.h
Switching to adjacencyMatrix, assuming we are going to migrate other detectors to it as well.
=> EcalEndcapNIslandProtoClusters: switch to using adjacencyMatrix

src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/digi/PhotoMultiplierHitDigi.h, src/detectors/DRICH/DRICH.cc, src/global/digi/PhotoMultiplierHitDigi_factory.cc, src/global/digi/PhotoMultiplierHitDigi_factory.h
**NOTE**: This PR targets the branch associated with https://github.com/eic/EICrecon/pull/599, and therefore adds on to it.
- output both the raw hits and associations, using the new `JMultifactory` feature
- new `struct PhotoMultiplierHitDigiResult` is used as the return value of `AlgorithmProcess` (rather than a `std::pair`, for better flexibility and readability)
- switch from `std::vector`s of raw pointers to PODIO collections
- unrelated: style changes to `DRICH.cc` to be more consistent with #393 (we are factorizing that giant PR into smaller PRs, and these changes will make this process a bit easier)
no
no
=> feat: output raw hits and associations from `PhotomultiplierHitDigi`

src/services/io/podio/JEventSourcePODIO.cc, src/services/io/podio/JEventSourcePODIOLegacy.cc, src/services/io/podio/make_datamodel_glue.py
This adds the required `auto`s to support both current and future `podio::getTypeName` signatures. 
Ref: https://github.com/AIDASoft/podio/pull/402, https://github.com/AIDASoft/podio/pull/404
No.
No.
=> feat: `auto` podio::getTypeName for both string/string_view support

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h
Cluster shape properties are calculated from the 3D covariance matrix of hits within a cluster.
2 coordinate system options are provided: eta-phi-z and x-y-z, which can be toggled with the m_xyClusterProfiling variable.
This adds to the existing routine, which has been moved out of the header file and into the CalorimeterClusterRecoCoG.cc.
- [ x ] New feature (issue #__)
=> Add 3D cluster shape analysis

docs/design/naming_conventions.md, src/algorithms/reco/MatchClusters.cc, src/algorithms/reco/MatchClusters.h, src/detectors/FHCAL/Cluster_factory_LFHCALClusters.h, src/detectors/FHCAL/Cluster_factory_LFHCALTruthClusters.h, src/examples/track_matching/reco_particles_track_matching.cc, src/global/reco/MatchClusters_factory.cc, src/global/reco/MatchClusters_factory.h, src/global/reco/reco.cc, src/global/tracking/tracking.cc, src/services/io/podio/JEventProcessorPODIO.cc, src/tests/tracking_test/TrackingTest_processor.cc
Re-enables MatchClusters algorithm. 
**Yes**. Some collections have been renamed: 
- "ReconstructedChargedParticlesAssociations" => "ReconstructedChargedParticleAssociations"
- "LFHCALClustersAssociations" => "LFHCALClusterAssociations"
- "LFHCALTruthClustersAssociations" => "LFHCALTruthClusterAssociations"
No
=> Re-enable MatchClusters algorithm

src/detectors/MPGD/MPGD.cc
Update MPGD digi threshold value based on digitization table: https://docs.google.com/spreadsheets/d/1s8oXj36SqIh7TJeHFH89gQ_ayU1_SVEpWQNkx6sETKs/edit#gid=238482234
No.
Yes, 0.25 keV threshold is applied for MPGD hit digitization. Prior code used 0 keV threshold for digitization.
=> MPGD: Update digi threshold value based on digitization table

src/global/reco/InclusiveKinematicsDA_factory.cc, src/global/reco/InclusiveKinematicsElectron_factory.cc, src/global/reco/InclusiveKinematicsJB_factory.cc, src/global/reco/InclusiveKinematicsSigma_factory.cc, src/global/reco/InclusiveKinematicseSigma_factory.cc, src/global/reco/reco.cc
Track/cluster matching in MatchClusters is now active and doesn't just return the reconstructed charged particles and their associations. However, until the clusters themselves get converted to multifactories and get associations, this doesn't result in any matched results, not even the reconstructed charged particles.
Rather than living without any x and Q2 in the campaign (a quick way to check overall performance since it relies on everything going right), this reverts the inclusive kinematics explicitly to using reconstructed charged particles without information from the cluster matching.
Woud like to backport into the v1.1 branch and include in a v1.1.1 bugfix release to use in the 23.05 campaign.
No.
No.
=> fix: only use reconstructed charged particles in inclusive kinematics, until cluster matching works

src/services/io/podio/JEventProcessorPODIO.cc
We have a working (somewhat) MatchClusters, but don't write the ReconstructedParticleAssociations collection. This adds that to the output.
No.
Adds new output collection ReconstructedParticleAssociations.
=> feat: write ReconstructedParticleAssociations into output file

src/utilities/eicrecon/CMakeLists.txt, src/utilities/eicrecon/eicrecon.cc
The `eicrecon` utility does not require `TFile.h` nor does it need to link to ROOT.
=> fix: do not include unused TFile in eicrecon

src/detectors/LUMISPECCAL/ProtoCluster_factory_EcalLumiSpecIslandProtoClusters.h
for pair of towers with
```c++
ev.setVariable("module_1", 31);
ev.setVariable("module_2", 40);
```
```
(sector_1==sector_2)&&((abs(ceil(module_1/10)-ceil(module_2/10))+abs(fmod(module_1,10)-fmod(module_2,10)))==1)
```
evaluates to 1 (incorrect), and
```
(sector_1==sector_2)&&((abs(floor(module_1/10)-floor(module_2/10))+abs(fmod(module_1,10)-fmod(module_2,10)))==1)
```
evaluates to 0 (correct)
=> ProtoCluster_factory_EcalLumiSpecIslandProtoClusters: fix minor defect in adjacencyMatrix

src/detectors/BEMC/CalorimeterHit_factory_EcalBarrelScFiRecHits.h
Updated the value of the threshold factor from 5 to 36.00488 to have a threshold of 0.5MeV
=> EcalBarrelScFiRecHits: update value of thresholdFactor

src/algorithms/calorimetry/CalorimeterHitReco.h, src/detectors/RPOTS/RomanPotsReconstruction_factory.h
This is needed to facilitate #514
src/algorithms/calorimetry/CalorimeterHitReco.h:80:23: runtime error: implicit conversion from type 'int' of value -1 (32-bit, signed) to type 'size_t' (aka 'unsigned long') changed the value to 18446744073709551615 (64-bit, unsigned)
src/detectors/RPOTS/RomanPotsReconstruction_factory.h:68:22: runtime error: implicit conversion from type 'int' of value -1 (32-bit, signed) to type 'size_t' (aka 'unsigned long') changed the value to 18446744073709551615 (64-bit, unsigned)
=> CalorimeterHitReco, RomanPotsReconstruction_factory: fix UBSAN error regarding converting -1 to size_t

src/algorithms/tracking/TrackPropagation.cc, src/algorithms/tracking/TrackPropagation.h, src/detectors/DRICH/DRICH.cc, src/global/pid/RichTrackConfig.h, src/global/pid/RichTrack_factory.cc, src/global/pid/RichTrack_factory.h, src/tests/track_propagation_test/TrackPropagationTest_processor.cc, src/tests/track_seeding_test/TrackSeedingTest_processor.cc
- return `Collection` of `TrackSegments` in `TrackPropagation::propagateToSurfaceList`, rather than a (potentially leaky) new `TrackSegment` pointer
- the loop over input trajectories is moved from `RichTrack_factory` to `TrackPropagation::propagateToSurfaceList`, which makes the PR diff appear to be more complex than it actually is
- fix additional possible memory leaks by replacing any `return new raw_pointer` calls with `return std::make_unique<...>(...)`, and update any code which depends on this change
- improve the configuration with `RichTrackConfig`, which configures the _factory_, not the algorithm, since the factory is used to connect to the `richgeo` service (and not the more general `TrackPropagation` algorithm)
no, unless the `TrackPropagation` algorithm is called by anything …
=> refactor+fix: use collections and multi-factory in `RichTrack_factory`; fix potential leaks in `TrackPropagation`

src/algorithms/calorimetry/CalorimeterHitReco.cc
Not all segmentation types will be ordered as XYZ. One notable example: CartesianStripZ gives only one dimension, which triggers ASAN error.
This implements only support for CartesianGridXY. It is assumed that we should be looking to deprecate dimension field from EDM4eic. Hence, this implementation only fixes the case which have worked before. The case where wrong coordinates were set before will now report warnings and use the cartesian bounding box.
=> CalorimeterHitReco: proper handling for segmentation for dimension

src/global/digi/PhotoMultiplierHitDigi_factory.cc, src/global/pid/RichTrack_factory.cc, src/global/tracking/CKFTracking_factory.cc, src/global/tracking/IterativeVertexFinder_factory.cc, src/global/tracking/ParticlesWithTruthPID_factory.cc, src/global/tracking/TrackParamTruthInit_factory.cc, src/global/tracking/TrackProjector_factory.cc, src/global/tracking/TrackSeeding_factory.cc, src/global/tracking/TrackerHitReconstruction_factory.cc, src/global/tracking/TrackerSourceLinker_factory.cc, src/global/tracking/TrackingResult_factory.cc, src/tests/track_propagation_test/TrackPropagationTest_processor.cc, src/tests/track_seeding_test/TrackSeedingTest_processor.cc
There are several factories that `catch` exceptions in underlying algorithms and just print a warning. We should try to `throw` these exceptions instead, however:
- there may still be some algorithms where this is not a good idea, in other words, there may be a reason just printing a warning message is preferred; IMO this should be fixed in the algorithm and we shouldn't just be warning on exceptions
- this PR likely does not address all of the cases
no, but there may be "regular" warning messages that are now thrown exceptions
maybe (see bullet points above)
=> fix: throw exceptions for algorithm failures, instead of warning printouts

src/algorithms/CMakeLists.txt, src/algorithms/pid/CMakeLists.txt, src/algorithms/pid/MergeTracks.cc, src/algorithms/pid/MergeTracks.h, src/detectors/DRICH/DRICH.cc, src/global/pid/MergeTrack_factory.cc, src/global/pid/MergeTrack_factory.h, src/global/pid/RichTrack_factory.cc, src/global/pid/RichTrack_factory.h, src/tests/algorithms_test/CMakeLists.txt, src/tests/algorithms_test/pid_MergeTracks.cc
- Add an algorithm to merge propagated tracks from dRICH aerogel and gas.
- Prefer to keep in `pid` algorithms, since:
- avoid cluttering `tracking` algorithms
- this is (currently) only used by PID, though it is a general algorithm for combining `TrackSegments`
- it's incomplete, only combining the `TrackPoint`s (sorting them by time); we currently don't need the other members downstream for PID
- Add CMake file for `pid` algorithms library
- there are more `plugin_add_*` calls needed for this PR, however, they will be needed for the full set of `pid` algorithms, so we might as well include them now (see #393)
no
no
=> feat(dRICH): merge track propagations

src/algorithms/calorimetry/CalorimeterHitReco.cc
Reduces the level of output in the CalorimeterHitReco by not printing the cell dimensions as an `error` for each hit in each event.
No.
No.
=> fix: print cell dimensions as debug in CalorimeterHitReco

src/tests/algorithms_test/CMakeLists.txt, src/tests/algorithms_test/calorimetry_CalorimeterHitDigi.cc
Should cover some of the current features. Major exception is `CalorimeterHitDigi::signal_sum_digi`, as DD4hep services are not yet supported in unit tests.
=> add algorithms/test/calorimetry_CalorimeterHitDigi.cc

src/detectors/DRICH/README.md
Documentation for the dRICH PID. This is a bit ahead of `main`, but is up-to-date for our [development branch `irt-algo`](https://github.com/eic/EICrecon/pull/393); therefore, part of it represents plans for `main`.
- @chchatte92 
- @alexander-kiselev 
- @DelloStritto
no
no
=> doc(dRICH): PID algorithms and collections

src/global/tracking/TrackParamTruthInit_factory.cc
This adds theta/phi debug output to truth seeder, which was useful when running the seeder in debug mode for matching studies.
No.
No.
=> feat: add theta/phi debug output to truth seeder

src/algorithms/calorimetry/CalorimeterHitReco.cc
A calorimeter with NoSegmentation gives no reco hits. This is because cell_dim should be calculated inside the if statement. Otherwise, since a calorimeter such as LFHCAL uses NoSegmentation, the library is terminated when calculating the cell_dim.
No. Users do not need to change their code.
No.
=> CalorimeterHitReco: Fix calo giving no reco hits when using NoSegmentation

.github/workflows/pr-backport.yml
This allows one to create labels with special name like `backport v1.2` that would automatically create a PR to duplicate change into a maintenance branch.
=> Add GitHub action for PR backporting

src/algorithms/digi/PhotoMultiplierHitDigiConfig.h, src/detectors/DRICH/DRICH.cc
Extrapolate endpoints of the quantum efficiency curve down to zero. Two points are added:
| wavelength | quantum efficiency |
| --- | --- |
| 315 nm | 0.0 |
| 1000 nm | 0.0 |
This is a minor change, applied to both the default config `PhotoMultiplierHitDigiConfig`  and the dRICH-specific config in `DRICH.cc` (along with a syntax simplification).
This goes along with other material property extrapolations from https://github.com/eic/epic/pull/445
- @chchatte92 
no
no, but `<NPE>` will increase slightly
=> fix(dRICH): extrapolate quantum efficiency endpoints

src/detectors/DRICH/README.md
Final reconstructed particle and association collections do not include the suffix `WithDRICHPID` (this is a remnant of an older design).
no
no
=> doc(dRICH): remove dRICH spec from reconstructed particle collections

src/algorithms/reco/MatchClusters.cc
This shifts the cluster map erase after the use of the cluster. Erase before use is an error in the address sanitizer branch.
No.
No.
=> fix: MatchClusters.cc, use before delete (asan)

.github/workflows/linux-eic-shell.yml
There is an issue in DD4hep that results in excessive output being generated by `ddsim` in default `INFO` log level. This reduces the output to only `WARNING` logging.
No.
No.
=> ci: run `ddsim` with `-v WARNING`

src/global/tracking/tracking.cc
This fixes the tracking for me locally. Presumably this failed before (likely not silently but without an error return code because EICrecon depends on failing without error codes).
=> fix: missing comma in tracking.cc

src/algorithms/reco/ElectronReconstruction.cc, src/algorithms/reco/ElectronReconstruction.h, src/global/reco/ReconstructedElectrons_factory.h, src/global/reco/reco.cc, src/services/io/podio/JEventProcessorPODIO.cc
Provides electron candidates as a first step towards a DIS electron finder.
This PR uses the recently provided MC particle to Reco cluster associations to produce a `ReconstructedElectrons` collection. Electrons candidates are identified with an E/p cut using Reco particle momentum and Redo cluster energy (only from ECAL detectors for now).
Couple of comments/potential improvements for reviewers:
- I am not sure how best to use the Config objects to allow parameters to be modified (e.g. min/max E/p in this case)
- AFAIK this creates a copy of the reconstructed particles - since this (ReconstructedElectrons) is a strict subset of the ReconstructedParticles collection, is there a way to store as such (without duplicating)
- I am currently pulling from (by name) several locations (see …
=> Add reconstructed electron factory, algorithm utilizing E/p cut 

src/detectors/FOFFMTRK/OffMomentumReconstruction_factory.h
Without `JFactoryPodioT`, eicrecon doesn't produce errors, completes fine, and has no OffMomentum reconstructed particles.
This may also affect:
```console
[2023-07-13 11:50:32.483] [JEventProcessorPODIO] [warning] Explicitly included collection 'EcalBarrelImagingMergedClusterAssociations' not present in factory set, omitting.
```
No.
Yes, OffM tracker reconstruction will now work.
=> fix: OffMomentumReconstruction_factory should use JFactoryPodioT

src/algorithms/calorimetry/CalorimeterClusterRecoCoGConfig.h
Adds required `#include <string>` header where it is not transitively included.
No.
No.
=> fix: `#include <string>` in CalorimeterClusterRecoCoGConfig

src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/pid/IrtCherenkovParticleID.cc, src/algorithms/reco/JetReconstruction.cc, src/algorithms/tracking/TrackSeeding.cc, src/services/geometry/richgeo/IrtGeo.cc
Constructing an element at the end of a container doesn't require a temporary copy followed by `push_back`, but can be done with `emplace_back`.
See https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-emplace.html.
No.
No.
=> fix: clang-tidy modernize-use-emplace

src/algorithms/calorimetry/CalorimeterClusterMerger.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterIslandCluster.cc, src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/reco/InclusiveKinematicsDA.cc, src/algorithms/reco/InclusiveKinematicsElectron.cc, src/algorithms/reco/InclusiveKinematicsJB.cc, src/algorithms/reco/InclusiveKinematicsSigma.cc, src/algorithms/reco/InclusiveKinematicsTruth.cc, src/algorithms/reco/InclusiveKinematicseSigma.cc, src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc
This propagates a number of suggested clang-tidy changes related to testing whether a container is empty. Containers may implement `size()` differently from `empty()`, and `size()` may run in O(n) instead of constant time. This means that `empty()` is preferred by clang-tidy for performance reasons. Moreover, `empty()` improves readability, and avoids implicit bool conversion (as in `if (!split.size())`).
See https://clang.llvm.org/extra/clang-tidy/checks/readability/container-size-empty.html for details
No.
No.
=> fix: clang-tidy readability-container-size-empty

.github/workflows/linux-eic-shell.yml
Fix for failures like https://github.com/eic/EICrecon/actions/runs/5556691154/jobs/10150278283
https://github.com/actions/runner-images/issues/7452
=> linux-eic-shell.yml: fix the apt-get failures

src/algorithms/tracking/TrackParamTruthInit.cc
Fixes: 95aa36c2 ('fix: rewrite TrackParamTruthInit to create edm4eic::TrackParameters (#766)')
When reviewing #766, the assumption was that the PR was supposed to implement a refactoring and result in no change. There was a minor defect that wasn't discovered during the review. A pair of constants were switched. This PR reverts that change.
There is however another, actually significant remaining effect, unlike the `eicrecon::TrackParameters` the `edm4eic::TrackParameters` can't propagate values from `Acts::PerigeeSurface`. Instead, global position = {0, 0, 0} is used now:
https://github.com/eic/EICrecon/blob/95aa36c2b652b4b78b0c8024786c0d5c9dbcad85/src/global/tracking/CKFTracking_factory.cc#L82-L83
If we take the old commit dd98b254d228896a40ebbee088f693fe44b6d2c8 and apply
```diff
diff …
```
=> TrackParamTruthInit: revert accidental swap of theta and phi error values

CMakeLists.txt
Like #775 this compresses debug symbols when supported. I think this is a useful default.
No.
Yes, by default compresses debug symbols.
=> feat: use -gz if supported in Debug and RelWithDebInfo

.github/workflows/linux-eic-shell.yml
Instead of a separate artifact for each jana.dot, this puts them all into a single artifact. That then makes it easier to publish them on GitHub Pages.
TODO:
No.
No.
=> ci: collect all jana.dot and jana.svg into single artifact, and publish

src/detectors/B0ECAL/B0ECAL.cc, src/detectors/BEMC/BEMC.cc, src/detectors/BHCAL/BHCAL.cc, src/detectors/EEMC/EEMC.cc, src/detectors/EHCAL/EHCAL.cc, src/detectors/FEMC/FEMC.cc, src/detectors/FHCAL/FHCAL.cc, src/detectors/LUMISPECCAL/LUMISPECCAL.cc, src/detectors/ZDC/ZDC.cc, src/factories/calorimetry/CalorimeterClusterRecoCoG_factoryT.h
The wordiness of the current factory-factory,
```cpp
class Cluster_factory_EcalBarrelSciGlassTruthClusters :
public CalorimeterClusterRecoCoG_factoryT<Cluster_factory_EcalBarrelSciGlassTruthClusters>
{
public:
template <typename... Args>
Cluster_factory_EcalBarrelSciGlassTruthClusters(Args&&... args)
:  CalorimeterClusterRecoCoG_factoryT<Cluster_factory_EcalBarrelSciGlassTruthClusters>(std::forward<Args>(args)...)
{ }
};
```
has been bothering me since #666. This always seemed like it should be possible to express it more elegantly, with a `using` or so.
However, the naive approach
```cpp
using Cluster_factory_EcalBarrelSciGlassTruthClusters =
CalorimeterClusterRecoCoG_factoryT<Cluster_factory_EcalBarrelSciGlassTruthClusters>;
```
fails out of the gate since you can't use the lhs in the …
=> feat: make the factory-factory a variadic template (more evil things)

src/services/io/podio/JEventProcessorPODIO.cc
The realistic seed finder is emitting NaNs to the CKF tracking algorithm. This causes crashes in CI test jobs at a high false positive rate. This PR removes the realistic seed finder from the default. It can be added again with `-Ppodio:output_include_collections` for studies. 
As a general note, algorithms should not emit NaNs, and rather than using `isnan` as a cleanup step, the algorithms writers should understand where NaNs are created (e.g. sqrt negative numbers, division by zero, over- or underflow) and should test for domain validity. Most likely the presence of NaNs is pointing to incorrect assumptions when the algorithm is applied.
No.
No.
=> fix: disable default inclusion of realistic seeder

src/algorithms/reco/MC2SmearedParticle.cc
The GeneratedParticles branch all MCParticles which are thrown into the detector, in the ReconstructedParticles format (for easy comparison). This means we should not include `generatorStatus == 0` as was the case until now.
No.
Yes, excludes secondary particles (which should be determined from MCParticles based on the bit pattern in simulatorStatus).
=> fix: GeneratedParticles: ignore MCParticles with generatorStatus != 1

src/algorithms/reco/Beam.h, src/algorithms/reco/InclusiveKinematicsDA.cc, src/algorithms/reco/InclusiveKinematicsDA.h, src/algorithms/reco/InclusiveKinematicsElectron.cc, src/algorithms/reco/InclusiveKinematicsElectron.h, src/algorithms/reco/InclusiveKinematicsJB.cc, src/algorithms/reco/InclusiveKinematicsJB.h, src/algorithms/reco/InclusiveKinematicsSigma.cc, src/algorithms/reco/InclusiveKinematicsSigma.h, src/algorithms/reco/InclusiveKinematicsTruth.cc, src/algorithms/reco/InclusiveKinematicsTruth.h, src/algorithms/reco/InclusiveKinematicseSigma.cc, src/algorithms/reco/InclusiveKinematicseSigma.h, src/global/reco/InclusiveKinematicsDA_factory.cc, src/global/reco/InclusiveKinematicsDA_factory.h, src/global/reco/InclusiveKinematicsElectron_factory.cc, src/global/reco/InclusiveKinematicsElectron_factory.h, src/global/reco/InclusiveKinematicsJB_factory.cc, src/global/reco/InclusiveKinematicsJB_factory.h, src/global/reco/InclusiveKinematicsSigma_factory.cc, src/global/reco/InclusiveKinematicsSigma_factory.h, src/global/reco/InclusiveKinematicsTruth_factory.cc, src/global/reco/InclusiveKinematicsTruth_factory.h, src/global/reco/InclusiveKinematicseSigma_factory.cc, src/global/reco/InclusiveKinematicseSigma_factory.h
This converts the InclusiveKinematics algorithms and factories (back) to using podio collections (from `std::vector<T*>`).
Because JANA2 expects `std::unique_ptr`, the algorithms are creating `std::unique_ptr`s of the collections. Ultimately it may be nice to just create collection and `std::move` it...
No.
No.
=> feat: rewrite InclusiveKinematics algorithms to operate on podio collections

src/global/reco/reco.cc
This removes an include of a removed header, removed in #778.
When we run CI tests, we use an eic-shell container that has EICrecon already installed. That means that removing a header file in the test build can still cause that header file to be found in the system directories. This then only shows up in an actual clean build later on.
Short of revamping our CI, I don't really know of a way to prevent this from happening in the short term.
No.
No.
=> fix: rm failing MC2SmearedParticleConfig include

src/services/geometry/acts/ACTSGeo_service.cc
The `calibrations/materials-map.cbor` path can now be passed via the geometry instead of being hard-coded in the reconstruction code. This was causing difficulties since brycecanyon and craterlake were forced to write to `calibrations/materials-map.cbor`. This allows us now to write to different files.
No.
No. Reverts to previous behavior until defined in geometry.
=> fix: read `materials-map` string constant in ACTSGeo_service

src/detectors/BEMC/BEMC.cc
As of https://github.com/eic/epic/pull/490, the naming of the sectors of the imaging and scfi is now correct in the readout field. This is reqiured because there are now actual modules implemented (i.e. chip modules placed on staves). The hierarchy/nomenclature defined by the DSC is system > sector > layer > stave > module > pixel (x,y).
No.
No.
=> fix: rename imaging/scfi module to sector

src/algorithms/tracking/TrackParamTruthInitConfig.h
Update max eta forward limit to 6 to take far forward events into account for reconstruction by default
No
No
=> update max eta forward limit in truth seeder to 6

src/services/io/podio/make_datamodel_glue.py
We specify the working dir where datamodel glue headers are written as a key-value pair argument, `WORKING_DIR=dir`. If we then take field 1 after a split on '=', we discard parts of the directory if it contains '=' characters. This fixes the split to only split on the first '=' character.
Use case: when we build a git tag or branch in spack, we give an equivalent version for dependency resolution purposes, e.g `eicrecon@git.feature-branch=v1.4.0`. For the version of spack we are using, this leads to staging directories with that full version string.
No.
No.
=> fix: allow for = in working dir for datamodel glue

src/global/tracking/CKFTracking_factory.cc, src/services/geometry/acts/ACTSGeo_service.cc, src/services/geometry/acts/ACTSGeo_service.h
The reason for pausing the jana ticker is because the ActsGeo takes long to initialize. This moves the pausing to that initialization.
Also, opportunistically:
- renamed class member `init_flag` to `m_init_flag` for consistency,
- removed commented lines,
- corrected license header for explicitly derived code.
No.
No. Maybe during long-duration tracking steps, there will now be tickers shown whereas previously they were suppressed completely during all tracking.
=> fix: move jana ticker pausing from CKFTracking into ActsGeo service

src/global/tracking/CKFTracking_factory.cc, src/global/tracking/CKFTracking_factory.h, src/global/tracking/tracking.cc
This converts the CKFTracking factory to a multifactory without any other changes. This is a preparation for a next changes that has the CKFTracking factory emit also podio collections.
No.
No.
=> feat: convert CKFTracking factory to multifactory

src/algorithms/tracking/ParticlesFromTrackFit.cc, src/algorithms/tracking/ParticlesFromTrackFit.h, src/benchmarks/reconstruction/tracking_efficiency/TrackingEfficiency_processor.cc, src/global/tracking/TrackingResult_factory.cc, src/global/tracking/TrackingResult_factory.h, src/global/tracking/tracking.cc
This removes the unused output{Seeded}Particles collection from the tracking plugin, and removes the ReconstructedParticle output from the TrackingResult algorithm and factory.
The construction of ReconstructedParticles (which includes PID information) is not something that should be done at this stage of the track reconstruction chain (and indeed the results are ignored).
The `TrackingEfficiency_processor` was updated to process the `ReconstructedChargedParticles` collection which is (later) produced from tracks.
No.
No.
=> fix: rm unused output{Seeded}Particles from TrackingResult_factory

src/services/log/Log_service.cc, src/services/log/Log_service.h
During development, it is often needed to diff log files, which can be cumbersome if timestamps are printed. It doesn't seem like we have a strong need to get timestamps in the production logs at the time, but if that will be needed, it can now be re-enabled using eicrecon::LogFormat option.
=> services/log: remove timestamp from log messages, allow configuring format

src/algorithms/calorimetry/CalorimeterHitDigi.cc
Towards the goal of unifying the two code patch, this changes signal_sum_digi to have an identical smearing using only a single random number. Both procedures are mathematically identical for large samples, but using a single number is simpler.
no
not in a significant way
=> CalorimeterHitDigi: use energy same smearing in signal_sum_digi as in single_hits_digi

src/algorithms/calorimetry/CalorimeterHitDigi.cc
There is no point to iterate over hit contributions twice - `timeC` already contains the earliest time.
No
No
=> CalorimeterHitDigi: remove duplicate calculation from signal_sum_digi

CMakeLists.txt, src/services/io/podio/CMakeLists.txt
This will force rebuilding of the datamodel glue headers in local development copies when the data model changes version.
Depends on:
No.
No.
=> fix: depend on datamodel version headers in datamodel glue

.github/workflows/linux-eic-shell.yml
We set `if_no_artifact_found: warn` on the action-download-artifact (when the default is `fail`), but then we fail anyway because the next step can't find the file. If we don't want to fail, we shouldn't run the next step.
TODO:
No.
No.
=> ci: don't fail when if_no_artifact_found: warn

src/algorithms/tracking/TrackerHitReconstruction.h, src/global/tracking/TrackerHitReconstruction_factory.cc
The time resolution specified on the command line or in the tracking.cc file was ignored for the tracker hit reconstruction (only). This fixes that issue so the timeError is set correctly when the hits are sent to ACTS for track fitting.
Changes in the output to be expected:
- timeError in B0, TOF endcap (all others are set to default values),
- potential for different track fit parameters downstream of these collections.
Ref https://github.com/eic/EICrecon/pull/840#issuecomment-1692340071, bullet 1.
TODO:
No.
Yes, this will cause B0 and TOF time to be as set in tracking.cc, i.e.
```
src/detectors/B0TRK/B0TRK.cc:    hit_reco_cfg.time_resolution = 8;
src/detectors/ECTOF/ECTOF.cc:    hit_reco_cfg.time_resolution = 0.025;
```
=> fix: apply the specified time resolutions to tracking reco algorithm

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTracking.h, src/global/tracking/CKFTracking_factory.cc
This moves the conversion of the initial track parameters into ActsExamples structures from the CKFTracking factory into the algorithm, for improved modularity and algorithm reuse. No other changes. Diffs should come back clean.
No.
No.
=> fix: mv init TrackParameters edm4eic to ActsExamples conversion into algorithm

src/algorithms/calorimetry/CalorimeterHitDigi.cc
There was an edge case when all hits could be skipped in the previous loop and then the algorithm would still proceed to add a hit with edep=0. Most common case to trigger that, would be if there is only a single hit (e.g. if we were to use this code path for calorimeters for which the hit merging is not required).
No
No
=> CalorimeterHitDigi: don't add a hit when none of the merged hits meet the timing requirement

src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/digi/PhotoMultiplierHitDigi.h, src/algorithms/digi/PhotoMultiplierHitDigiConfig.h, src/algorithms/pid/IrtCherenkovParticleID.cc, src/detectors/DIRC/DIRC.cc, src/detectors/DRICH/DRICH.cc, src/global/digi/PhotoMultiplierHitDigi_factory.cc, src/services/geometry/richgeo/IrtGeo.h, src/services/geometry/richgeo/IrtGeoDRICH.cc, src/services/geometry/richgeo/ReadoutGeo.cc, src/services/geometry/richgeo/ReadoutGeo.h
Updates respecting https://github.com/eic/epic/pull/331 
- `richgeo`:
- use DD4hep `VariantParameters` to streamline access to sensor positioning and orientation
- various updates respecting https://github.com/eic/epic/pull/331 
- tests of sensor positioning and orientation are moved to `epic` with that PR
- respect the readout field change: `module` -> `pdu` and `sipm`
- method `richgeo::ReadoutGeo::PixelGapMask` was cut and pasted from `PhotoMultiplierHitDigi` 
- `PhotoMultiplierHitDigi`:
- move pixel gap (mask) cuts to `richgeo` service in `ReadoutGeo`
- delete config parameter `PhotoMultiplierHitDigiConfig::pixelSize`, since it can be obtained from `richgeo`
yes: this PR should be merged at the same time as
- https://github.com/eic/epic/pull/331
- …
=> refactor(dRICH): compatibility update for PDU readout

src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterHitDigi.h
This should be easier to maintain. We probably could even refactor merging into
a separate algorithm, if we wanted to.
A side effect of this is that non-merging digitization now reorders hits (the
cell id is used as a key for an std::unordered_map).
No
Yes, the hits will be reordered.
=> CalorimeterHitDigi: unified code path for digitization with and without the hit merging

src/detectors/DRICH/DRICH.cc, src/detectors/DRICH/README.md
Fix dRICH track propagation by using `CentralCKFActsTrajectories` instead of `CentralCKFTrajectories`
no
yes, should restore functionality to dRICH
=> fix(dRICH): `CentralCKFTrajectories` -> `CentralCKFActsTrajectories`

src/detectors/DIRC/CMakeLists.txt, src/detectors/DRICH/CMakeLists.txt
Link the DIRC and DRICH detector plugins against the src/global/digi library to resolve PhotoMultiplierDigi factory.
No.
No.
=> fix: link DIRC/DRICH detectors against digi_library with PhotoMultiplierDigi_factory

src/detectors/BHCAL/BHCAL.cc
This PR updates the BHCal minimum energy thresholds applied during digitizaiton and clustering based on discussions from the calorimeter and background working groups (see [this spreadsheet](https://docs.google.com/spreadsheets/d/1s8oXj36SqIh7TJeHFH89gQ_ayU1_SVEpWQNkx6sETKs/edit?pli=1#gid=238482234)).
No.
Yes. Only tiles with at least 5 MeV deposited in them will be digitized and passed on to reconstruction.
=> Update BHCal energy thresholds

src/services/io/podio/JEventProcessorPODIO.cc
This removes collections that are not produced by anything. This just adds noise to the logs, e.g.
```console
[JEventProcessorPODIO] [info] Persisting collection 'EcalLumiSpecTruthClusterAssociations'
[JEventProcessorPODIO] [info] Persisting collection 'EcalLumiSpecTruthClusters'
[JEventProcessorPODIO] [info] Persisting collection 'ForwardMPGDEndcapRecHits'
[JEventProcessorPODIO] [info] Persisting collection 'ForwardOffMRecParticles'
Warning: ocessorPODIO] [warning] Explicitly included collection 'ForwardOffMTrackerRecHits' not present in factory set, omitting.
Warning: ocessorPODIO] [warning] Explicitly included collection 'ForwardRomanPotRecHits' not present in factory set, omitting.
[JEventProcessorPODIO] [info] Persisting collection 'ForwardRomanPotRecParticles'
[JEventProcessorPODIO] …
```
=> fix: don't try to write non-existent collections

src/services/io/podio/JEventProcessorPODIO.cc
Include dRICH output collections in default `eicrecon`.
no
yes, new output collections
=> feat!: enable dRICH PID in production

src/algorithms/pid/ParticlesWithPID.cc
Reduce noisy log messages in `ParticleWithPID`
no
no
=> fix: change "no matching CherenkovParticleID" log level `warn` -> `trace`

src/algorithms/pid/ParticlesWithPID.cc
The std::hypot method used to define p_mag in ParticlesWithPID.cc by default returns a float. This is insufficient precision when looking at particles travelling very close to the beam axis.
This PR changes to using the edm4eic vector utils methods which return doubles.
Additionally the eta and phi tolerance values provided to match the MC and reconstructed particles do not make sense for the particles along the beamline so if both are below -5 they are assumed to match.
no
no
=> Changed kinematic calculations to use edm4eic vector utils in ParticlesWithPID

src/detectors/CMakeLists.txt, src/detectors/LOWQ2/CMakeLists.txt, src/detectors/LOWQ2/LOWQ2.cc, src/services/io/podio/JEventProcessorPODIO.cc, src/utilities/dump_flags/DumpFlags_processor.h, src/utilities/eicrecon/eicrecon.cc
Adds a basic LowQ2 plugin which only digitizes the simulated hits using the standard silicon digitization factory
no
Adds digitized lowq2 tagger hits to output
=> Added LowQ2 plugin with hit digitization

src/algorithms/tracking/ActsGeometryProvider.cc, src/algorithms/tracking/TrackProjector.cc, src/extensions/spdlog/SpdlogFormatters.h
One of the largest source of slow builds is the inclusion of `Eigen` headers indirectly in many source files. This removes one of these instances. Rather than including and using `Eigen::MatrixBase<T>` in the SpdlogFormatters header, this moves the 'expensive' formatters to the source files where they are used.
No.
No.
=> fix: move Eigen out of SpdlogFormatters

.github/workflows/linux-eic-shell.yml
Since we run doxygen in alpine, and since alpine doesn't come with any fonts installed, we need to install at least one font. `ttf-freefont` is 17 MB, and smaller than `ttf-dejavu`, and it has both serif and sans serif typefaces.
See e.g. https://wdconinc.github.io/EICrecon/doxygen/classACTSGeo__service.html which uses this fix.
No.
No.
=> docs: apk add ttf-freefont for graphviz without boxes

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h, src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterHitReco.cc, src/algorithms/calorimetry/CalorimeterHitReco.h, src/algorithms/calorimetry/CalorimeterIslandCluster.cc, src/algorithms/calorimetry/CalorimeterIslandCluster.h, src/algorithms/calorimetry/CalorimeterTruthClustering.cc, src/algorithms/calorimetry/CalorimeterTruthClustering.h, src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/digi/PhotoMultiplierHitDigi.h, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTracking.h, src/algorithms/tracking/CKFTrackingFunction.cc, src/algorithms/tracking/IterativeVertexFinder.h, src/algorithms/tracking/IterativeVertexFinderConfig.h, src/algorithms/tracking/TrackSeeding.h
Unused headers in source files, but even more importantly in other headers, slows down compilation unnecessarily and potentially moves necessary includes behind a smokescreen. For example, by including `JDD4hep_service.h` in an algorithm, you may indirectly include `DD4hep/Detector.h`, but this should be done manifestly in the places that need it.
No.
No.
=> fix: unused header cleanup

src/utilities/eicrecon/eicrecon_cli.h
When `alignas` is overridden as a macro, we want to fail compilation. This allows us to ensure that this code is only used with patched JANA2 versions or future releases which don't define `alignas` as a macro.
No.
No.
=> fix: trigger compilation error when `alignas` is a macro

src/global/tracking/tracking.cc
Because JANA2 redefines `alignas` https://github.com/JeffersonLab/JANA2/blob/master/src/libraries/JANA/Utils/JResourcePool.h#L43-L46, we have been including an Acts header before any JANA headers in tracking.cc, just to get ACTS stuff loaded before JANA breaks it. Instead of loading Navigator (and all its Eigen dependencies) we can also just load the only relevant header: `boost/container/small_vector.hpp`. But really, this should be fixed in JANA, at https://github.com/JeffersonLab/JANA2/issues/238. `alignas` is a [formal part of the C++11 standard](https://en.cppreference.com/w/cpp/language/alignas) and should not be modified.
No.
No.
=> fix: avoid including Navigator.hpp in tracking.cc

src/tests/algorithms_test/pid_MergeParticleID.cc
Resolve warning: non-void lambda does not return a value in all control paths.
no
no
=> fix: Compiler warning in src/tests/algorithms_test/pid_MergeParticleID.cc

.github/workflows/linux-eic-shell.yml
This will prevent main pipelines from being interrupted by newer merges. This is becoming relevant in times of frequent merges. Because we do one or two extra things on main (like not just running clang-tidy on diffs only), the merge queue will complete faster than the previous main pipeline, so we risk just canceling every main pipeline...
No.
No.
=> feat(ci): no cancel-in-progress on main

.github/workflows/linux-eic-shell.yml
`JANA_PLUGIN_PATH` in eic-shell (and therefore CI environments) is prepopulated with `/usr/local/lib/EICrecon/plugins:/usr/local/plugins`. This means that removing (intentionally or otherwise) a plugin in a PR will still cause it to be found in `/usr/local/lib/EICrecon/plugins`. We need `/usr/local/plugins` though, because that contains the `janadot` plugin to create callgraphs.
There's an issue reported to JANA2 (https://github.com/JeffersonLab/JANA2/issues/136) that points out that installing plugins in a shared namespace at `/usr/local/plugins` may lead to issues and does not conform to the linux FHS. But at least EICrecon plugins are not installed there, otherwise we would have exactly this issue.
No.
No.
=> fix(ci): don't use pre-filled JANA_PLUGIN_PATH with EICrecon plugins

src/services/geometry/richgeo/ReadoutGeo.cc
This fixes the memory overrun in e.g. https://github.com/eic/EICrecon/actions/runs/6176955368/job/16769656988.
Fixes: c9ceddc0275c911065d9c3658a51d646264ca63e ('feat: SiPM pixel gap cuts')
=> fix: use xyz_g[3] in richgeo/ReadoutGeo.cc

.github/workflows/linux-eic-shell.yml
We are trying to exercise the whole pipeline, but not throwing any optical photons. This means the dRICH does not currently see anything and we don't test the reconstruction and particle matching.
This is expected to result in 1) changes, 2) slower simulation running, 3) dragons.
No.
No.
=> fix(ci): use npsim instead of ddsim

src/utilities/CMakeLists.txt, src/utilities/eicrecon/eicrecon.cc, src/utilities/janatop/CMakeLists.txt, src/utilities/janatop/JEventProcessorJANATOP.h, src/utilities/janatop/janadot.cc
This plugin produces a final table with top link requests and top factory consumers. This will allow us to figure out where our CPU time is going (in particular the factory consumers list shows that). I don't know yet if the top link requests is so useful or interpretable...
Example output:
```console
[INFO] All workers have stopped.
[INFO] Merging threads ...
[INFO] JArrow: Finalized JEventProcessor 'JEventProcessorPODIO'
Links:
20 calls, 2.68 s (  3.0%) JEventProcessorPODIO -> edm4eic::ReconstructedParticle:GeneratedJets
20 calls, 0.00 us (  3.1%) JEventProcessorPODIO -> edm4eic::TrackSegment:CalorimeterTrackProjections
10 calls, 3.08 s (  3.4%) edm4eic::MCRecoClusterParticleAssociation:LFHCALClusterAssociations -> edm4eic::ProtoCluster:LFHCALIslandProtoClusters
20 calls, 3.14 s ( …
```
=> feat: new janatop plugin, i.e. janadot without the svg output

.github/workflows/linux-eic-shell.yml
This should (again) prevent the main CI workflows from canceling older pipelines when newer commits/merges are added. The `ref_name` should be the full ref name, not just `main`, but `refs/heads/main`.
No.
No.
=> fix(ci): cancel in progress when ref_name != refs/heads/main

src/detectors/DRICH/DRICH.cc
This disables the cheatTrueRadiator and cheatPhotonVertex codes in the DRICH IrtCherenkovParticleID_factory configuration. This should reduce the number of warnings about non-optical photon hits on the DRICH sensors.
No.
Yes. No more cheating.
=> fix: disable DRICH radiator and photon vertex cheat code

src/services/geometry/richgeo/ReadoutGeo.cc
=> [Backport v1.5] fix: use xyz_g[3] in richgeo/ReadoutGeo.cc

src/detectors/DRICH/DRICH.cc
=> [Backport v1.5] fix: disable DRICH radiator and photon vertex cheat code

.github/workflows/linux-eic-shell.yml, CMakeLists.txt
This will (hopefully) fix the ctest failures in CI. We were not explicit about how we want rpath to be handled in the build tree (now we are), but more importantly on binaries the rpath settings in CMake set the RUNPATH elf record, which is lower precedence than the entries in LD_LIBRARY_PATH. That means that any executable (such as the test executable) will still defer to LD_LIBRARY_PATH, if set. So, we unset it for ctest.
This doesn't affect our other executable, eicrecon, because that isn't actually linked against anything (or nothing that is internal to our source tree). Instead it uses the dlopen to plugins explicitly in JANA_PLUGIN_PATH. When those are opened, the rpath to their dependencies is respected.
No.
No.
=> fix: use RPATH in build tree, unset LD_LIBRARY_PATH for ctest

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h
A memory leak was caused by creating a new pointer `cl`, then push_back `*cl`, but not deleting the pointer. This modifies the algorithm to use objects instead of pointers. RVO and podio object encapsulation should ensure performance is not affected.
Leak sanitizer output resolved:
```
Direct leak of 108512 byte(s) in 13564 object(s) allocated from:
#0 0x55cbc7e9fded in operator new(unsigned long) (/home/wdconinc/git/EICrecon/.worktree/main/bin/eicrecon+0xeaded) (BuildId: 4702f11c9afe7b8bff422367fb6901ebdee7ea40)
#1 0x7f92f7afe251 in eicrecon::CalorimeterClusterRecoCoG::reconstruct(edm4eic::ProtoCluster const&) const /home/wdconinc/git/EICrecon/.worktree/main/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc:293:10
#2 0x7f92f7af9dc9 in …
```
=> fix: memory leak in CalorimeterClusterRecoCoG

src/algorithms/tracking/CKFTracking.cc
When there are no track tips, we should delete the ActsExamples::Trajectories before moving on to the next one.
Fixes:
```
Direct leak of 128928 byte(s) in 1343 object(s) allocated from:
#0 0x556fe8256ded in operator new(unsigned long) (/home/wdconinc/git/EICrecon/.worktree/main/bin/eicrecon+0xeaded) (BuildId: 7089f1e0b4fe65f89c79d38a99df5a0d1554ba34)
#1 0x7f0f0594cb83 in eicrecon::CKFTracking::process(boost::container::flat_multiset<std::reference_wrapper<ActsExamples::IndexSourceLink const>, ActsExamples::detail::CompareGeometryId, void> const&, std::vector<std::variant<Acts::Measurement<Acts::BoundIndices, 1ul>, Acts::Measurement<Acts::BoundIndices, 2ul>, Acts::Measurement<Acts::BoundIndices, 3ul>, Acts::Measurement<Acts::BoundIndices, 4ul>, Acts::Measurement<Acts::BoundIndices, 5ul>, …
```
=> fix: resolve CKFTracking memory leak

Doxyfile
This enables include diagrams (and much more documentation diagrams) by not requiring the explicit adding of documentation tags like `\headerfile` etc. It produces for example the following included-by diagram for `ActsGeometryProvider.h`:
TODO:
No.
No.
=> docs: Doxyfile EXTRACT_ALL = YES

src/algorithms/calorimetry/CalorimeterHitReco.cc
This addresses an ubsan error because 0 is a signed integer. In other places, we avoid this by expliclitly using a `static_cast<size_t>(0)` (another option could be a literal, `0ull`).
No.
No.
=> fix: avoid undefined behavior in signed integer 0 bitwise complement

src/algorithms/pid/IrtCherenkovParticleID.cc, src/algorithms/pid/MergeTracks.cc
This avoids undefined behavior flagged by ubsan in the statement `std::size_t n_tracks = -1;` and in the signed/unsigned integer comparisons in the pid system, which caused at least MergeTracks to always fail. It also adds output on the problematic sizes, e.g.
```
[DRICH:DRICHMergedTracks] [error] cannot merge input track collections with different sizes 3, 5
[DRICH:DRICHIrtCherenkovParticleID] [error] radiators have differing numbers of TrackSegments 3, 5, 0
```
No.
Yes, should now attempt MergeTracks.
=> fix: avoid undefined unsigned integer behavior in pid size checks

src/global/pid/RichTrack_factory.cc
Resolve #990 
We use the `Acts` surface at max $z$ as the "filter surface" to decide whether or not to proceed with track propagation to the sequence of surfaces in the dRICH radiators (see #735). For aerogel, that surface is slightly before the acrylic filter, and for gas that surface is just before the vessel exit window.
This PR resolves #990 by changing the filter surface to be the surface at max $z$ for gas, for _both_ aerogel and gas track propagation attempts. Prior to this PR, a charged particle with $\eta$ less than the max $\eta$ of aerogel would not produce any propagated track points and no `TrackSegment` object would be written out; however, there would still be a `TrackSegment` for the gas radiator, since the track still passes through gas, thus causing the errors reported …
=> fix(dRICH): use gas radiator backplane for track propagation filter

src/services/geometry/acts/ACTSGeo_service.cc
The https://github.com/eic/epic/pull/494 is not merged at this time. Let's update that one to provide both constants, but going forward use proper meaning one.
=> ACTSGeo_service.cc: rename geom const materials-map -> material-map

src/algorithms/interfaces/WithPodConfig.h, src/extensions/jana/JChainFactoryGeneratorT.h, src/extensions/jana/JChainFactoryT.h, src/extensions/jana/JChainMultifactoryGeneratorT.h, src/extensions/jana/JChainMultifactoryT.h
Instead of defining `NoConfig` in `JChainFactoryT.h`, it makes more sense to define it where the config interfaces are defined.
No.
No.
=> fix: move NoConfig to WithPodConfig.h, as default template argument

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h
In CalorimeterClusterRecoCoG, we use a helper function which can sometimes decide not to return a cluster. `std:: optional` makes that intent clearer.
See discussion in https://github.com/eic/EICrecon/pull/989#discussion_r1330628992. Suggestion is to merge #989, merge this, then put the actual `return {}` for zero weights in a third PR.
No.
No.
=> feat: std::optional in cluster reco CoG

.github/workflows/linux-eic-shell.yml
Instead of unsetting `LD_LIBRARY_PATH`, this now sets `LD_LIBRARY_PATH` to start with the install lib directory. This should address the failures in gcc due to failing `dlopen` of `libDD4hepGaudiPluginMgr.so`, and at the same time allow for ctest with sanitizers in the clang builds.
No.
No.
=> fix(ci): run ctest with prefixed LD_LIBRARY_PATH

src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterHitReco.cc, src/algorithms/calorimetry/CalorimeterHitsMerger.cc
This removes some info logging that should be debug. Also, we don't need to use an explicit fmt::format inside an spdlog logging call.
No.
No.
=> fix: move some info logging to debug; remove unneeded fmt::format

src/algorithms/tracking/TrackSeeding.cc, src/algorithms/tracking/TrackSeeding.h, src/global/tracking/TrackSeeding_factory.cc
This converts the TrackSeeding to podio collections, thereby fixing major memory leaks in all three because of not deleting of pointers in std::vectors.
No.
No.
=> fix: address memory leaks in TrackSeeding

src/algorithms/reco/InclusiveKinematicsDA.cc
This avoids a division by zero when only the scattered electron is in the final state, and no other hadrons are present. In that case `Esum` and `pzsum` are both still exactly zero, and `sigma_h` is still exactly zero as well.
No.
No.
=> fix: avoid division by zero in inclusive kinematics DA method

src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackProjector.h, src/global/tracking/TrackProjector_factory.cc
This converts the TrackProjector to podio collections, thereby fixing major memory leaks in all three because of not deleting of pointers in std::vectors.
No.
No.
=> fix: address memory leaks in TrackProjector

src/algorithms/tracking/IterativeVertexFinder.cc, src/algorithms/tracking/IterativeVertexFinder.h, src/global/tracking/IterativeVertexFinder_factory.cc
This converts the IterativeVertexFinder to podio collections, thereby fixing major memory leaks in all three because of not deleting of pointers in std::vectors.
No.
No.
=> fix: address memory leaks in IterativeVertexFinder

src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc
This fixes femc_studies and lfhcal_studies to use the DD4hep_service instead of just a DD4hep::GetInstance() call.
No.
No.
=> fix: use DD4hep_service in femc_studies and lfhcal_studies

.github/workflows/linux-eic-shell.yml
We have been seeing API rate limit failures (e.g. https://github.com/eic/EICrecon/actions/runs/6239863253/job/17007468298?pr=982#step:2:21) likely due to the spinning up of many jobs at the same time. This effectively spreads the rate to a more managable average instead of peaking in short time, and should (hopefully) resolve these issues.
No.
No.
=> fix(ci): avoid API rate exceeding in get-docs-from-open-prs with max-parallel: 4

src/algorithms/tracking/CKFTracking.cc
I don't have a proof of ODR compliance at this time, but, at least, this issue was recently resolved (likely by #940).
This reverts commit f375494b06e6dfc93d92652b6cee271de526bdfb.
Closes: #340
=> Revert "CKFTracking: disable RTTI type checks until EICrecon conforms to ODR (#551)"

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/IterativeVertexFinder.cc, src/algorithms/tracking/TrackPropagation.cc, src/extensions/spdlog/SpdlogToActs.h
This introduces `SpdlogPrintPolicy` that is used to tell Acts to use the framework logger.
This already works, but probably makes some code obsolete, which I'll evaluate later. 
No.
No.
=> feat: use our spdlog::logger for Acts logging

src/algorithms/reco/MatchClusters.cc, src/algorithms/reco/MatchClusters.h, src/global/reco/MatchClusters_factory.cc
One of the few factories with incomplete porting to GetCollection/SetCollection instead of Get/Set with STL vectors.
=> MatchClusters_factory: switch to use PODIO collections as input

.github/workflows/linux-eic-shell.yml
We have seen some pipelines fail because get-docs-from-main fails to get the correct artifact from main becuase the pipeline it tries to get the artifact from has not completed successfully, e.g. https://github.com/eic/EICrecon/actions/runs/6239677941/job/16939205041 (merge queue) failed because https://github.com/eic/EICrecon/actions/runs/6238746274 (main) failed. We can avoid this merge queue (and PR) failure scenario by requiring that the main artifact is pulled from the lastest successful main workflow.
No.
No.
=> fix(ci): get-docs-from-main for last *success* workflow, not merely completed

.github/workflows/linux-eic-shell.yml, src/services/io/podio/JEventProcessorPODIO.cc
This adds a test job that runs digitization and reconstruction in separate eicrecon steps, with only a raw file artifact as communication between them. This should allow for ensuring #667 is continuously tested.
It is likely that this test won't work until some additional work is completed either here or elsewhere, depending on the scope of that extra work.
The test is limited to the barrel ecal because we currently have to specify all required raw collections as command line arguments, and this seems representative enough. Tracking systems are more collections, and none of the other calorimeter systems have deeply involved experts, so that's how I ended up with barrel ecal.
Quality of life ideas:
- easier way to specify output selection from the default list, e.g. by regex (I would have …
=> feat: add two-stage test job (digitization/reconstruction); write EventHeader by default

docs/howto/add_factory.md, docs/howto/make_plugin.md, docs/tutorial/03-end-user-plugin.md, src/benchmarks/detectors/EcalBarrelScFiCheck/EcalBarrelScFiCheckProcessor.cc, src/benchmarks/detectors/EcalBarrelScFiCheck/EcalBarrelScFiCheckProcessor.h, src/benchmarks/reconstruction/TRACKINGcheck/TRACKINGcheckProcessor.cc, src/benchmarks/reconstruction/TRACKINGcheck/TRACKINGcheckProcessor.h, src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc, src/benchmarks/reconstruction/tof_efficiency/TofEfficiency_processor.cc, src/benchmarks/reconstruction/tof_efficiency/TofEfficiency_processor.h, src/scripts/eicmkplugin.py
PrefetchT relies on compatibility interface that copies PODIO pointer objects into `std::vector<> JFactory::mData` member. We'd like for all of our code to work with PODIO collections directly.
=> src/benchmarks: deprecate JEventProcessorSequential::PrefetchT in favor of PODIO collections

.github/workflows/linux-eic-shell.yml
For debug builds the previous 500MB doesn't fit the entire build so we end up rebuilding all the time. This bumps it up to 1500MB and adds a stats summary at the end which should allow us to assess how many misses we have.
For more efficient lookups in branches off branches, this explicitly adds the PR head and base branch to the lookup list, and changes the ccache key to the head branch for PRs. This means the temporary merge ref "774/merge" won't be used as the key, since that cannot be determined by dependent branches.
No.
No.
=> ci: ccache max size increase and show stats; key name changes

src/algorithms/calorimetry/CalorimeterHitReco.cc, src/algorithms/tracking/ActsGeometryProvider.cc, src/benchmarks/reconstruction/TRACKINGcheck/TRACKINGcheckProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc, src/services/io/podio/JEventProcessorPODIO.cc, src/tests/tracking_test/TrackingTest_processor.cc
This addresses nearly all issues highlighted in #757. Mainly essentially unused variables that the compiler didn't already flag because of conditional assignment patterns.
This doesn't fix the warning about the bypassing of virtual dispatch in the RichGeoDRICH and RichGeoPFRICH constructors. Maybe prefixing the class names makes it clear we don't want dispatch and shuts up the warning, but needs testing. (cc @chchatte92 @c-dilks )
- These are all tests not available in the clang-tidy-14 we're using.
No.
No.
=> fix: address clang-tidy clang-analyzer warnings

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc
In the center of gravity weighting, when all cluster hits have zero weight (logWeightBase is set too low, e.g. ZDC Ecal), then none of the hits are added in the weighted sum and the sum of weights is zero. Normalizing by the sum of weights leads to division by zero on a zero position at that point. Instead of division by zero we just leave the position unset (i.e. still at zero).
No.
No.
=> fix: avoid division by zero by not setting weighted position if sum of weights is zero

.github/labeler.yml
EEMC went in twice - must have been an editing mistake.
=> labeler.yml: fix calorimetry tag for EHCAL

src/services/geometry/richgeo/IrtGeo.cc, src/services/geometry/richgeo/IrtGeo.h, src/services/geometry/richgeo/IrtGeoDRICH.h, src/services/geometry/richgeo/IrtGeoPFRICH.h, src/services/geometry/richgeo/RichGeo_service.cc
This removes the unused (deprecated) IrtGeo interfaces that load their own compact file. This is in particular relevant because RichGeo cleans up the geometry regardless with a `destroyInstance` that is applied on both the DD4hep_service and RichGeo_service geometries. That could potentially cause a race condition when both DD4hep_service and RichGeo_service try to destroy the same geometry instance (it probably is happening already but is caught by the try catch around both instances). This change also allows us to move towards more const correctness in the treatment of DD4hep geometries (i.e. not passing the geometry as a non-const pointer).
No.
No.
=> fix: rm independent geometry reading in RICHGeo

src/global/tracking/TrackSeeding_factory.cc
This fixes a regression introduced in #983 that caused realistic track seeding to fail. Essentially, you cannot just add an object from one podio collection into another podio collection "by reference", i.e. without cloning. You can do that with pointers in std::vector, which was done here before #983. We can achieve the same behavior in podio, but we have to be more intentional about it and define a subset collection.
Of course, podio complains loudly when you try to add an object from one collection into another collection. It emits an exception: `Object already in a collection. Cannot add it to a second collection`. But JANA2 eats that exception and doesn't even print it :angry:
TODO:
No.
Yes, CentralTrackSeedingResults and dependents are restored.
=> fix: use subset collection when collecting hits in TrackSeeding

src/global/tracking/TrackSeeding_factory.cc
This fixes a regression introduced in #983 that caused realistic track seeding to fail. Essentially, you cannot just add an object from one podio collection into another podio collection "by reference", i.e. without cloning. You can do that with pointers in std::vector, which was done here before #983. We can achieve the same behavior in podio, but we have to be more intentional about it and define a subset collection.
Of course, podio complains loudly when you try to add an object from one collection into another collection. It emits an exception: `Object already in a collection. Cannot add it to a second collection`. But JANA2 eats that exception and doesn't even print it :angry:
TODO:
No.
Yes, CentralTrackSeedingResults and dependents are restored.
=> [v1.6] fix: use subset collection when collecting hits in TrackSeeding (backport of #1050)

src/detectors/EHCAL/EHCAL.cc
Fix the division by 0 bug #988, where segment dimensions are 0. Switched to localDistXY. Needs testing and adjustment of the max dist values.
No.
No.
=> fix: use localDistXY in HcalEndcapN

src/algorithms/calorimetry/CalorimeterHitReco.cc, src/detectors/FHCAL/FHCAL.cc
This removes adhoc LFHCAL treatment in CalorimeterHitReco and implements a configurable approach that uses previously implemented layer ID resolution. Instead of `if (m_cfg.readout == "LFHCALHits")`, this now:
- uses the cellID decoder `id_dec` defined on init intsead of a local version,
- doesn't depend on fragile testing `sampFracLayer[0] != 0.` but instead `sampFracLayer.empty()`,
- single place to do the energy reconstruction based on the varying sampFrac,
- single place to do the layer field id decoding.
TODO:
No.
No.
=> fix: remove adhoc LFHCAL treatment in CalorimeterHitReco

src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackPropagation.cc
This reenables the geometryId call to store the surface field of the TrackPoint. It was previously having issues with ASAN.
No.
No.
=> fix: reenable storing geometryId into TrackPoint surface field

cmake/jana_plugin.cmake
Hotfix. Depending on Microsoft.GSL through just a top-level find_package(Microsoft.GSL CONFIG) doesn't work in the eic-shell nightlies, where GSL is in a completely different prefix, e.g. https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/2013019.
No.
No.
=> fix: make sure Microsoft.GSL::GSL is provided to plugins/libraries

src/global/tracking/TrackPropagation_factory.cc
Currently, we have `tracking:CalorimeterTrackPropagator:InputTags` and `tracking:CalorimeterTrackPropagator:OutputTags` as parameter name, but also `CalorimeterTrackPropagator:LogLevel`. This change brings the missing boilerplate that fixes the inconsistency.
=> TrackPropagation_factory: prefix Tag:LogLevel with plugin_name: in parameter name

src/global/tracking/TrackPropagation_factory.cc
The Acts::Surface geometry identifier is intended to store information we are currently passing through two other lists in the TrackPropagation factory. This fills the geometry identifier field with:
- the 'surface' as layer ID,
- the 'detector' as extra ID (which is inteded for subsystem identifiers).
These changes will allow us to get rid of the extra vectors that are passed to the algorithm, which in turn allows us to use the same algorithm for real and constructed surfaces.
No.
No.
=> feat: add system and layer ID to Acts::Surface GeometryIdentifier

src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc
In C++20 / fmt-10.1.0 the format string is constexpr and parsed on compilation time. That means that format string mismatches with the number of arguments are now compilation errors. This fixes (the only) two such cases.
No.
No.
=> fix: correct number of arguments for fmt string in processors

src/global/tracking/TrackPropagation_factory.cc
=> [Backport v1.6] TrackPropagation_factory: HcalEndcapN_* is not defined anymore, use LFHCAL

.github/ubsan.supp, .github/workflows/linux-eic-shell.yml, CMakeLists.txt
This enables ubsan by default in CI, with some more undefined behaviors (float-divide-by-zero, unsigned-integer-overflow, local-bounds). It has two suppressions already, but more will no doubt be needed to limit the output to what we control. There is no way to have an exitcode != 0 when undefined behavior is found, so this depends a bit on people checking the output periodically.
TODO:
=> feat: enable ubsan by default in CI, with print_stacktrace=1 and suppressions

src/global/tracking/TrackPropagation_factory.cc
Fixes: 6bef773f ('feat: add system and layer ID to Acts::Surface GeometryIdentifier')
https://github.com/eic/EICrecon/actions/runs/6478157904/job/17589778133?pr=1069#step:5:605
> Error: [JEventProcessorPODIO] [error] Omitting PODIO collection 'CalorimeterTrackProjections' due to exception: getRefChild: Failed to find child with name: HcalBarrel_ID Map  contains 1759 elements:  ...
=> TrackPropagation_factory: HcalBarrel_ID -> HCalBarrel_ID

src/algorithms/tracking/ActsGeometryProvider.cc, src/algorithms/tracking/ActsGeometryProvider.h
This sets up the Acts::GeometryIdentifierHook to get the DD4hep detector ID on geometry conversion.
Also: makes the material decorator local instead of class member.
No.
No.
=> feat: fill Acts::GeometryIdentfier extra field with DD4hep detector ID

CMakeLists.txt, cmake/jana_plugin.cmake, src/algorithms/pid/IrtCherenkovParticleID.cc, src/algorithms/pid/ParticlesWithPID.cc, src/extensions/spdlog/SpdlogExtensions.h, src/extensions/spdlog/SpdlogToActs.h, src/services/geometry/acts/ACTSGeo_service.cc, src/services/geometry/richgeo/IrtGeo.cc, src/services/geometry/richgeo/RichGeo.h, src/services/geometry/richgeo/RichGeo_service.cc, src/tests/tracking_test/TrackingTest_processor.cc
These are the first commits in #1072 which should be entirely compatible with the current version of Acts v21.1.1, fmt v9, and C++17.
Note: this adds C++20 compatibility in EICrecon code (C++20 adds constexpr support for several fmt functions, which imposes conditions on the inputs we pass to them), but it does not mean that this PR allows one to compile EIC with C++20. The Acts dependency of v21.1.1 only allows C++17 support.
No.
No.
=> fix: support fmt v10 and C++20

src/detectors/BEMC/BEMC.cc
This PR adjusts the Barrel ECal parameters as following:
Dynamic range of SciFi/Pb Calo: 750 MeV ->1500 MeV (both in Digi and Reco)
Pedestal sigma of SciFi/Pb Calo: 1 channel (Digi)
Pedestal of SciFi/Pb Calo: 100 channels (Digi and Reco)
Energy threshold in RecoHits: ~ 5MeV = ~ 5 ADC counts (set through `thresholdValue`)
Pedestal of AstroPix Calo: 14 channels (Digi and Reco) ~ 5 keV noise floor
Pedestal sigma of AstroPix Calo: ~5 channels (Digi) (~3x smaller then noise floor)
Energy threshold in RecoHits: ~ 15keV = ~ 41 ADC counts (set through `thresholdValue`)
It has been also spotted that the SciFi/Pb clustering parameters were not corrected for the sampling fraction, which was causing lots of very small energy clusters being reconstructed. This has been corrected in:
minClusterHitEdep …
=> Adjust reconstruction parameters for Barrel ECal

.github/iwyu.imp, cmake/jana_plugin.cmake, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/TrackParamTruthInit.cc, src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackSeeding.cc, src/algorithms/tracking/TrackSeeding.h, src/extensions/spdlog/SpdlogFormatters.h, src/tests/tracking_test/TrackingTest_processor.cc
This adds some fixes to the IWYU treatment which is now enabled.
- IWYU always_keep on SpdlogFormatters.h ([iwyu fails to detect usage](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYUIsDifficult.md#who-is-responsible-for-dependent-template-types)),
- IWYU keep SpdlogFormatters.h while always_keep not available yet,
- IWYU keep known missing std headers in Acts,
- IWYU import fixes to avoid duplicate symbols due to inclusion of ipp AND hpp files,
- IRT include directories fix to avoid short-form include suggestions.
TODO:
No.
No.
=> fix: IWYU pragmas and iwyu.imp fixes

.github/iwyu.imp, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterIslandCluster.cc, src/algorithms/calorimetry/CalorimeterIslandCluster.h, src/algorithms/calorimetry/EnergyPositionClusterMerger.h, src/algorithms/calorimetry/ImagingClusterReco.h, src/algorithms/calorimetry/ImagingTopoCluster.h, src/algorithms/calorimetry/TruthEnergyPositionClusterMerger.h, src/algorithms/fardetectors/MatrixTransferStatic.cc, src/algorithms/reco/ElectronReconstruction.cc, src/algorithms/reco/InclusiveKinematicsTruth.cc, src/algorithms/reco/MatchClusters.cc, src/algorithms/tracking/ActsGeometryProvider.cc, src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackPropagation.cc
This includes two commits (one full, one partial) from #1072 that can be applied even with Acts 21.1.1 and would simplify #1072. Main impact:
- use edm4hep vector_utils,
- avoid unnecessary MaterialWiper.
No.
No.
=> fix: use edm4hep vector_utils instead of edm4eic; remove MaterialWiper (prep for Acts v26)

.github/workflows/linux-eic-shell.yml
The brycecanyon test now fails, because the simulation is gone.
=> linux-eic-shell.yml: remove last reference to brycecanyon

.github/iwyu.imp, src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterHitsMerger.cc, src/algorithms/calorimetry/CalorimeterIslandCluster.cc, src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/fardetectors/MatrixTransferStatic.cc, src/algorithms/pid/ParticlesWithPID.cc, src/algorithms/tracking/TrackParamTruthInit.cc, src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackPropagation.cc, src/algorithms/tracking/TrackSeeding.cc, src/detectors/DIRC/DIRC.cc, src/services/geometry/richgeo/ActsGeo.cc, src/services/geometry/richgeo/IrtGeoPFRICH.cc, src/services/geometry/richgeo/ReadoutGeo.cc
Those are not portable across versions and to different libraries.
Avoids build errors like:
```
src/algorithms/calorimetry/CalorimeterHitDigi.cc:21:10: fatal error: bits/utility.h: No such file or directory
21 | #include <bits/utility.h>
|          ^~~~~~~~~~~~~~~~
compilation terminated.
```
=> treewide: avoid including some internal headers from libstdc++

src/tests/algorithms_test/calorimetry_CalorimeterIslandCluster.cc
Distance-based adjacency test is not the only code path. Using adjacencyMatrix is preferred, but was not tested until now. This implements a mock DD4hep detector that just provides the necessary readout encoder/decoder.
=> calorimetry_CalorimeterIslandCluster: add test case for adjacencyMatrix code path

.github/workflows/linux-eic-shell.yml
It looks like workflows on main continue to be cancelled: https://github.com/eic/EICrecon/actions/runs/6711622872/job/18239385242
This is yet another attempt at fixing this in the series of ... #968 #998.
=> linux-eic-shell.yml: fix cancel-in-progress

src/detectors/BEMC/BEMC.cc, src/detectors/BHCAL/BHCAL.cc
Updated BHCAL thresholds and digitization parameters from the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g).
- This uses a cut on accumulated energy. Instead, you could set the energy cut to 0 and use `.thresholdValue=328` instead (or `.thresholdFactor = 164`). The difference between the two is that in the latter case, an ADC fluctuation can bring the result below/above threshold.
- I believe the 5 MeV threshold corresponds to a 150 MeV real deposition, accounting for sampling fraction. Just double-checking that that's correct.
No.
Yes.
=> Bhcal threshold

src/detectors/EEMC/EEMC.cc
Updated EEMC thresholds and digitization parameters from the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g).
- This uses a cut on accumulated energy.
- Previous adc cut settings would correspond to a cut of 
ped = 20; thresholdADC = 4.0*1+3 
https://github.com/eic/EICrecon/blob/main/src/algorithms/calorimetry/CalorimeterHitReco.cc#L47
Note that at most one of `.thresholdFactor`  and `.thresholdValue` should be non-zero/
Converting back, I get the lowest energy as
27 gets reconstructed as
(27 - 20) / 16384 * 20000 MeV / 0.998 = 8.56 MeV > 5 MeV
I therefore turned off zero suppression for this campaign. We can make the ADC cut more consistent, or replace the energy cut with it, …
=> Updated EEMC energy threshold and ADC parameters

src/detectors/EHCAL/EHCAL.cc
Updated backward HCal ADC params from the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g).
- NO thresdhold is applied.
- Previous adc cut settings are inconsistent, at most one of `.thresholdFactor`  and `.thresholdValue` should be non-zero. I therefore turned off zero suppression for this campaign. 
No.
Yes.
=> Updated backward HCAL ADC parameters, removed threshold

src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/detectors/FEMC/FEMC.cc
Updated FEMC threshold and digitization parameters to match the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g)
Also, the formula in https://github.com/eic/EICrecon/blob/main/src/algorithms/calorimetry/CalorimeterHitDigi.cc#L172 was wrong. It is corrected and eRes here was adapted for that change.
These parameters are applied in three stages:
1. Apply energy threshold to cumulated Geant4 hits. 
Relevant snippet:
https://github.com/eic/EICrecon/blob/main/src/algorithms/calorimetry/CalorimeterHitDigi.cc#L164-L170
--> Not used here, instead we use an ADC cut
2. Smear energy, convert to ADC
Relevant snippet:
https://github.com/eic/EICrecon/blob/main/src/algorithms/calorimetry/Calori …
=> Updated FEMC threshold and digitization parameters

src/detectors/B0ECAL/B0ECAL.cc
Updated B0ECAL threshold from the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g).
- This uses a cut on accumulated energy.
- Previous adc cut settings are inconsistent, at most one of `.thresholdFactor`  and `.thresholdValue` should be non-zero. I therefore turned off zero suppression for this campaign. We can make the ADC cut more consistent, or replace the energy cut with it, in the future.
No.
Yes.
=> B0 Ecal threshold

src/detectors/FEMC/FEMC.cc, src/detectors/FHCAL/FHCAL.cc
Updated backward Insert ADC parameters from the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g).
- Threshold cut is applied on the ADC level.
0.25 MeV particle:
adc = 50 + 0.25 / 200 * 32768 = 91
No.
Yes.
=> Updated ADC parameters and threshold for HCal (and ECal) inserts

src/detectors/FHCAL/FHCAL.cc
Updated LFHCAL ADC params from the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g).
Threshold on the ADC level:
0.3 MeV deposition --> adc = 50 + 0.3 / 1000 * 65536 == 70 --> thresholdValue = 20
No.
Yes.
=> Updated LFHCAL ADC parameters and threshold

src/algorithms/calorimetry/CalorimeterTruthClustering.cc, src/algorithms/calorimetry/ImagingClusterReco.h, src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/pid/ConvertParticleID.h, src/algorithms/pid/MergeParticleID.cc, src/algorithms/pid/ParticlesWithPID.cc
This adds forward compatibility with podio v0.17.1. See https://github.com/AIDASoft/podio/pull/493
No.
No. The modified algorithms are not relying on the most significant bits in the previous ObjectID uint_t that encode the collectionID.
=> fix: mv id() to getObjectID().index because id() returns ObjectID, not uint_t, in podio v0.17.1

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoGConfig.h, src/detectors/B0ECAL/B0ECAL.cc, src/detectors/BEMC/BEMC.cc, src/detectors/BHCAL/BHCAL.cc, src/detectors/EEMC/EEMC.cc, src/detectors/EHCAL/EHCAL.cc, src/detectors/FEMC/FEMC.cc, src/detectors/FHCAL/FHCAL.cc, src/detectors/LUMISPECCAL/LUMISPECCAL.cc, src/detectors/ZDC/ZDC.cc, src/factories/calorimetry/CalorimeterClusterRecoCoG_factoryT.h
The options depthCorrection and moduleDimZName are entirely unused, it appears.
No.
No.
=> fix: rm unused ClusterRecoCoG options

CMakeLists.txt, cmake/jana_plugin.cmake, src/algorithms/calorimetry/CMakeLists.txt, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h, src/factories/calorimetry/CalorimeterClusterRecoCoG_factoryT.h
This adds support for [algorithms](https://github.com/eic/algorithms) in EICrecon. It depends on getting the updated algorithms@main into eic-shell, to get the addition of `find_package(algorithms)` support. This does not add any 'real' algorithms support but demonstrates the accessibility of the interface in CalorimeterClusterRecoCoG.
No.
No.
=> feat: depend on algorithms; demo interface in CaloClusterRecoCoG

src/algorithms/calorimetry/CalorimeterTruthClustering.cc, src/algorithms/calorimetry/ImagingClusterReco.h, src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/pid/ConvertParticleID.h, src/algorithms/pid/MergeParticleID.cc, src/algorithms/pid/ParticlesWithPID.cc
=> [Backport v1.7] fix: mv id() to getObjectID().index because id() returns ObjectID, not uint_t, in podio v0.17.1

.github/workflows/linux-eic-shell.yml
The way GitHub actions upload-artifact uploads each file individually, and stores them in a compressed archive on the server. This means that there are 1500+ files uploaded, each counting as an API call. It's also slow due to the way the protocols work. Compressing on the node, then uploading one file could be net faster.
No.
No.
=> fix(ci): upload build/ as tar.gz for speedup

src/algorithms/tracking/DD4hepBField.cc
Remove hard-coded unit conversion from DD4hepBfield. Cherry-picked from #1072.
No.
No.
=> fix: convert DD4hepBfield position units without hardcoding

.github/workflows/linux-eic-shell.yml
This publishes the capybara diffs to the EICrecon ghpages, e.g. https://eicrecon.epic-eic.org/pr/1072/capybara/rec_dis_10x100_minQ2=1000_craterlake/#CalorimeterTrackProjections_0 (will be inactive as soon as a pipeline that doesn't support this overwrites the active ghpages deployment).
Cherry-picked from 1072.
No.
No.
=> feat: write capybara diff dashboards for PRs to ghpages

CMakeLists.txt
This updates the default C++ standard from 17 to 20, which is now required by Acts. As of now, there do not appear to be any Acts headers that are using C++20 concepts (pun intended) but that should be considered a coincidence. After this PR, C++20 constructs in EICrecon are officially allowed. 
I thought about restricting it to just C++20, not allowing anything higher, but that prevents us from implementing C++23 support through the regular development process.
No.
No.
=> fix: update CMAKE_CXX_STANDARD default to 20, now required by Acts

src/tests/algorithms_test/CMakeLists.txt
This fixes an issue in the linking of algorithms_test which popped up today (and likely was always there...). Until https://github.com/JeffersonLab/JANA2/pull/255 is included, we install a libJANA.so with undefined references to podio because it doesn't include it in the NEEDED section. By passing `--no-as-needed` we don't strip the podio calls from the algorithms_test executables where they are unused.
No.
No.
=> fix: link tests with --no-as-needed due to JANA #255

.github/workflows/linux-eic-shell.yml, docs/_sidebar.md
This aims to present the capybara results in a more accessible way, by integrating them in the browsable structure at eicrecon.epic-eic.org, and by printing them as a step summary in the github actions summary interface.
No.
No.
=> feat(ci): produce PR and capybara summary; print to step summary

CMakeLists.txt, src/tests/algorithms_test/CMakeLists.txt
=> algorithms_test/CMakeLists.txt: alternative option detection mechanism

src/global/tracking/tracking.cc
Updates track collections that are passed into algorithms downstream of CKF to make them consistent with the trajectory collections that are provided -- both are now the truth seeded CKF output.
No. None.
No.
=> Fix: update collections passed into factories downstream of CKF in tracking.cc

.github/workflows/linux-eic-shell.yml
Instead of clobbering the summaries, we can just run clang only. There is not a lot of value in running both gcc and clang. Would reduce our CI pipelines too.
No.
No.
=> feat: only run clang eicrecon-{dis,gun}, no more gcc

src/algorithms/tracking/TrackerMeasurementFromHits.cc, src/algorithms/tracking/TrackerMeasurementFromHits.h, src/global/tracking/TrackerMeasurementFromHits_factory.cc
Instead of passing a std::vector<T*> to the TrackerMeasurementFromHits algorithm, we should pass a TrackerHitCollection. This PR modifies the algorithm and factory. The factory accepts an array of input collections in a similar way as the TrackerHitCollector does, but that functionality is not currently used (since we use the TrackerHitCollector). Nevertheless, it means we also need to use a subset collection here.
No.
No.
=> fix: pass TrackerHitCollection to TrackerMeasurement, not std::vector<T*>

.github/workflows/linux-eic-shell.yml
Similar to #1112, this PR installs EICrecon into a separate CMAKE_INSTALL_PREFIX (to ensure the rest of the pipeline only relies on explicitly installed targets, not things that are part of the repository but not installed). It uploads a single (uncompressed, see #1124) tar archive with the install directory, ensuring that file permissions are maintained and that we don't hit our API limits.
No.
No.
=> fix(ci): install into prefix and upload as tar artifact

.github/workflows/linux-eic-shell.yml
After finding in #1124 that compression does matter, we might as well use the best modern compression currently available to evaluate if it does any better than gz. Since it does (comment below) we apply this to both install and build artifacts.
No.
No.
=> fix(ci): compress install and build artifact with zstd

.github/workflows/linux-eic-shell.yml
This should address the clang-tidy issues on main (and likely soon in a PR). clang-tidy runs without errors in my local eic-shell test setup now.
I considered adding the logic to allow the builds to be against a variable that encodes the C++ standard, but that quickly ran out of hand (see discussion on doing this for compilers). With one standard every three years, I think it's reasonable to deal with this as we go. We only support C++20 now anyway.
No.
No.
=> fix(ci): run clang-tidy with extra-args -std=c++20

CMakeLists.txt
Maybe this is a better approach too: set by default to 17, allow user to set higher, check that C++std agrees with what ROOT and Acts are assuming.
Question: should we automatically upgrade default 17 to 20 if we find that Acts or ROOT requires it?
No.
No.
=> fix: set C++std to 20, allow higher; agree with Acts and ROOT

src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterHitDigi.h, src/factories/calorimetry/CalorimeterHitDigi_factoryT.h, src/tests/algorithms_test/calorimetry_CalorimeterHitDigi.cc
In the ongoing attempts at making the algorithms self-descriptive and conformant to the algorithms:: specification, this converts another one: CalorimeterHitDigi. This wasn't as straightforward as CalorimeterClusterRecoCoG because of the RandomSvc. No attempt is made to connect a JANA2 random service (in part because I don't think JANA2 has one; @nathanwbrei is that still true?). Due to the change of random generator, this is not expected to agree bit-for-bit with what is in main.
No.
No.
=> feat: use algorithms:: interface CalorimeterHitDigi (incl RandomSvc)

src/algorithms/pid/MergeParticleID.cc
This minor fix addresses a warning, e.g. at https://github.com/eic/EICrecon/actions/runs/7024158171/job/19112268764#step:7:295. Instead of forcing unsigned int, this uses the decltype of podio::ObjectID::index.
No.
No.
=> fix: avoid narrowing warning with decltype in MergeParticleID

.github/workflows/linux-eic-shell.yml
IWYU as previously installed was exposing non-standard commands as defined by the Debian package. Since we moved to the spack package, we have to revert back to the original command names.
No.
No.
=> fix: more generic iwyu command line interface

.github/tsan.supp, CMakeLists.txt, cmake/jana_plugin.cmake
This installs the {asan,lsan,tsan,ubsan}.supp files into `share/EICrecon` when the installation has support for the respective sanitizers. At this point I'm leaving the *.supp files in .github/ since we don't have an equivalent other directory, and with the current practice of in-tree installations we don't really want to use share/ itself.
It also applies a few minor CMake cleanups:
- use `message(VERBOSE)` instead of an EICRECON flag; one can use `cmake --log-level VERBOSE` to print this,
- include GNUInstallDirs for consistent directory support (not yet propagated to plugins)
- use install DIRECTORY with FILE_PATTERN for cmake/*.cmake files instead of a GLOB
No.
No.
=> fix: install {asan,lsan,tsan,ubsan}.supp with CMake; other CMake cleanup

.github/workflows/linux-eic-shell.yml
We spend several minutes just waiting for the build artifacts to get uploaded, and then we don't use them... This only uploads the build directory artifact that is used by the clang-tidy-iwyu job (which is, incidentally, associated with the fasted compilation job, the smallest build directory, and fastest upload). This will speed up when the build matrix completes, and when the next set of jobs can start running.
No.
No.
=> fix(ci): don't upload unused build directory artifacts

src/extensions/jana/JOmniFactory.h, src/tests/omnifactory_test/JOmniFactoryTests.cc
Small fix to be able to use `Output` in JOmniFactory.
No.
No.
=> fix: Output uses collection_name; Input uses GetCollection in JOmniFactory.h

src/scripts/eicrecon-this.sh.in
Small fix to `pushd` and `popd` around `source thisroot.sh`
No.
It shouldn't.
=> eic-shell requires "cd where/root/is" before calling ". bin/thisroot.sh"

src/algorithms/reco/MatchClusters.cc, src/algorithms/reco/MatchClusters.h, src/global/reco/MatchClusters_factory.cc, src/global/reco/MatchClusters_factory.h, src/global/reco/reco.cc
MatchClusters is trying to be clever in the factory, while at the same time assuming hardcoded collection names. This changes the MatchClusters factory to require MCParticles, ReconstructedChargedParticles, and ReconstructedChargedParticleAssociations as first collections, then a sequence of XClusters, XClusterAssociations (instead of building the Associations listing itself). This makes the reco.cc more complete and less dependent on MatchCluster_factory magic.
This also modifies MatchClusters the algorithm to return tuple<unique_ptr<Collection> x 2>.
No.
No.
=> feat: use unique_ptr in MatchClusters; require all collections in reco.cc

src/algorithms/calorimetry/CalorimeterHitsMerger.cc, src/algorithms/calorimetry/CalorimeterHitsMerger.h, src/factories/calorimetry/CalorimeterHitsMerger_factory.h
This adopts the algorithms:: interface in CalorimeterHitsMerger. Note: `input[ix]` becomes `(*in_hits)[ix]` because `input` is now a tuple of size 1, and it contains a smart pointer to a collection instead of a collection by reference.
No.
No.
=> fix: adopt algorithms:: interface in CalorimeterHitsMerger

src/algorithms/calorimetry/CalorimeterHitReco.cc, src/algorithms/calorimetry/CalorimeterHitReco.h, src/factories/calorimetry/CalorimeterHitReco_factory.h
This adopts the `algorithms::` interface in CalorimeterHitReco. Notable changes needed, since `process()` is now `const`:
- NcellIDerrors and warned_unsupported_segmentation are now mutable,
- the local DetElement copy is now handled slightly differently to allow for either a copy obtained during process, or one obtained during init.
No.
No.
=> fix: adopt algorithms:: interface in CalorimeterHitReco

.github/iwyu.imp, src/algorithms/tracking/ActsGeometryProvider.cc
In https://github.com/acts-project/acts/pull/2617 the detail header will be removed.
No.
No.
=> fix: rm Acts detail header for stable interface

cmake/jana_plugin.cmake, src/algorithms/tracking/IterativeVertexFinder.cc
~~Thanks to C++20 we can now do templated lambdas which don't require syntactic validity of all code paths. That makes forward/backward compatibility across Acts versions easier with constexpr lambdas.~~
Ifdefs on defined Acts major versions allow us to bypass code blocks that are not compilable or parsable under different versions of Acts.
Ref: https://github.com/acts-project/acts/pull/2649
No.
No.
=> fix: forward compatibility with Acts-v31

README.md
It's handy to have the instruction easily available. This is a copy of the corresponding section from eic/epic.
=> README.md: add instruction on compilation

.github/iwyu.imp, cmake/jana_plugin.cmake, src/algorithms/tracking/ActsGeometryProvider.cc, src/algorithms/tracking/IterativeVertexFinder.cc
This backports 4023c3f139427766a304aeb43cb2ffc971571163 and 03b1049a4e7a6b7ff4d22998d815e73d78d329bc into v1.9 in prep for a v1.9.1 release. Acts v31 isn't expected to land officially until EICrecon v1.10 and container 24.02, but we need a stable version that compiles with the newer container for testing of the container builds.
No.
No.
=> fix: backport into v1.9 of Acts v31 support 

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h, src/factories/calorimetry/CalorimeterClusterRecoCoG_factory.h
This removes the unused `GeoSvc` from `CalorimeterClusterRecoCoG`.
=> fix: rm unused GeoSvc from CalorimeterClusterRecoCoG

CMakeLists.txt, README.md
Instead of leaving CMAKE_BUILD_TYPE unset, this sets the default to `Release`, unless `.git` exists and it sets `Debug`. This avoids ending up with `noconfig` on target exports (or unoptimized compiles).
No.
Yes, developers with `.git` will likely switch from unspecified defaults to actual `Debug` configuration.
=> feat: set default CMAKE_BUILD_TYPE in CMakeLists.txt

src/services/geometry/dd4hep/DD4hep_service.cc, src/services/geometry/dd4hep/DD4hep_service.h
Instead of using the JANA logger macros, this switches DD4hep_service over to using Log_service for logging. It also has the TGeoManager use a verbose level defined by the dd4hep::PrintLevel.
Default output is now:
```
[dd4hep] [info] Loading DD4hep geometry from 1 files
[dd4hep] [info]   - loading geometry file:  '/opt/detector/epic-nightly/share/epic/epic_craterlake.xml' (patience ....)
[dd4hep] [info] Geometry successfully loaded.
```
No.
Not really. Less output from TGeoManager by default; recover previous output with `-Pdd4hep:print_level=INFO`.
=> fix: use Log_service inside DD4hep_service

.github/workflows/linux-eic-shell.yml
Instead of installing epic-capybara for every pipeline, this only installs when `capybara` is not already in the path.
No.
No.
=> feat: install capybara only when not available

src/algorithms/reco/ElectronReconstruction.cc, src/algorithms/reco/ElectronReconstruction.h, src/algorithms/reco/ElectronReconstructionConfig.h, src/extensions/jana/JOmniFactory.h, src/global/reco/ReconstructedElectrons_factory.h, src/global/reco/reco.cc, src/tests/omnifactory_test/JOmniFactoryTests.cc
Adds support for variadic PODIO inputs inside JOmniFactories. This lets us fetch an arbitrary number of collections specified simply via input tags. Includes a migrated ReconstructedElectrons factory. 
It also enables us to migrate MatchClusters, MergeTrack, and TrackerHitCollector in the near future.
No
No
=> Variadic OmniFactories

src/algorithms/tracking/TrackSeeding.cc
Essentially changes this line
```if(dphi > M_PI) dphi = 2.*M_PI - dphi;```
to 
```if(dphi > M_PI) dphi = dphi - 2.*M_PI;```
This will affect a seed where, for example, the first hit is at ```phi = - 179.5 degrees``` and the second hit is at ```phi = + 179.5 degrees```. In the prior version, ```dphi = 360 - 359 = +1 degrees```, returning a positive charge. Now it will correctly return a negative charge.
This has a very small overall effect. For 10k single muons generated from ```(x,y,z) = (0,0,0)``` with eta [-4,4] and p = [0.5,20] GeV/c, we have ```0.86%``` seed charge misidentification now, compared to ```0.87%``` previously.
Thanks to @veprbl for pointing this out.
No
Yes, change affects seed charge calculation for a small number of seeds
=> Fix: Small change to phi difference calculation in seed charge determination

src/algorithms/tracking/TrackParamTruthInit.cc, src/algorithms/tracking/TrackParamTruthInitConfig.h
Units are set (via command line or config files) assuming a certain unit system. We have chosen DD4hep for this in all other cases (in part because it comes with a parser). Having one algorithm use Acts units is potentially confusing since distances may be passed in the wrong units.
This PR converts TrackParamTruthInit to store the config variables in DD4hep units, and modifies the algorithm itself to interpret the config in DD4hep units. No changes are expected to the output.
No values are specified in the factory or in the plugin, so this is the only change that should be needed.
No.
No.
=> fix: convert TrackParamTruthInit to use DD4hep units

.github/workflows/linux-eic-shell.yml
After some initial succesful running of eicrecon, we pass on to building a full eicweb container and subsequent benchmarks.
No.
No. Won't make this test required (for now) so shouldn't slow down the pipelines until completion.
=> feat(ci): trigger eicweb container build for benchmarks

src/algorithms/digi/PhotoMultiplierHitDigi.cc, src/algorithms/digi/PhotoMultiplierHitDigi.h, src/global/digi/PhotoMultiplierHitDigi_factory.h
This PR converts the PhotoMultiplierHitDigi algorithm to the algorithms:: interface.
No.
No.
=> feat: convert PhotoMultiplierHitDigi to use algorithms:: interface

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc
=> CalorimeterClusterRecoCoG: copy hits references from ProtoCluster

src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc
Fixes regression introduced by https://github.com/eic/EICrecon/pull/1224
It would appear those loops were never utilized before. There are simular loops for the inlined "kMA" clustering code.
=> femc_studies,lfhcal_studies: remove broken code

src/services/geometry/dd4hep/DD4hep_service.cc
This PR removes some remaining references to the environment variable DETECTOR, which is not used and should not be referred to.
No.
No.
=> fix: rm references to $DETECTOR in DD4hep_service.cc

src/algorithms/digi/SiliconTrackerDigi.cc, src/algorithms/digi/SiliconTrackerDigi.h, src/factories/digi/SiliconTrackerDigi_factory.h
This converts SiliconTrackerDigi to use the algorithms:: interface.
TODO:
No.
No.
=> feat: convert SiliconTrackerDigi to use algorithms:: interface

src/algorithms/pid/MergeTracks.cc, src/algorithms/pid/MergeTracks.h, src/global/pid/MergeTrack_factory.cc, src/global/pid/MergeTrack_factory.h, src/tests/algorithms_test/pid_MergeTracks.cc
This PR converts the MergeTracks algorithm in PID to use the algorithms:: interface. I was pleasantly surprised that algorithms:: already supports vectors of input and output (<- FYI @nathanwbrei).
No.
No.
=> feat: convert MergeTracks to use algorithms:: interface (not yet omni)

.github/workflows/linux-eic-shell.yml
This prevents comments from being posted before the links are alive.
=> linux-eic-shell.yml: delay posting capybara comment until pages are deployed

docs/howto/add_factory.md, docs/tutorial/04-factory.md
I don't think there is any plans to update this documentation, but we could at least make a link to the updated material.
=> docs/tutorial/04-factory.md: link to updated tutorial

src/global/pid/pid.cc
There were two factories with the same name in pid.cc: one for the truth-seeded reconstruction path, and one for the realistic-seeding-based reconstruction path. This PR makes sure they are named differently.
No.
No.
=> fix: avoid duplicate factory names in pid.cc

src/algorithms/tracking/TrackProjector.cc
While going through this class for other reasons, I noticed the arbitrary direction `{0,0,0}` when we can provide the actual direction. I don't expect any difference due to this, but as we have seen there can be upstream changes that make it such that arbitrarily chosen directions suddenly start to matter. If the interface specifies a direction, then Acts is free to start expecting the direction to make sense and to start producing results that depend on it.
No.
No.
=> fix: use track direction in localToGlobal in TrackProjector

src/algorithms/pid/ParticlesWithPID.cc, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/TrackParamTruthInit.cc, src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackSeeding.cc
This adds forward support for edm4eic version 5, which includes the changes in https://github.com/eic/EDM4eic/pull/58.
No.
Yes, some fields not written as before since CKFTracking does not yet write edm4eic::Track collection.
=> feat: forward support edm4eic version 5

cmake/jana_plugin.cmake
In #1203 this was included as an 'also', but we do want this in main. I am not entirely sure why this works in eic-shell right now, since even there algorithms exports the namespaced target... but it doesn't work without this outside eic-shell and should use the namespace that upstream specifies.
No
No.
=> fix: namespace needed on link target algorithms::algocore

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/TrackerMeasurementFromHits.cc
Acts uses square matrices for covarianc matrices that are **not** required to be symmetric. This means that we should set **both** off-diagonal elements explicitly (but we can just read one of them). The EDM4eic data model does assume symmetry, so only upper diagonal is stored.
This PR ensures that we explicitly write off-diagonal covariance matrix elements everywhere, even if they are just written as zeros. This makes it clearer that we are not implicitly assuming symmetry.
No.
No.
=> fix: explicitly set off-diagonal elements in the covariance matrices

src/detectors/EHCAL/EHCAL.cc
Implemented 100 ns integration time
Eth=0.25 MIP=0.1875 MeV for backward HCal
Fixed hit merging and plugged into clustering
=> Fix hit merging and add thresholds for backward HCal

.github/dependabot.yml, .github/workflows/labeler.yml, .github/workflows/linux-eic-shell.yml
We're starting to see a lot of warnings in CI (e.g. https://github.com/eic/EICrecon/actions/runs/7674122445) due to node.js v16 deprecation, ref: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
This PR updates the versions in the CI workflow, and also enabled dependabot to do this automatically from now on.
TODO:
No.
No.
=> fix: avoid CI warnings by upgrading actions; add dependabot

.github/workflows/linux-eic-shell.yml
[Should benefit us since we have 4 cores available](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
=> linux-eic-shell.yml: use all available cores for cmake build

src/global/tracking/TrackPropagation_factory.cc, src/global/tracking/TrackPropagation_factory.h
Potentially fixes the track projection strange behavior and mismatch between detector/surface ID and eta range, etc.
NO
NO
=> TrackPropagation_factory: resolve an indexing bug by using ACTS surface ID fields

src/algorithms/calorimetry/CalorimeterClusterRecoCoGConfig.h
It's not 50 GeV. This is for documentation purposes.
=> Update CalorimeterClusterRecoCoGConfig: specify units for default value logWeightBase_Eref

.github/workflows/linux-eic-shell.yml
Merge queues use a temporary branch that is not available for checkout. This PR disables the trigger of the eic_container build for merge queues because they fail (e.g. https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/2329046).
No.
No.
=> fix(ci): don't trigger eic_container in merge queue

src/benchmarks/detectors/EcalBarrelScFiCheck/EcalBarrelScFiCheckProcessor.cc, src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc, src/benchmarks/reconstruction/tof_efficiency/TofEfficiency_processor.cc, src/global/pid/IrtCherenkovParticleID_factory.cc, src/global/pid/MergeCherenkovParticleID_factory.cc, src/global/pid/MergeTrack_factory.cc, src/global/reco/MatchClusters_factory.cc, src/scripts/eicmkplugin.py
Supersedes https://github.com/eic/EICrecon/pull/936.
Back in the early JMultifactory days, we were not able to use GetCollection<T>, so we ended up with many static_cast<const T::collection_t*>(GetCollectionBase()) workarounds. Nowadays, we can and already do use the GetCollection<T> syntax.
No.
No.
=> fix: replace GetCollectionBase with GetCollection<T> (2nd attempt)

src/algorithms/tracking/TrackSeeding.cc, src/algorithms/tracking/TrackSeeding.h
Closes: #1271
Closes: #1272
It calculates the charge more correctly. 
Before the change
```
events->Scan("CentralTrackSeedingResults.phi:CentralTrackSeedingResults.phi-atan2(MCParticles.momentum.y[0],MCParticles.momentum.x[0]):CentralTrackSeedingResults.charge","abs(CentralTrackSeedingResults.phi-atan2(MCParticles.momentum.y[0],MCParticles.momentum.x[0]))>0.5")
***********************************************************
*    Row   * Instance * CentralTr * CentralTr * CentralTr *
***********************************************************
*      457 *        0 * 3.1368908 * 6.2784049 *        -1 *
*      457 *        2 * 3.1409514 * 6.2824654 *        -1 *
*     1051 *        0 * 3.1248598 *  6.197864 *        -1 *
*     1541 *        2 * -2.652385 * -3.144119 *        -1 *
*     1593 * …
```
=> improvement in charge calculation in trackseeding

.github/workflows/linux-eic-shell.yml
Each PR (and main) publishes the capybara artifacts for all open PRs:
- Within the PR's own workflow run itself, it pulls the capybara artifacts regardless of completion of the workflow (since the workflow is still running), and it posts this as a comment.
- Within another PR's (or main's) workflow run, it pulls the capybara artifacts with dawidd6/download-artifact-action, and it does this with the default of `workflow_conclusion: success`.
This strategy results in a comment being posted on the PR with working capybara artifacts links, but the workflow fails (e.g. clang-tidy-iwyu or later API requests exceeded), and the workflow is marked as failed (e.g. https://github.com/eic/EICrecon/pull/1285/commits has two failing workflows right now). Since it is failed, the capybara artifacts are …
=> fix(ci): accept failing workflow runs as source of capybara reference

src/detectors/BVTX/BVTX.cc, src/detectors/ECTRK/ECTRK.cc, src/services/io/podio/JEventProcessorPODIO.cc
I updated the Si raw hits name. Also added all tracker raw hits (Si, MPGD, TOF, B0) to the default podio output collection.
- [x ] New feature (issue #__)
- [x ] Changes have been communicated to collaborators @mdiefent 
N/A. Some raw hits name changed. but since it's never used anywhere other than the digitization it should not be an issue.
N/A
=> add raw tracker hits to output collection

.github/workflows/linux-eic-shell.yml
Specifying the commit hash with dawidd6/action-download-artifact avoids an API request by bypassing https://github.com/dawidd6/action-download-artifact/blob/master/main.js#L87. This PR modifies the list-open-prs job to pass the head.sha as commit to the get-docs-from-open-prs matrix.
No.
No.
=> fix(ci): store pull_request.head.sha for later use

.github/workflows/linux-eic-shell.yml
In #1299 we started accepting all workflows, not just the ones that succeeded. This had as effect that incomplete workflows (where there is no artifact yet) are used, leading to failures.
This PR requires that pipelines have completed.
No.
No.
=> fix(ci): accept only completed workflow runs as source of capybara reference

.github/workflows/linux-eic-shell.yml
Sometimes useful to know if a post is stale or has updated info.
No.
No.
=> feat(ci): add last updated timestamp to capybara post

src/algorithms/reco/InclusiveKinematicsElectron.cc
In the W² = M² + 2pq - Q² formula in inclusive kinematics (electron) the M² was missing. This PR assume it is always scattering off protons.
No.
No.
=> fix: W² = M² + 2pq - Q² in inclusive kinematics (electron)

src/algorithms/fardetectors/MatrixTransferStatic.cc, src/algorithms/fardetectors/MatrixTransferStatic.h, src/algorithms/fardetectors/MatrixTransferStaticConfig.h, src/detectors/FOFFMTRK/FOFFMTRK.cc, src/detectors/RPOTS/RPOTS.cc, src/factories/fardetectors/MatrixTransferStatic_factory.h, src/services/io/podio/JEventProcessorPODIO.cc
Adds functionality to obtain beam energy information, at least for a few cases (protons, and one case, for now, for deuterons) to select correct matrix for RP reconstruction.
Also added correct collections to PODIO output in eicrecon to use digitized hits and store "rec" hits.
Not breaking changes, adds proper functionality so the algorithm can actually handle different beam energies.
Yes, see above.
=> Add digi and fix reco for roman pots

src/algorithms/reco/ElectronReconstruction.cc
The previously introduced ElectronReconstruction factory outputs a ReconstructedParticleCollection of electron candidates via the E/p ratio. However, the matched cluster (used for the E/p calculation) was not associated. This calls repo_electron.addToClusters(...) to keep the association for use in later electron finder factories that use the electron candidates.
Note:
I also considered adding the energy (from the cluster) to the reco Electron via:
```
reco_electron.setEnergy(cluster.getEnergy());
```
but I am not sure if this is a good idea...
NO
NO
=> Associate matched calo cluster with reco electrons

.github/workflows/linux-eic-shell.yml
This PR removes the VERSION variable from the trigger of the container build.
We specified the VERSION so the published container is identifiable. This also means that every trigger with a VERSION ends up getting published to docker hub, ghcr.io and the eicweb internal registry. This was fine for an occasional trigger, but it's overwhelming the registry storage (in particular eicweb) when we trigger a container for every commit on every branch, even with automatic cleanup rules.
So, with this PR we stop deploying the containers to tags with name eicrecon-$SHA.
No.
No.
=> fix: don't trigger container build with VERSION

.github/workflows/linux-eic-shell.yml
Because `vm.mmap_rnd_bits-28` matches our pattern for protected stable release branches (`v*.*`), I can't push to it directly anymore...
=> fix(ci): set 32 bits for all EICrecon runs

.github/workflows/linux-eic-shell.yml
This PR sets vm.mmap_rnd_bits=28 to get around the issues in:
- https://github.com/actions/runner/issues/3207
- https://github.com/google/sanitizers/issues/1614
No.
No.
=> fix(ci): set vm.mmap_rnd_bits=28

src/algorithms/reco/JetReconstruction.cc, src/algorithms/reco/JetReconstruction.h, src/algorithms/reco/JetReconstructionConfig.h, src/global/reco/JetReconstruction_factory.h
This PR resolves issue #1254. The `JetReconstruction` algorithm now determines the number of parameters needed for the selected fastjet algorithm and calls the relevant `JetDefinition` ctor.
In the process of resolving the issue, a new user-configurable parameter has been introduced into the algorithm's configuration: `pJet`, which sets the exponent on the energy weights of the distance measure in the case of the generalized kt algorithms.
No.
No.
---------
=> Fix Jet Algorithm Initialization Bug (#1331)

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/TrackParamTruthInit.cc, src/algorithms/tracking/TrackSeeding.cc
Uses correct indices for phi and theta in the seed covariance matrix (for EDM4EIC version 5). 
Indices are now consistent with those given here:
[https://github.com/acts-project/acts/blob/3eb0b4febd16ad8cee5664302e3542044ab17d35/Core/include/Acts/Definitions/TrackParametrization.hpp#L37-L56](https://github.com/acts-project/acts/blob/3eb0b4febd16ad8cee5664302e3542044ab17d35/Core/include/Acts/Definitions/TrackParametrization.hpp#L37-L56)
No modification was made for EDM4EIC version 4. So, `track_parameter.getMomentumError().xx` still corresponds to the theta error.
None
=> Fix to seed theta and phi covariance indices

src/algorithms/pid/ParticlesWithPID.cc
This PR changes the direct member access to a getter to avoid a compiler warning:
```
/home/wdconinc/git/EICrecon/.worktree/pfrich-digitization/src/algorithms/pid/ParticlesWithPID.cc:145:44: warning: 'referencePoint' is deprecated: use getReferencePoint instead [-Wdeprecated-declarations]
145 |             auto referencePoint = rec_part.referencePoint();
|                                            ^
/opt/local/include/edm4eic/MutableReconstructedParticle.h:142:5: note: 'referencePoint' has been explicitly marked deprecated here
142 |   [[deprecated("use getReferencePoint instead")]]
|     ^
```
This applies since https://github.com/AIDASoft/podio/pull/553.
No.
No.
=> fix: use proper EDM4hep getter in ParticlesWithPID.cc

src/algorithms/pid/ParticlesWithPID.cc, src/algorithms/reco/ElectronReconstruction.cc, src/algorithms/reco/InclusiveKinematicsDA.cc, src/algorithms/reco/InclusiveKinematicsElectron.cc, src/algorithms/reco/InclusiveKinematicsJB.cc, src/algorithms/reco/InclusiveKinematicsSigma.cc, src/algorithms/reco/InclusiveKinematicseSigma.cc, src/algorithms/reco/MatchClusters.cc, src/tests/tracking_test/TrackingTest_processor.cc
This is a subset of #970, that removes use of SimID and RecID fields (while switching to comparisons of full object id's instead of just the indices).
In principle, we could even drop `.getObjectID()` in comparisons and just use `Object::operator==` https://github.com/AIDASoft/podio/blob/400f4f06bef3e7666c71e31be579ec715c412b8a/python/templates/macros/implementations.jinja2#L160, which relies on pointer comparison instead.
No
No
=> treewide: use PODIO ObjectID instead SimID/RecID indices

src/scripts/eicrecon-this.sh.in
`eicrecon-this.sh` had an issue where it would **not** add EICrecon installs to the PATH and LD_LIBRARY_PATH if they were already in there, **even if there was another EICrecon install earlier in those paths**. That results in confusion when juggling (no pun intended) multiple worktrees with various EICrecon installs.
This PR adds a small utility `pathadd` that takes care of three things:
- always adds the specified directory to the front of the environment variable list to make sure it is found first,
- checks if the environment variable you want to add to is already there or not to avoid trailing colons,
- removes the specified directory from the interiors of the path if it is already somewhere.
On top of that it's POSIX-safe and doesn't use bashisms (which is what took 50% of the …
=> fix: ensure eicrecon-this.sh prepends even when already in PATH

.github/workflows/linux-eic-shell.yml, .gitignore, src/algorithms/tracking/ActsGeometryProvider.cc, src/algorithms/tracking/ActsGeometryProvider.h, src/services/geometry/acts/ACTSGeo_service.cc
Instead of writing our own obj files in `draw_surfaces` (with only support for planar surfaces), this PR converts it to use the Acts support for export to obj and ply files, optionally and with parameter support for coloring etc. Syntax is:
```
eicrecon -Pacts:WriteObj=true -Pacts:WritePly=true -Pacts:OutputDir=$PWD/tracking_geometry
```
where `OutputDir` must exist and defaults to current working directory (because it exists; upstream choice).
To open the obj and ply models, you can use e.g. [meshlab](https://www.meshlab.net). Just import all files at once.
No.
Yes, by default `tracking_geometry.obj` will not be written anymore.
=> feat: replace draw_surfaces with Acts-based obj and ply export

src/algorithms/reco/ElectronReconstruction.cc, src/algorithms/reco/ElectronReconstruction.h, src/algorithms/reco/ScatteredElectronsEMinusPz.cc, src/algorithms/reco/ScatteredElectronsTruth.cc, src/global/reco/ReconstructedElectrons_factory.h, src/global/reco/reco.cc
The ReconstructedElectron algorithm now uses the particle-cluster associations created by MatchClusters_factory rather than doing it itself.  It makes the collection ReconstructedElectrons a subset collection of ReconstructedParticles, so the association is kept between them.  
I will leave this as a draft until #1277 is merged, then update that code as well to take advantage of it.
ReconstructedElectrons is now a subset collection, but I don't believe that should break anything.
No
=> Adapt ElectronReconstruction to use MatchClusters

.github/release.yml
Without this, the generated release notes ignore contributions that don't belong to any of the tags specified.
=> release.yml: implement a catch-all category

.github/workflows/linux-eic-shell.yml
This PR will make CI runs start just a few microseconds faster... :-\ This made more sense when we were doing checkouts of an entire 50k-commit spack tree with fulll history because we couldn't specify tree-less or blob-less...
No.
No.
=> fix(ci): actions/checkout with filter: "tree:0"

.github/workflows/linux-eic-shell.yml
Introduced 6 months ago in 17c4137878de4695286caad7e1a26982402fe626
I was wondering why we haven't had any clang-tidy reports in a long while.
=> linux-eic-shell.yml: unbreak clang-tidy in PR context

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTrackingConfig.h, src/algorithms/tracking/IterativeVertexFinder.cc, src/algorithms/tracking/IterativeVertexFinderConfig.h, src/algorithms/tracking/OrthogonalTrackSeedingConfig.h, src/algorithms/tracking/TrackParamTruthInit.cc, src/algorithms/tracking/TrackParamTruthInitConfig.h, src/algorithms/tracking/TrackSeeding.cc, src/global/tracking/CKFTracking_factory.h, src/global/tracking/IterativeVertexFinder_factory.h, src/global/tracking/TrackParamTruthInit_factory.h, src/global/tracking/TrackSeeding_factory.h
Tidies the code so that the tracker configuration structs don't have the m_ tag. None of the other algorithm configuration structs are prefixed by m_ and it is my understanding that these are conventionally for class members which presumably they may have originally been before moving to a separate config.
No
No
=> Remove m_ member tags from tracking configuration structs

.github/workflows/linux-eic-shell.yml, CMakeLists.txt, cmake/jana_plugin.cmake, src/algorithms/CMakeLists.txt, src/algorithms/onnx/CMakeLists.txt, src/algorithms/onnx/InclusiveKinematicsML.cc, src/algorithms/onnx/InclusiveKinematicsML.h, src/algorithms/onnx/InclusiveKinematicsMLConfig.h, src/factories/reco/InclusiveKinematicsML_factory.h, src/global/reco/CMakeLists.txt, src/global/reco/reco.cc, src/services/io/podio/JEventProcessorPODIO.cc
This PR adds the hooks for ONNX Runtime (CPU only) for fast inference, and an example that doesn't actually do anything except... Enabled by default but not actually doing anything.
No.
No.
=> feat: example of how to use ONNX Runtime (Ort) in algorithms

.gitignore
Some files are not explicitly ignored, and can get mistakenly committed. This PR adds the macOS `.DS_Store` metadata files, and `.vscode/`, `.idea/`, `cmake-build-*/` also in subdirectories. See #1383.
No.
No.
=> fix: ignore .DS_Store, .vscode, .idea, cmake-build-* in subdirs

src/tests/track_propagation_test/TrackPropagationTest_processor.cc
This PR fixes an issue in src/tests/track_propagation_test where CentralCKFTrajectories were attempted to be cast into ActsExamples::Trajectories. Instead, CentralCKFActsTrajectories should be retrieved and cast into ActsExamples::Trajectories.
No.
No.
=> fix: CentralCKFActsTrajectories is the collection with ActsExamples::Trajectories

.github/workflows/linux-eic-shell.yml, src/tests/track_propagation_test/TrackPropagationTest_processor.cc
We don't test what's in src/tests, to a large degree (exception is the catch unit tests), and this leads to code issues, e.g. #1385.
This PR adds the test plugins in src/tests to a CI job. ~~It won't actually catch #1385 until we stop silently eating exceptions...~~ It catches #1385 now, https://github.com/eic/EICrecon/actions/runs/8726213766/job/23941043650#step:8:676.
No.
No.
=> fix(ci): add src/tests plugins as CI jobs

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc
This PR removes an old comment left in the MCParticle-Cluster association code. The comment stated that the code doesn't work for HcalEndcapPClusters, However, this seems to be no longer the case.
No.
No.
=> Remove outdated comment on mc-cluster associations

src/detectors/LUMISPECCAL/LUMISPECCAL.cc
The LumiSpecCAL name is from deprecated `$DETECTOR_PATH/compact/far_backward/lumi/spec_homo_cal.xml` that was replaced by the `spec_ScFi_cal.xml` in https://github.com/eic/epic/commit/eaf7f8089c16ef4e935e97c671e957f82942fea4#diff-9ff1b47fbddbe9afe982f6dc6cce5c5f43a15362ff43fa4216c0b4f34a4bd72eR10.
This PR brings EICrecon in accordance to the geometry change. The sector field is deprecated and is removed as part of this change.
No
Yes
=> LUMISPECCAL: LumiSpecCALHits -> EcalLumiSpecHits

src/algorithms/digi/SiliconTrackerDigi.cc, src/algorithms/digi/SiliconTrackerDigi.h, src/detectors/B0TRK/B0TRK.cc, src/detectors/BTOF/BTOF.cc, src/detectors/BTRK/BTRK.cc, src/detectors/BVTX/BVTX.cc, src/detectors/ECTOF/ECTOF.cc, src/detectors/ECTRK/ECTRK.cc, src/detectors/FOFFMTRK/FOFFMTRK.cc, src/detectors/LOWQ2/LOWQ2.cc, src/detectors/MPGD/MPGD.cc, src/detectors/RPOTS/RPOTS.cc, src/factories/digi/SiliconTrackerDigi_factory.h, src/services/io/podio/JEventProcessorPODIO.cc
This fills the `edm4eic::MCRecoTrackerHitAssociation` for each tracking detector. This should allow us to more easily implement track to MCParticle hit-based matching.
An example of the result for 1 single-muon event and one subsystem (SVT endcap) is shown below:
```
SiEndcapHitAssociations = (vector<edm4eic::MCRecoTrackerHitAssociationData>*)0x559bcc564160
SiEndcapHitAssociations.weight = 1.000000, 1.000000, 1.000000, 1.000000
SiEndcapHitAssociations.simHits_begin = 0, 1, 2, 3
SiEndcapHitAssociations.simHits_end = 1, 2, 3, 4
_SiEndcapHitAssociations_simHits = (vector<podio::ObjectID>*)0x559bcc5a96a0
_SiEndcapHitAssociations_simHits.index = 2, 3, 1, 0
_SiEndcapHitAssociations_simHits.collectionID = 1948551886, 1948551886, 1948551886, 1948551886
_SiEndcapHitAssociations_rawHit = …
```
=> Add associations between tracker Raw and Sim hits

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h, src/algorithms/calorimetry/ImagingClusterReco.h, src/algorithms/reco/MatchClusters.cc, src/algorithms/reco/MatchClusters.h
This fixes compatibility with PODIO 00-17-04+ where check
https://github.com/AIDASoft/podio/blob/5964958a9b151ea3637342e1e9aad1629f6de7a6/python/templates/Collection.cc.jinja2#L161C34-L161C91
was implemented as a part of the
https://github.com/AIDASoft/podio/commit/e5a13c2b8382c6969c6b3a6092de7adda0fd33f0
Fixes: #1366
=> treewide: fix "Immutable objects can only be added to subset collections" exception

.github/workflows/linux-eic-shell.yml
Adds tests for the pythia6 min bias events at all standard beam energies. This includes electrons within the Low-Q2 tagger acceptance which currently no other samples cover.
=> Add minbias test

src/algorithms/calorimetry/CalorimeterHitDigi.cc, src/algorithms/calorimetry/CalorimeterHitDigi.h
This PR reverts the RandomSvc back to an adhoc implementation.
No.
Hopefully makes calorimeter digitization truly (pseudo-)random again...
=> fix: revert RandomSvc back to std::default_random_engine

src/algorithms/fardetectors/FarDetectorTrackerCluster.cc
ulong from sys/types is not a standard C type
This fixes a compilation error:
```
src/algorithms/fardetectors/FarDetectorTrackerCluster.cc:113:26: error: use of undeclared identifier 'ulong'; did you mean 'long'?
ROOT::VecOps::RVec<ulong> clusterList = {maxIndex};
^~~~~
long
```
=> FarDetectorTrackerCluster.cc: ulong -> unsigned long

CMakeLists.txt, cmake/jana_plugin.cmake
This prevents EICrecon from picking up Findonnxruntime.cmake from Acts. The actual onnxruntime only ever provided the config, to my best knowledge.
=> cmake: use CONFIG mode for onnxruntime

src/algorithms/reco/HadronicFinalState.cc, src/algorithms/reco/HadronicFinalState.h, src/factories/reco/HadronicFinalState_factory.h, src/global/reco/reco.cc, src/services/io/podio/JEventProcessorPODIO.cc
This adds and algorithm and corresponding factory for calculating hadronic final state variables.  Since this uses a new `EDM4eic` data type not included in major release 5, the algorithm is only called for major release >= 6.
=> Created algorithm and factory for calculating hadronic final state variables

src/factories/calorimetry/CalorimeterClusterRecoCoG_factory.h, src/factories/calorimetry/CalorimeterHitReco_factory.h, src/factories/calorimetry/CalorimeterHitsMerger_factory.h, src/factories/calorimetry/CalorimeterIslandCluster_factory.h, src/factories/calorimetry/CalorimeterTruthClustering_factory.h, src/factories/calorimetry/EnergyPositionClusterMerger_factory.h, src/factories/calorimetry/HEXPLIT_factory.h, src/factories/calorimetry/ImagingClusterReco_factory.h, src/factories/calorimetry/ImagingTopoCluster_factory.h, src/factories/calorimetry/TruthEnergyPositionClusterMerger_factory.h, src/factories/digi/SiliconTrackerDigi_factory.h, src/factories/fardetectors/FarDetectorLinearTracking_factory.h, src/factories/fardetectors/FarDetectorTrackerCluster_factory.h, src/factories/fardetectors/MatrixTransferStatic_factory.h, src/factories/meta/CollectionCollector_factory.h, src/factories/meta/FilterMatching_factory.h, src/factories/meta/SubDivideCollection_factory.h, src/factories/reco/InclusiveKinematicsML_factory.h, src/factories/reco/InclusiveKinematicsReconstructed_factory.h, src/factories/reco/InclusiveKinematicsTruth_factory.h, src/factories/reco/JetReconstruction_factory.h, src/factories/reco/TransformBreitFrame_factory.h, src/global/digi/PhotoMultiplierHitDigi_factory.h, src/global/pid/MergeTrack_factory.h, src/global/reco/MatchClusters_factory.h
With the switch to the algorithms interface, we need to explicitly pass the logger level from the JOmniFactory to the algorithm, i.e. `m_algo->level(static_cast<algorithms::LogLevel>(logger()->level()));`. Only this allows the algorithm to use the log level that is specified on the command line.
This PR adds the necessary line for those factories that use algorithms-interfaced algorithms. There may be other factories that I overlooked. Not sure how to fail compilation when we don't do this.
No.
No.
=> fix: pass logger options from factory to algorithms-interfaced algorithms

.github/workflows/linux-eic-shell.yml
This PR suppresses unsigned integer overflow warnings by UBSan. These are virtually always in basic_string.h due to string comparisons, e.g. https://github.com/eic/EICrecon/actions/runs/8976184643/job/24652936018#step:8:125. They are noisy and detract from other UB, in particular when they appear on line 1.
No.
No.
=> fix(ci): ubsan with silence_unsigned_overflow=1

.github/workflows/linux-eic-shell.yml
This PR adds the release environment name to the ccache key to ensure that eic_xl:nightly and eic_xl:24.04.0-stable each get a separate ccache.
No.
No.
=> fix(ci): add matrix.release to ccache key

.github/workflows/linux-eic-shell.yml
We are having issues with hosting capybara reports with too many files produced (collect-docs fails).
=> linux-eic-shell.yml: remove configurations with minq2=1

.github/workflows/linux-eic-shell.yml
Was removed in https://github.com/eic/EICrecon/pull/1427, where the tests got away
```
[INFO] JPluginLoader: Initializing plugin "/usr/local/lib/EICrecon/plugins/reco_test.so"
```
Once nightly had hit cvmfs, that wouldn't work anymore.
=> linux-eic-shell.yml: remove eicrecon-test-plugins[reco_test]

cmake/jana_plugin.cmake
This prevents compilation on non-gnu
=> jana_plugin.cmake: fix typo

src/algorithms/pid_lut/PIDLookup.cc
This is a hotfix for PDG derived by roll of a dice being overwritten. This became a problem when factories were chained and now results in coverage limited to DRICH:
=> pid_lut: avoid overwriting PDG

src/detectors/RPOTS/RPOTS.cc
Fix bug in old positions for RP sensors in EICrecon.
- [x ] Bug fix (issue #__)
- [ x] Tests for the changes have been added
No.
Yes - this will make RP tracks work again.
=> correct z positions of hits for RP

src/algorithms/pid_lut/PIDLookup.cc
Second iteration on #1442. None of the hadrons should be affected by convention, but electron is one of exceptions.
This was discovered in benchmark
https://github.com/eic/physics_benchmarks/blob/cd616f2a92e5d59f9e94c27d9ad0a1b8c18daeef/benchmarks/dis/analysis/truth_reconstruction.py#L56
Fixes: https://github.com/eic/physics_benchmarks/issues/7
=> PIDLookup: fix incorrect PDG convention - electron should not be -11

src/algorithms/pid_lut/PIDLookup.cc
This is a hotfix for PDG derived by roll of a dice being overwritten. This became a problem when factories were chained and now results in coverage limited to DRICH:
(cherry picked from commit 5a703aa9b028b720cfd2a1a7c96e93ed26e1807e)
=> [v1.13] pid_lut: avoid overwriting PDG

src/algorithms/reco/JetReconstructionConfig.h
This is also the default in FastJet
https://fastjet.fr/repo/doxygen-3.4.2/namespacefastjet_1_1gas.html
Some measurements for a trivial e- reconstruction:
Before:
```
Elapsed (wall clock) time (h:mm:ss or m:ss): 10:25.74
```
After:
```
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:42.34
```
Closes: #1348
Credit for suggestion goes to @rosijreed
=> JetReconstructionConfig: reduce default ghost area to 0.01

src/algorithms/pid_lut/PIDLookup.cc
Second iteration on #1442. None of the hadrons should be affected by convention, but electron is one of exceptions.
This was discovered in benchmark
https://github.com/eic/physics_benchmarks/blob/cd616f2a92e5d59f9e94c27d9ad0a1b8c18daeef/benchmarks/dis/analysis/truth_reconstruction.py#L56
Fixes: https://github.com/eic/physics_benchmarks/issues/7
=> [v1.13] PIDLookup: fix incorrect PDG convention - electron should not be -11

CMakeLists.txt
Boost defines the environment variable `BOOST_ROOT`, which violates the older CMake case-sensitivity syntax for `find_package(Boost)`. Therefore, in CMake 3.27, the policy was changed to also look at uppercase `<PACKAGENAME>_ROOT` environment variables. In `eic-shell`, where we have such a newer version, this generates a build warning since the new policy is available but it is not explicitly enabled or disabled.
This PR explicitly enables the policy in those CMake versions that support it. This doesn't affect running in `eic-shell` other than hiding the warning. Outside `eic-shell`, for newer CMake versions (>= 3.27), it should only increase the likelihood that the correct Boost version is found without having to hint it on the command line. For older CMake versions (>= 3.24, but < …
=> fix: do not warn about `BOOST_ROOT`

.pre-commit-config.yaml
We already have pre-commit enabled on command line and preventing code from being committed that fails clang-format. But it just prints out a diff to apply and doesn't apply it...
This PR applies the clang-format changes that are suggested.
Note: no automatic changes are applied by the CI workflows because of this change.
No.
No.
=> feat: pre-commit fix in place (interactive use only)

src/algorithms/reco/JetReconstructionConfig.h
=> [Backport v1.13] JetReconstructionConfig: reduce default ghost area to 0.01

src/algorithms/tracking/TrackPropagation.cc, src/algorithms/tracking/TrackPropagation.h, src/detectors/DRICH/DRICH.cc, src/global/pid/RichTrack_factory.h, src/global/tracking/TrackPropagation_factory.h, src/global/tracking/tracking.cc, src/tests/track_propagation_test/TrackPropagationTest_processor.cc
The tracks propagated to the calorimeter surfaces and the DRICH aerogel and gas surfaces did not contain the relation to the track.
This PR adds the track relations to CalorimeterTrackProjections and the DRICH{Aerogel,Gas}Tracks collections.
Note the methodology here. We don't use edm4eic::Tracks to do the propagation, so this here relies on keeping the order in the edm4eic::Tracks and ActsExamples::Trajectories.
No.
No.
=> feat: set track relation for calorimeter and DRICH propagations

src/tests/omnifactory_test/JOmniFactoryTests.cc
Fails with new PODIO
This is same as #1379
=> omnifactory_test: fix "Immutable objects can only be added to subset collections" exception

.github/workflows/linux-eic-shell.yml
The documentation https://docs.github.com/en/actions/learn-github-actions/contexts#github-context says that it only works for pull_request*, but there is some hope that it can inherit from merge_group payload too https://docs.github.com/en/webhooks/webhook-events-and-payloads#merge_group . Then that would fix issues with missing capybara references on main: https://github.com/eic/EICrecon/issues/1264
Fixes: #1264
=> linux-eic-shell.yml: use github.head_ref

.github/workflows/linux-eic-shell.yml
`github.base_ref` doesn't work for merge_group: https://github.com/eic/EICrecon/actions/runs/9120955781/job/25084018811#step:13:21
It's put after github.base_ref, so that we can later test if this can be reverted by re-running with enabled debug logging.
=> linux-eic-shell.yml: use github.event.merge_group.base_ref

.github/workflows/linux-eic-shell.yml
This is needed to display a human-friendly pipeline name on eicweb.
https://eicweb.phy.anl.gov/containers/eic_container/-/commit/7d9d792dfcab74311dc5beea7bb45e965bb40df7
=> linux-eic-shell.yml: pass PIPELINE_NAME_CONTAINER

CMakeLists.txt, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/IterativeVertexFinder.cc, src/algorithms/tracking/TrackParamTruthInit.cc, src/algorithms/tracking/TrackSeeding.cc
=> Drop support for EDM4eic 4.0.0 and older

src/algorithms/fardetectors/FarDetectorLinearProjection.cc, src/algorithms/fardetectors/FarDetectorLinearProjection.h, src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc, src/benchmarks/reconstruction/tracking_efficiency/TrackingEfficiency_processor.cc, src/benchmarks/reconstruction/tracking_occupancy/TrackingOccupancy_processor.cc, src/extensions/jana/JOmniFactory.h, src/extensions/spdlog/SpdlogMixin.h, src/services/geometry/acts/ACTSGeo_service.cc, src/services/geometry/acts/ACTSGeo_service.h, src/services/geometry/dd4hep/DD4hep_service.cc, src/services/geometry/richgeo/RichGeo_service.cc, src/services/log/Log_service.cc, src/services/log/Log_service.h, src/tests/tracking_test/TrackingTest_processor.cc, src/utilities/dump_flags/DumpFlags_processor.cc
The Log_service::logger(name) call defines name:LogLevel already, so callers don't need to do this anymore. That removes the need for SpdlogExtensions.h includes in factories.
This PR removes the double defines, removes the headers, and also unifies the Acts loggers, so we don't have one for init and one for regular.
No.
No.
=> fix: don't double-define logger LogLevel parameters

src/algorithms/calorimetry/TrackClusterMergeSplitter.cc, src/algorithms/calorimetry/TrackClusterMergeSplitter.h, src/algorithms/calorimetry/TrackClusterMergeSplitterConfig.h, src/detectors/BHCAL/BHCAL.cc, src/factories/calorimetry/TrackClusterMergeSplitter_factory.h, src/services/io/podio/JEventProcessorPODIO.cc
This PR converts the proposed track-based cluster merger algorithm to operate on protoclusters and produce protoclusters rather than reconstructed clusters.
n/a
n/a
=> Use protoclusters for track cluster merger

.github/workflows/linux-eic-shell.yml
This PR moves the default JANA options into an env variable at the top. This PR also adds a large ticker value to avoid filling logs with 1Hz ticker lines. This PR also has JANA print out an extended report at the end (which mostly matters for multi-threading, and for single-threading is just identical).
No.
No.
=> feat(ci): disable jana ticker; assemble JANA_OPTIONS in env variable

src/algorithms/tracking/ActsToTracks.cc, src/algorithms/tracking/ActsToTracks.h, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTracking.h, src/global/tracking/ActsToTracks_factory.h, src/global/tracking/CKFTracking_factory.h, src/global/tracking/tracking.cc
This is intended to allow code reuse in #1383
No
No
=> tracking: refactor EDM conversion to ActsToTracks

src/detectors/BEMC/BEMC.cc
The clustering parameter, localDistXZ  is changed from {40 mm, 40mm} to {80mm, 80mm}. 
Minimizes the cluster splitting at the pseudorapidities corresponding to forward and backward region. The results can be seen here:
https://docs.google.com/presentation/d/1DympCgYqOKZBqyOqESEXCtlv073pGnkf266O1KRoba8/edit?usp=sharing
=> Update the localDistXZ paramter in BEMC.cc

src/utilities/eicrecon/eicrecon_cli.cpp
This PR adds two extra lines to the usage info, explaining how to add extra plugins or disable default plugins.
We now get:
```
$ eicrecon
Usage:
eicrecon [options] source1 source2 ...
Description:
Command-line interface for running JANA plugins. This can be used to
read in events and process them. Command-line flags control configuration
while additional arguments denote input files, which are to be loaded and
processed by the appropriate EventSource plugin.
Options:
-h   --help                  Display this message
-v   --version               Display version information
-j   --janaversion           Display JANA version information
-c   --configs               Display configuration parameters
-l   --loadconfigs <file>    Load configuration parameters from file
-d   --dumpconfigs <file> …
```
=> feat: add plugin usage info to `eicrecon -h`

src/algorithms/calorimetry/ImagingClusterReco.h
ImagingClusterReco uses multiplication of Vector3f with float, which is defined in vector_utils. IWYU has trouble with operators.
No.
No.
=> fix: include vector_utils in ImagingClusterReco

.github/iwyu.imp, src/services/io/podio/JEventProcessorPODIO.cc, src/services/io/podio/JEventProcessorPODIO.h
This is a follow up on a resolution from #1323
No
No
=> JEventProcessorPODIO: deprecate podio:output_include_collections parameter

.github/workflows/linux-eic-shell.yml
This PR fixes how we determine the detector hash that tells us when we have to rerun the npsim part of the pipeline to make sure our simulation and reconstruction are using the same geometry.
Due to changes in the containers (epic now in spack), the previous approach returns nothing for any geometry
```console
grep epic/nightly /cvmfs/singularity.opensciencegrid.org/eicweb/jug_xl\:nightly/etc/jug_info | sed 's/.*: .*-\(.*\)/hash=\1/g'
```
The new approach takes the hash of, e.g.
```console
$ grep ' epic@' /cvmfs/singularity.opensciencegrid.org/eicweb/jug_xl:nightly/etc/jug_info
- [+] gqyaoru epic@23.10.0
- [+] l6jmpez epic@23.11.0
- [+] m4h7dpf epic@23.12.0
- [+] malsskd epic@24.02.0
- [+] ey2eyus epic@24.02.1
- [+] wtzurj6 epic@24.03.0
- [+] 3bqnqno epic@24.03.1
- [+] ybvec7w …
```
=> fix(ci): use correct detector-info hash

src/algorithms/calorimetry/TruthEnergyPositionClusterMerger.h
This PR ensures that we are including collection headers in TruthEnergyPositionClusterMerger, not just data type headers.
No.
No.
=> fix: use correct EDM headers in TruthEnergyPositionClusterMerger

src/detectors/FHCAL/FHCAL.cc
Fix to LFHCAL clustering, avoiding sign error on local coordinates
- [X ] Bug fix (issue #__)
- [ X] Documentation has been added / updated
- [ X] Changes have been communicated to collaborators
Nothing breaks and no changes needed
Yes - it no longer splits clusters
=> fixed LFHCAL adjacency matrix

docs/tutorial/05-contributing.md, src/algorithms/calorimetry/CalorimeterIslandCluster.h, src/algorithms/calorimetry/ImagingTopoCluster.h
This PR fixes some spelling mistakes to pass codespell checks.
No.
No.
=> fix: codespell suggestions

src/global/beam/beam.cc
Adds MCBeamNeutron and MCBeamHadron collections. This matches the current use case in beam.h rather than only providing the protons.
No
No
=>  Introduce MCBeamNeutron and MCBeamHadron Collections

src/global/tracking/tracking.cc
Injects the LowQ2 tracks into the tracking workflow so they can finally be used like any other particle.
This might not be the best place to add the information from the events in the longer term as there will may be some extra looping over calorimeter and pid hits which aren't possible. At the moment though there isn't another easy place to add them while there is a mix of ReconstructedChargedParticles and ReconstructedParticles used in different places.
No
Low-Q2 electrons should show up in ReconstructedParticle collections and easily identifiable in the InclusiveKinematics collections
=> Inject Low-Q2 electrons into tracking

src/global/tracking/tracking.cc
=> [Backport v1.14] Inject Low-Q2 electrons into tracking

src/detectors/FHCAL/FHCAL.cc
=> [Backport v1.14] fixed LFHCAL adjacency matrix

src/detectors/FHCAL/FHCAL.cc
Changed sampling fraction for the insert from 0.98% to 2.59% in order to match the change from mixed W + Fe absorbers to all Fe absorbers (see pull request https://github.com/eic/epic/pull/744 in the epic repository)
Changes the sampling fraction for reconstructing hits in the calorimeter insert to match a change in the materials used in the detector
yes.  Users must use the updated detector geometry:  https://github.com/eic/epic/pull/744
yes.
=> HcalEndcapPInsert*Clusters: update sampFrac

CMakeLists.txt, src/global/reco/CMakeLists.txt, src/global/reco/reco.cc
This PR passes USE_ONNX as a compile definition and guards use of ONNX functionality with an ifdef.
No.
No.
=> fix: ensure USE_ONNX=OFF can compile

src/global/tracking/tracking.cc
This should restore the ability to write out tracks from the central detector while using an xml configuration which doesn't contain the far-backward detectors (and vise versa)
=> Make TaggerTracker and/or central tracks optional

src/global/pid/IrtCherenkovParticleID_factory.h
This PR should(?) fix the drich_fixed_eta reconstruction benchmark error in https://eicweb.phy.anl.gov/EIC/benchmarks/reconstruction_benchmarks/-/jobs/3441830. Unfortunately I can't reproduce the issue locally (it always works). The CI pipeline will have to tell if this works...
No.
No.
=> fix: require AlgorithmsInit_service in IrtCherenkovParticleID for ParticleSvc

src/factories/reco/HadronicFinalState_factory.h, src/factories/reco/InclusiveKinematicsReconstructed_factory.h, src/factories/reco/TransformBreitFrame_factory.h, src/global/tracking/TrackParamTruthInit_factory.h
More of changes like #1522.
Closes: #1523
=> treewide: add missing AlgorithmsInit_service for particleSvc

CMakeLists.txt, cmake/jana_plugin.cmake
We do not use the Acts Identification and TGeo plugins, but we do need the Acts Json plugin.
No.
No.
=> fix: don't require Acts::{Identification,TGeo} component, but require Json

src/algorithms/reco/FarForwardNeutronReconstructionConfig.h, src/detectors/ZDC/ZDC.cc, src/global/reco/reco.cc
This sets the sampling fraction of the ZDC LYSO calorimeter back to unity, since it is a homogenous calorimeter. This will give more accurate reconstruction for low-energy photons.
No
Yes, for ZDC LYSO clusters
=> Fix: Correct ZDC LYSO Sampling Fraction

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/DD4hepBField.h, src/algorithms/tracking/IterativeVertexFinder.cc, src/algorithms/tracking/SpacePoint.h, src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackProjector.h, src/algorithms/tracking/TrackSeeding.cc
This adapts our tracking algorithms to any Acts version between v31 and v36 (to be released, so additional refactors may hit the Acts main branch that would need porting).
The commits in this branch are topologically ordered with reference to the commit message title, Acts PR number, and version validity. All commits compile individually, but no event-for-event validation has been performed.
The support for mulitple versions is done by somewhat extensive use of preprocessor directives based on `Acts_VERSION_MAJOR`.
Builds with:
- v32.1.0: https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/3481513#L3103
- v33.1.0: https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/3482111#L3549
- v34.1.0: https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/3482134#L3699
- v35.0.0: …
=> feat: fix compilation for Acts versions from v33 up to v35

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, src/algorithms/calorimetry/CalorimeterClusterRecoCoGConfig.h, src/detectors/BEMC/BEMC.cc, src/detectors/FHCAL/FHCAL.cc, src/detectors/ZDC/ZDC.cc, src/factories/calorimetry/CalorimeterClusterRecoCoG_factory.h, src/tests/algorithms_test/calorimetry_CalorimeterClusterRecoCoG.cc
This partially reverts effect of #1391. The clusterShape has become a way to extend EDM without going through extending it. We should sort those variable out into proper members, this is a first step.
=> CalorimeterClusterRecoCoG: set intrinsic{Phi,Theta}

src/algorithms/tracking/TracksToParticles.cc
People were confused by us removing truth PDG in ReconstructedParticles, so we better remove this too, before it is relied upon for too much.
No
Yes
=> TracksToParticles: avoid initializing mass from truth

src/algorithms/calorimetry/ImagingTopoCluster.h
Fixed an issue where "break" is not included in a case/break statement.
When initializing the ImagingTopoCluster algorithm, there is a switch statement wherein different things are printed to inform the user what the parameters are (depending on the layer mode).  This lacked breaks for the cases, causing the other print statements to be executed.  This patch fixes it.  
no.  no
yes.  only prints out the information about the cuts for defining neighbors that is relevent based on the layer mode.
=> ImagingTopoCluster: fix Init printouts by adding missing break statements

src/algorithms/tracking/OrthogonalTrackSeedingConfig.h, src/algorithms/tracking/TrackSeeding.cc
The _rMin_ parameter defined in the seeder configuration file was not being passed to the seed finder. This PR adds this. The parameter is currently set to the default value defined here:
https://github.com/acts-project/acts/blob/main/Core/include/Acts/Seeding/SeedFinderOrthogonalConfig.hpp#L39
https://github.com/acts-project/acts/blob/main/Core/include/Acts/Seeding/SeedFinderConfig.hpp#L43
So, there should be no change to the output. But it will be needed in the future if we ever want to search for seeds in an outer part of the tracking detector volume.
In addition, the _bFieldMin_ parameter defined in the seeder configuration file but not passed to the seed finder has been removed. This parameter does not seem to be a Acts seed finder parameter in any event. It seems to only be used if …
=> Added missing seed finder parameter

src/detectors/BHCAL/BHCAL.cc
This readout field was removed in 24.03.0. We don't need to support it.
No
No
=> BHCAL: drop support for legacy sectors

.github/ubsan.supp, .github/workflows/linux-eic-shell.yml
We're at 71 warnings (https://github.com/eic/EICrecon/actions/runs/10238130891), most outside of our control in boost iostream, eigen3, and acts. This PR causes UBSan to print the actual error name to use in the suppression file, and then uses that to suppress the false positives (well, out of our scope errors). This bring us down to 34 errors.
No.
No.
=> fix(ci): suppress more UB false positives out of our scope

src/algorithms/calorimetry/CalorimeterIslandCluster.cc, src/algorithms/calorimetry/CalorimeterIslandCluster.h, src/algorithms/calorimetry/CalorimeterIslandClusterConfig.h, src/detectors/EEMC/EEMC.cc, src/tests/algorithms_test/calorimetry_CalorimeterIslandCluster.cc
This reduces excessive splitting observed in EEEMCal. The issue is observed by looking at E/p in log scale. The splitting causes an extended tail towards lower E/p, which reduces electron efficiency.
No
Yes
=> CalorimeterIslandCluster: peakNeighbourhoodMatrix to control how far peaks need to be to split

src/algorithms/tracking/IterativeVertexFinder.cc
This PR fixes incorrect smart pointer handling that caused shared ownership semantics to be violated and objects to be deleted early.
No.
No.
=> fix: properly const_cast dynamic BField pointer

src/algorithms/calorimetry/CalorimeterHitDigi.cc
In some configurations (EcalBarrelImagingRawHits), the pedestal mean (14 a.u.) and sigma (5 a.u.) are such that negative hit pedestal channel numbers are not uncommon in a simple Gaussian model. For low energy hits, this pushes the ADC value into negative double range, and conversion to unsigned long long results in integer wraparound. E.g. https://github.com/eic/EICrecon/actions/runs/10239218932/job/28324710737#step:9:6119.
```
Error: /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterHitDigi.cc:186:38: runtime error: implicit conversion from type 'long long' of value -2 (64-bit, signed) to type 'unsigned long long' changed the value to 18446744073709551614 (64-bit, unsigned)
```
This PR prevents the hit pedestal value from being negative. This PR does not address …
=> fix: avoid integer wraparound in CalorimeterHitDigi

src/algorithms/calorimetry/CalorimeterHitReco.cc, src/algorithms/tracking/TrackerHitReconstruction.cc, src/factories/calorimetry/CalorimeterHitDigi_factory.h
Add one-to-one relation with raw tracker/calorimeter hit for reconstructed tracker/calorimeter hit. Contingent on https://github.com/eic/EDM4eic/pull/86.
=> Add one-to-one relation with raw tracker/calorimeter hit for reconstructed tracker/calorimeter hit

src/algorithms/calorimetry/CalorimeterHitReco.cc
When a raw hit is encountered with an energy amplitude greater than the ADC capacity we think we are working with, then this almost certainly is an indication of a digitization configuration error. E.g. https://github.com/eic/EICrecon/actions/runs/10239218932/job/28324710737#step:9:6119.
This PR adds an error message for these raw hits in calorimetry.
No.
No.
=> feat: print error when raw hit has amplitude > ADC capacity

src/algorithms/calorimetry/CalorimeterIslandCluster.cc
This fixes a small regression from https://github.com/eic/EICrecon/pull/1554 pointed out by @wdconinc. Some error messages would appear for detectors that are not using matrices and don't specify "readout" field. This allows the current status quo to continue, but removes the messages.
No
No
=> CalorimeterIslandCluster: avoid complaining about missing readouts

src/detectors/BHCAL/BHCAL.cc, src/detectors/FEMC/FEMC.cc, src/detectors/ZDC/ZDC.cc
The priority of values is given by https://github.com/eic/EICrecon/blob/0d5b8d8d156099a5b1e585e277b394ff3cd61109/src/algorithms/calorimetry/CalorimeterIslandCluster.cc#L112-L120 in descending order. Hence dimScaledLocalDistXY is taken in precedence by all others. adjacencyMatrix trumps localDistXY. Hence, those values can be removed, especially given that they are often incorrect and misleading.
No
No
=> src/detectors: remove unused dimScaledLocalDistXY settings

src/algorithms/calorimetry/CalorimeterIslandCluster.cc
A bug that was introduced when EICrecon code was produced from copy-pasting code from Juggler. A `uprops` variable that set option priority used to be an `std::vector`
https://eicweb.phy.anl.gov/EIC/juggler/-/blob/main/JugReco/src/components/CalorimeterIslandCluster.cpp#L213
but later became an `std::map`
https://github.com/eic/EICrecon/commit/de2f4896ff04af17dff7e2a96e0aee7485005e34#diff-57b413772a7a45d51cd383a3e763c8f739f1783ff05c234a7fdd130dd23d3045R88
hence the priority ordering became platform-dependent.
Need to check
Yes
=> CalorimeterIslandCluster: fix incorrect distance parameter priorities

.github/workflows/linux-eic-shell.yml, docs/howto/visualize_callgraph.md, docs/tutorial/02-work-environment.md, docs/tutorial/04-factory.md, src/benchmarks/reconstruction/tof_efficiency/README.md, src/benchmarks/reconstruction/tracking_efficiency/README.md, src/detectors/LUMISPECCAL/README.md, src/services/io/podio/README.md
This is a follow up on #1466 with focus on docs and use examples in general.
No
No
=> treewide: use podio:output_collections instead of deprecated podio:output_include_collections

src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc
This PR makes the cluster time deterministic, and not based on the whim of which hit happens to be first. It defines the cluster time as the energy-weighted average of all hit times.
This is not the only deterministic choice here (earliest hit is another).
No.
No.
=> fix: deterministic cluster time

src/detectors/BTOF/BTOF.cc, src/detectors/DIRC/DIRC.cc, src/detectors/DRICH/DRICH.cc, src/detectors/PFRICH/PFRICH.cc, src/global/tracking/tracking.cc, src/services/io/podio/JEventProcessorPODIO.cc
As we agreed during the collaboration meeting, the real seeding workflow is mature and should become the default. This changes Seeded collections to not include that prefix, and prefixless collections are moved to TruthSeeding (name is long but not supposed to be used by general users). As a side effect, Jet finding and ReconstructedParticles and DRICH IRT-based PID will use real seeding.
No
Yes
=> tracking: use Seeded tracks by default, rename previous default to TruthSeeded

src/detectors/FHCAL/FHCAL.cc
Updates the MIP value used in the HEXPLIT algorithm in the calorimeter insert.  Also lowers the threshold for the center hit in a cluster.  Doing this fixes issues in the benchmark for neutron reconstruction ( see https://github.com/eic/physics_benchmarks/issues/32 ).
no
yes.  Changes the parameters of the topo clustering.
=> updated MIP value in insert; also adjusted parameters of the topo clustering

src/algorithms/pid_lut/PIDLookup.cc
This disambiguates associations by selecting one with the largest contribution. As the result, no more need to output pesky warnings:
```
[PFRICH:RICHEndcapNLUTPID] [warning] Found a duplicate association for ReconstructedParticle at index 0
[PFRICH:RICHEndcapNLUTPID] [warning] The previous MCParticle was at 2 and the duplicate is at 0
```
No
No
=> PIDLookup: avoid complaining about ambiguous associations

src/utilities/eicrecon/eicrecon_cli.cpp
Users will be notified about a way to re-enable the parameter table: https://github.com/JeffersonLab/JANA2/blob/a439a5682586bf4ba951a9723aa0d4cf55015e35/src/libraries/JANA/Services/JParameterManager.cc#L127
Reduce amount of output
No
Yes
=> eicrecon_cli: disable parameter tables for JANA2 2.3.x

src/detectors/MPGD/MPGD.cc
Changes MPGD threshold values to 100 eV based on updated estimates
- [x ] Other: __
- [x ] Changes have been communicated to collaborators
No breaking changes. MPGD layers will now have more efficient hit reconstruction
MPGD detectors will see increase in hit reconstruction efficiency
=> Update MPGD.cc thresholds

src/detectors/ZDC/ZDC.cc
This PR updates the digitization parameters for the SiPM-on-Tile ZDC. The current default parameters place a zero-suppression threshold at 40 ADC channels. With a 15-bit ADC with dynamic range of 800 MeV, this is a cut at 0.98 MeV (~ 2 MIPs). We see that this has an impact on the energy reconstruction for single-particle simulations.
This PR changes following values:
```
ADC Capacity = 16-bit (65536 channels)
DynamicRange = 1000 MeV (0.015 MeV per ADC channel)
pedSigmaADC = 2
thresholdFactor = 3.0
```
These parameters are realistic. The HGROC ASIC can have a capacity of 16-bits; a high-energy photon shower can leave up to 800-1000 MeV in a single channel; and a zero-suppression cut of 6 ADC channels (0.2 MIPs) will allow studies of threshold cuts in the 0.2-0.5 MIP range.
The above …
=> Update to SiPM-on-Tile ZDC digitization parameters

CMakeLists.txt, src/extensions/jana/JOmniFactory.h, src/extensions/jana/JOmniFactoryGeneratorT.h, src/tests/omnifactory_test/JOmniFactoryTests.cc
This cleans up the EICrecon compilation output by fixing some deprecation warnings coming from JANA2. It also removes some JANA2-related TODO comments. It updates a test case to no longer use a template method that hasn't been deprecated, but is about to be.
No
No
=> Fix JANA2-related deprecation warnings and TODOs

.github/lsan.supp
Since a week or so, CI jobs on `main` have been failing, https://github.com/eic/EICrecon/actions/workflows/linux-eic-shell.yml?query=branch%3Amain. First one was https://github.com/eic/EICrecon/actions/runs/11171861991. This appears to be due to LSan in libJANA.so, e.g. https://github.com/eic/EICrecon/actions/runs/11171861991/job/31058015623#step:9:3979:
```
=================================================================
==609==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 272 byte(s) in 2 object(s) allocated from:
#0 0x55e2fb0ba20d in operator new(unsigned long) (/home/runner/work/EICrecon/EICrecon/install/bin/eicrecon+0x10e20d) (BuildId: a5040da1707e76901d07b3ade4bdca35b7daccf2)
#1 0x7f2d2a6a06d1 in JStreamLog::JStreamLog(std::ostream const&, char const*) …
```
=> fix(ci): suppress memory leaks in libJANA.so

.github/workflows/linux-eic-shell.yml
We are using python3.11 now, so the `pip install` would install to `~/.local/lib/python3.11/site-packages` if it did anything, and the hardcoded `PYTHONPATH` prepend would then fail to find the module. That this continued to work demonstrates that we don't need to install anything locally, and can get rid of the `PYTHONPATH` modifications too.
This PR removes the `PYTHONPATH` additions and the custom `pip install`. If an update to the bokeh and pygithub packages are needed, then this is better handled by updating what is in the container, now that we have reached a more stable capybara stage of development.
No.
No.
=> fix(ci): avoid python3.10 reference; don't install bokeh, pygithub

.github/workflows/linux-eic-shell.yml
When, for some reason, the reference artifacts on `main` are not available (typically recovering from a failing `main`), then we don't generate capybara output and the `build-docs` job fails when trying to merge the capy files. E.g. https://github.com/eic/EICrecon/actions/runs/11282255676/job/31379983435. There is no gracious "don't fail when you can't merge anything" option.
This PR ensures that we always have capy files generated, even when we don't actually have a reference to compare to. The only thing that will be included if there are is reference is the new file. That's still useful information to plot.
No.
No.
=> fix(ci): always run capybara, even when ref is not found

src/detectors/EEMC/EEMC.cc
This comes from Athena times where all calorimeters were smeared by 2%. We don't expect this term, we want to have something more motivated like #1064, instead. Submitting separately to confirm the effect.
=> EEEMCal: remove 2% smearing

src/algorithms/fardetectors/MatrixTransferStatic.cc
This PR introduces a bug fix for the p_y reconstruction in the Roman pots, and also switches the reco to global coordinates. There are some issues with the basic RP concept and how local coordinates are calculated using the cellIDs. It means an additional set of shifts would need to be calculated to do a proper transformation to the coordinate system local to the proton orbit. Using global coordinates simplifies this to the same procedure as before, but with different offsets (the matrices themselves don't actually change).
- [ xx] Bug fix (issue #__)
- [x ] Tests for the changes have been added
See attached slides for some discussion and comparison plots.
No, it fixes the default momentum reconstruction to be correct (within the limits of how the static matrix approach works). Users will …
=> Fix RP reco bug in p_y

.github/lsan.supp
=> fix(ci): suppress memory leaks in libJANA.so and DD4hep

src/algorithms/fardetectors/MatrixTransferStatic.cc
=> [Backport v1.18] Fix RP reco bug in p_y

src/algorithms/tracking/ActsToTracks.cc
In the loop that writes the covariance matrix for the track parameters to the edm4eic output, the indices were not being incremented.
This lead to this output:
```
root [1] events->Scan("CentralCKFTrackParameters.covariance.covariance")
***********************************
*    Row   * Instance * CentralCK *
***********************************
*        0 *        0 * 0.0003341 *
*        0 *        1 *         0 *
*        0 *        2 *         0 *
*        0 *        3 *         0 *
*        0 *        4 *         0 *
*        0 *        5 *         0 *
*        0 *        6 *         0 *
*        0 *        7 *         0 *
*        0 *        8 *         0 *
*        0 *        9 *         0 *
*        0 *       10 *         0 *
*        0 *       11 *         0 *
*        0 *       12 …
```
=> Fix: Correctly fill track parameters covariance error matrix

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTracking.h, src/global/tracking/CKFTracking_factory.h
Minor code clean up.
The order of the CKF algorithm arguments has been swapped around to match the order provided to the factory generator making it slightly easier to follow the code.
No
No
=> Swap the order of the CKF algorithm arguments

src/detectors/BEMC/BEMC.cc
Sampling fraction of the BIC ScFi layer has been updated using 5 GeV photons generated at eta = 0.
=> BIC sampling fraction update

src/algorithms/calorimetry/ImagingClusterReco.h, src/detectors/BEMC/BEMC.cc, src/factories/calorimetry/ImagingClusterReco_factory.h
This PR applies the #1396 treatment to the `ImagingClusterReco` algorithm. As a reminder:
- Previously, the truth in the truth-cluster associations was defined to be the MCParticle of the 1st contribution stored in the list of contributions to the SimCalorimeterHit corresponding to the highest energy hit in the cluster.
- The logic here is
1. Multiple MC-Cluster associations are created,
2. Associations link back to primary (generator status == 1) MC particles, and
3. Each association carries a weight of E_{contributed} / E_{cluster}.
It doesn't introduce breaking changes, but it does substantially alter cluster-MC associations in such a way that users may have account for in downstream analysis code.
**Yes:** MC-Cluster associations (edm4eic::MCRecoClusterParticleAssociations) will now …
=> Create Multiple Primary MC-Cluster Associations for Topoclusters

src/algorithms/tracking/CKFTracking.cc
Starting with Acts 34.x the CKF fitting had been divorced from propagation to the target surface https://github.com/acts-project/acts/commit/d9f775f4155f1a13e316aa142e939ef7178ff665, so we now have to do it ourselves:
https://github.com/eic/EICrecon/blob/5e39885644bdf867aa2060ccc46da2500678c1da/src/algorithms/tracking/CKFTracking.cc#L278-L296
However the catch is that B0 CKF tracks may be affected by failures to extrapolate explicitly. The failure currently leads to a null pointer dereference. This PR changes that to a mere warning, the track is omitted from the output in the process. We would be able to upgrade to Acts 34 with this change.
No
No
=> CKFTracking: gracefully handle failures when extrapolating to perigee surface

src/benchmarks/reconstruction/tof_efficiency/TofEfficiency_processor.cc, src/detectors/BTOF/BTOF.cc, src/global/tracking/tracking.cc, src/services/io/podio/JEventProcessorPODIO.cc
Changes the name of the BTOF hit collections to use Hits instead of Hit. This was inconsistent between the name output from the hit reconstruction and collection collector input.
No
Hopefully adds the BTOF into the tracking
=> Fix naming of BTOF hits

src/detectors/BEMC/BEMC.cc
Sampling fractions of the BIC ScFi and imaging layers have been updated using 5 GeV electrons generated at eta = 0. Only the constant sampling fractions are provided this time. The energy- and eta-dependent ones will be provided next time referring to the comments on the last BIC sampling fraction PR.
No
No
=> Update of the BIC sampling fractions

src/services/io/podio/JEventSourcePODIO.cc, src/services/io/podio/JEventSourcePODIO.h
https://github.com/AIDASoft/podio/blob/v01-01/include/podio/ROOTFrameReader.h
Writer was addressed in 9f0412c4c8da1f1ca97ee0827d53e36a0e6adfe5
=> JEventSourcePODIO: support future ROOTFrameReader -> ROOTReader rename

src/algorithms/tracking/OrthogonalTrackSeedingConfig.h, src/algorithms/tracking/TrackSeeding.cc, src/global/tracking/TrackSeeding_factory.h
Following up on the presentation yesterday ([here](https://indico.bnl.gov/event/25559/contributions/99383/attachments/58553/100546/tracking_111424.pdf)) on seeding inefficiencies at low momentum, I found that the Acts Orthogonal seeder does a comparison between the phi values of the middle/lower and middle/upper space points. By default, this parameter is set to 0.085 Rad:
https://github.com/acts-project/acts/blob/f6ed9013e76120137ae456583a04b554d88d9452/Core/include/Acts/Seeding/SeedFinderOrthogonalConfig.hpp#L79
This is checked, for example, here:
https://github.com/acts-project/acts/blob/f6ed9013e76120137ae456583a04b554d88d9452/Core/include/Acts/Seeding/SeedFinderOrthogonal.ipp#L82-L86
And this check is done prior to other doublet or triplet checks on the potential seed triplet.
This …
=> Added deltaPhiMax parameter for Seed Finder

src/algorithms/tracking/TrackProjector.cc
This PR should fix the eicrecon build error in https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/4175065/raw (root-6.32.06 upgrade).
No.
No.
=> fix: static_cast<float>(sqrt(...)) to avoid c++-narrowing warning/error

.github/workflows/linux-eic-shell.yml, src/utilities/eicrecon/eicrecon_cli.cpp
This changes default configuration to use jana:parameter_strictness=2. Should help users agains typos in their parameters. On older versions of JANA2 this should be no-op.
Yes. Users will have to update their invocations if unused parameters are provided, or pass `-Pjana:parameter_strictness=0` argument.
Yes
=> eicrecon: fail on unrecognized parameters

cmake/jana_plugin.cmake, src/services/io/podio/JEventSourcePODIO.cc, src/services/io/podio/JEventSourcePODIO.h
Podio event source uses a new `Emit()` callback which doesn't use exceptions for control flow.
No
No
=> Podio event source: Use new, exception-free Emit() callback

CMakeLists.txt, cmake/jana_plugin.cmake
This should bring us below 50 statement limit of cmake-lint.  Also, no need to call find_package for every plugin.  External plugins already have those looked up in cmake/EICreconConfig.cmake.in.
=> cmake: move find_package from plugin_add to CMakeLists.txt

src/algorithms/tracking/CKFTracking.cc
This is re-implements #1663 in such a way that downstream algorithms, such as the AmbiguitySolver, that operate on Acts EDM do not see the failed tracks.
Resolves: #1672
No
No
=> CKFTracking: remove Acts tracks that failed to extrapolate, not just the trajectories

src/algorithms/onnx/CalorimeterParticleIDPostML.cc, src/algorithms/onnx/CalorimeterParticleIDPostML.h, src/algorithms/onnx/CalorimeterParticleIDPreML.cc, src/algorithms/onnx/CalorimeterParticleIDPreML.h, src/algorithms/onnx/InclusiveKinematicsML.cc, src/algorithms/onnx/ONNXInference.cc, src/algorithms/onnx/ONNXInference.h, src/algorithms/onnx/ONNXInferenceConfig.h, src/detectors/EEMC/CMakeLists.txt, src/detectors/EEMC/EEMC.cc, src/factories/calorimetry/CalorimeterParticleIDPostML_factory.h, src/factories/calorimetry/CalorimeterParticleIDPreML_factory.h, src/factories/meta/ONNXInference_factory.h
This provides a calorimeter PID capability using ONNXruntime inference engine. The inference algorithm is generalized into a separate algorithm which inputs and outputs `edm4eic::Tensor` values introduced by https://github.com/eic/EDM4eic/pull/96.
A set of weights needed to run this are provided in https://github.com/eic/epic-data/pull/22, and is generated using a script from https://github.com/eic/detector_benchmarks/pull/91.
No
Yes
=> add ONNXInference algorithm, use it to provide EcalEndcapNClusterParticleIDs

src/services/io/podio/JEventSourcePODIO.cc
Currently eicrecon has two checks for files existing, neither of which allow the file to be on a remote xrootd server. This PR adapts JEventSourcePODIO.cc so that the first check allows for remote files and (currently) removes the second check.
tbd
Allows remote files to be passed directly to eicrecon
=> Allow xrootd files as inputs to eicrecon

.github/ubsan.supp
This PR fixes an UBSan error external to our code, showing up e.g. https://github.com/eic/EICrecon/actions/runs/12128923399/job/33816533286?pr=1635#step:8:880
EDM4hep defines CollectionID as signed int32_t, https://github.com/key4hep/EDM4hep/blob/v00-10-05/edm4hep.yaml#L111, but podio defines it as unsigned uint32_t, https://github.com/AIDASoft/podio/blob/v01-01/include/podio/ObjectID.h#L25. This is an issue as of podio-0.17.1, https://github.com/AIDASoft/podio/commit/ac086e004bdb6f7d8972a1f62276504bb21370e0, and disappears with EDM4hep-0.99 which removed the edm4hep::ObjectID component.
No.
No.
=> fix(ci): ubsan.supp: implicit-integer-sign-change in edm4hep::ObjectID

.github/workflows/linux-eic-shell.yml
This PR updates the target operating system for CI jobs, from ubuntu-latest to a more explicit ubuntu-24.04. This is in part to test that the automatic update of implicit ubuntu-latest will not break anything (https://github.com/actions/runner-images/issues/10636), and in part because it makes sense to be explicit about the target operating system. 
No.
Yes, for the next few days ubuntu-latest will still be ubuntu-22.04, and this will mean an upgrade to ubuntu-24.04.
=> feat(ci): runs-on: ubuntu-22.04 -> ubuntu-24.04

src/benchmarks/reconstruction/TRACKINGcheck/CMakeLists.txt, src/benchmarks/reconstruction/femc_studies/CMakeLists.txt, src/benchmarks/reconstruction/lfhcal_studies/CMakeLists.txt, src/benchmarks/reconstruction/tof_efficiency/CMakeLists.txt, src/benchmarks/reconstruction/tracking_efficiency/CMakeLists.txt, src/benchmarks/reconstruction/tracking_occupancy/CMakeLists.txt
This PR removes the find_package use in benchmarks, outside of jana_plugin.cmake. Finding packages is better done centralized, to reduce duplication, to ensure the same components are found, and to ensure we keep track of minimum version requirements.
No.
No.
=> fix: rm find_package outside jana_plugin.cmake

src/services/io/podio/JEventProcessorPODIO.cc
We had a soft deprecation before, now it's a hard failure. A message is provided to direct users to the new facility.
Follow up on https://github.com/eic/EICrecon/pull/1466 and https://github.com/eic/EICrecon/pull/1323
Yes
No
=> JEventProcessorPODIO: final deprecation of `-Ppodio:output_include_collections`

src/algorithms/tracking/TrackProjector.cc, src/algorithms/tracking/TrackProjector.h, src/global/tracking/TrackProjector_factory.h, src/global/tracking/tracking.cc
The `TrackProjector` records Acts TrackStates as `edm4eic::TrackSegment`s to be saved as "CentralTrackSegments" collection. The current implementation is lacking associations from those segments to the full tracks. This PR implements the same logic as in https://github.com/eic/EICrecon/blob/d072a3ea944b7e4f171b03237de95ba5176c24c5/src/algorithms/tracking/TrackPropagation.cc#L143 to provide this information.
Fixes: #1730
No
Yes
=> TrackProjector: fill relation from segment to track

src/algorithms/fardetectors/MatrixTransferStatic.cc
This PR introduces two things:
1) early-science 130 GeV RP and OMD matrices, although the OMD one is only for testing right now (won't be used for tracks in March campaign).
2) Very mediocre protection against tracks which are truly unphysical.
These tracks come from events where the number of RP hits > 4, and one (or more) of the hits is in one detector layer. The algorithm is not yet able to properly sort hits to pick the "best" one. 
This protection works well for events where you have a truly insane number of hits from spallation on metal components in the RP layers, but it also kills some "good" events with, say, 5 or 6 hits where some simple sorting could easily through away an essentially duplicate hit in the same layer. 
The old approach did this by default for the 5-6 hit cases …
=> Add early science rp omd matrices

src/algorithms/fardetectors/MatrixTransferStatic.cc
Fixes bug where you have conflicting matrices for 130 GeV. The problem would only have shown up if you ran deuterons. The solution will be to ultimately have a separate algorithm for the OMD. For now, the OMD matrices are removed entirely.
The reason for the full removal is the addition of the 130 GeV proton matrix. the default deuteron matrices are 130 and 135 GeV, which would both create a conflict for using the correct matrix.
This is because the MC level information doesn't contain any indication of a deuteron beam, so it's impossible to know at runtime which matrix to use with a single algorithm.
Ultimately, we will need to use a separate algorithm for the OMD which only uses the OMD hit collection, rather than sending the RP and OMD hit collections to the same algorithm.
Closes: …
=> remove OMD related matrices - will be put into a separate algorithm

src/algorithms/fardetectors/MatrixTransferStatic.cc
Updates the 10x130 RP matrix to match the new beamline settings: https://github.com/eic/epic/pull/839
- [ x] Other: updated to match magnet settings
- [x ] Tests for the changes have been added
- [x ] Documentation has been added / updated
- [x ] Changes have been communicated to collaborators
Yes, it will make the 10x130 RP reco correct for this energy setting with above magnet setting change.
Yes, see above.
[RP_and_B0_pt_resolution_comparison_10_100_and_interpol_10_130_3_7_2025.pdf](https://github.com/user-attachments/files/19130938/RP_and_B0_pt_resolution_comparison_10_100_and_interpol_10_130_3_7_2025.pdf)
[pt_squared_and_RP_hit_plot_comparison_10_100_and_interpol_10_130_3_7_2025.pdf](https://github.com/user-attachments/files/19130939/pt_squared_and_RP_hit_plot_comparison_10_100_and_in …
=> updated RP 10x130 matrix to use with new beamline settings

src/algorithms/fardetectors/FarDetectorMLReconstruction.cc
Highlighted in https://github.com/eic/EICrecon/pull/1756, sometimes the value of time isn't properly set to 0. This should assure it it properly set.
No
No
=> Properly initialize time in FarDetectorMLReconstruction

src/algorithms/fardetectors/MatrixTransferStatic.cc
=> [Backport v1.23] updated RP 10x130 matrix to use with new beamline settings

cmake/jana_plugin.cmake, src/services/CMakeLists.txt, src/services/io/podio/CMakeLists.txt
https://github.com/eic/EICrecon/pull/1704 broke multiprocess builds (e.g. `make -j10`). The issue is that cmake header scanner ignores rule that generates datamodel_glue.h, which leads to race conditions:
```
src/services/io/podio/JEventSourcePODIO.cc:30:10: fatal error: services/io/podio/datamodel_glue.h: No such file or directory
30 | #include "services/io/podio/datamodel_glue.h"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This PR introduces a target-level dependency. The case of external plugin is handled by the fact that the headers are installed along with EICrecon.
No
No
=> jana_plugin.cmake: explicitly depend plugins on podio_datamodel_glue

src/algorithms/fardetectors/FarDetectorLinearTracking.cc, src/algorithms/fardetectors/FarDetectorLinearTracking.h, src/algorithms/fardetectors/FarDetectorTrackerCluster.cc, src/algorithms/fardetectors/FarDetectorTrackerCluster.h, src/detectors/LOWQ2/LOWQ2.cc, src/factories/fardetectors/FarDetectorLinearTracking_factory.h, src/factories/fardetectors/FarDetectorTrackerCluster_factory.h, src/tests/algorithms_test/tracking_SiliconSimpleCluster.cc
Meant as a porential alternative to https://github.com/eic/EICrecon/pull/1765 and https://github.com/eic/EICrecon/pull/1676 and a step towards https://github.com/eic/EICrecon/issues/1657 without the need to change the data model.
This allows the edm4eic::TrackerHit to remain purely a calibrated sensor output defined by a single CellID and edm4eic::Measurement2D to be a clustered position on a surface.
The type of TaggerTrackerM{}L{}ClusterPositions is changed to a Measurement2D so will not directly contain any 3D position information. Any downstream analysis using the collections will need to be changed.
=> Use Measurement2D for far detector clustering

src/algorithms/tracking/CKFTracking.cc
Since #1677 we remove tracks that failed extrapolation. We don't do that with tracks that failed smoothing. This PR also applies the same treatment to tracks that failed smoothing.
No.
No.
=> fix: also add tracks that failed smoothing to failed_tracks

src/algorithms/tracking/ActsGeometryProvider.h, src/algorithms/tracking/AmbiguitySolver.cc, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTracking.h, src/algorithms/tracking/CKFTrackingFunction.cc, src/algorithms/tracking/DD4hepBField.cc, src/algorithms/tracking/DD4hepBField.h, src/algorithms/tracking/SpacePoint.h, src/algorithms/tracking/TrackPropagation.cc, src/algorithms/tracking/TrackSeeding.cc, src/algorithms/tracking/TrackSeeding.h, src/services/geometry/acts/ACTSGeo_service.cc, src/services/geometry/acts/ACTSGeo_service.h
This adapts our tracking algorithms to any Acts version between v36 and v38.
The commits in this branch are topologically ordered with reference to the commit message title, Acts PR number, and version validity. All commits compile individually, but no event-for-event validation has been performed. See also https://github.com/eic/EICrecon/pull/1525.
The support for mulitple versions is done by somewhat extensive use of preprocessor directives based on `Acts_VERSION_MAJOR` and `Acts_VERSION_MINOR`.
Builds with: 35.2.0 36.0.0 36.1.0 36.2.0 36.3.2 37.4.0 38.2.0 39.1.0
Needs:
No.
No.
=> feat: fix compilation for Acts versions from v36 up to v39

.github/workflows/linux-eic-shell.yml
This PR removes a now-unnecessary CI step that was introduced as a workaround suggested in https://github.com/actions/runner/issues/3207#issuecomment-2000066889.
No.
No.
=> chore(ci): remove mmap rnd_bits workaround

src/detectors/BHCAL/BHCAL.cc, src/detectors/EEMC/EEMC.cc, src/detectors/EHCAL/EHCAL.cc, src/detectors/FEMC/FEMC.cc, src/detectors/FHCAL/FHCAL.cc
This PR fixes the inputs used for various CalorimeterClusterRecoCoG factories. Depending on the EDM4eic version, the CalorimeterClusterRecoCoG factory uses different inputs, so we need to respect that.
- @veprbl please evaluate for need for backporting into 1.24.1 and 25.04.1
No.
Yes, will again produce outputs that are currently missing.
=> fix: correct CalorimeterClusterRecoCoG inputs by EDM4eic version

src/detectors/BHCAL/BHCAL.cc, src/detectors/EEMC/EEMC.cc, src/detectors/EHCAL/EHCAL.cc, src/detectors/FEMC/FEMC.cc, src/detectors/FHCAL/FHCAL.cc
=> [Backport v1.24] fix: correct CalorimeterClusterRecoCoG inputs by EDM4eic version

CMakeLists.txt, src/extensions/jana/JOmniFactory.h, src/services/log/Log_service.cc, src/services/log/Log_service.h
This PR adds spdlog Mapped Diagnostic Context (MDC, https://github.com/gabime/spdlog/pull/2907) to store the run and event number in JOmniFactory, and print it on the logged line.
Needs:
No.
No.
=> feat: use spdlog mapped diagnostic context to store event number

src/algorithms/tracking/CKFTracking.cc
This PR applies the pre-36 workaround also for 36.0.0, since the issue was only fixed in 36.1.0.
No.
No.
=> fix: workaround m_particleHypothesis in CKFTracking for acts-36.0.0 too

src/algorithms/tracking/CKFTracking.cc
=> [Backport v1.24] fix: workaround m_particleHypothesis in CKFTracking for acts-36.0.0 too

.git-blame-ignore-revs, src/algorithms/digi/EICROCDigitizationConfig.h, src/algorithms/digi/SiliconPulseDiscretization.cc, src/detectors/BTOF/BTOF.cc
…scretization, and error is thrown if pulse heights are repeating at the any given time.
- [ x] Bug fix (issue #1802 )
Nothing.
PulseCombiner is enabled before SiliconPulseDiscretization to prevent overlapping pulses from causing errors when the class interpolate the time bins. If there are multiple pulse heights at the same time, this class still won't work, but it will throw an error instead of keep silence.
=> Bug fix on SiliconPulseDiscretization giving nan values sometimes.

src/algorithms/digi/PulseCombiner.cc, src/algorithms/digi/PulseCombiner.h, src/algorithms/digi/PulseNoise.cc, src/algorithms/digi/PulseNoise.h, src/algorithms/digi/SiliconPulseDiscretization.cc, src/algorithms/digi/SiliconPulseDiscretization.h, src/algorithms/digi/SiliconPulseGeneration.cc, src/algorithms/digi/SiliconPulseGeneration.h, src/factories/digi/PulseCombiner_factory.h, src/factories/digi/PulseNoise_factory.h, src/factories/digi/SiliconPulseDiscretization_factory.h, src/factories/digi/SiliconPulseGeneration_factory.h, src/tests/algorithms_test/digi_SiliconPulseGeneration.cc
Allows the new SimPulse to be used by the current developing pulse algorithms
No
Outputs edm4eic::SimPulse rather than edm4hep::TimeSeries when the edm4eic version is >=8.1
=> Adopt edm4eic::SimPulse in for current pulse algorithms

src/detectors/MPGD/MPGD.cc
As presented in the tracking WG meeting ([https://indico.bnl.gov/event/27589/contributions/105659/attachments/60986/104773/tracking1_040325.pdf](https://indico.bnl.gov/event/27589/contributions/105659/attachments/60986/104773/tracking1_040325.pdf)), the updated 2D MPGD digitization leads to inefficiencies for the Barrel MPGD.
This PR restores the previous digitization scheme as the default, where the hits are used in the track reconstruction with high efficiency. Once the 2D readout can demonstrate comparable results, we will switch over.
Results with 2D digitization:
Results with pixel-style (SVT-like) digitization:
No
Yes, it restores previous barrel MPGD digitization scheme as default.
=> Use pixel-style MPDG readout for tracking until efficiency issues are resolved

src/detectors/MPGD/MPGD.cc
As presented in the tracking WG meeting
([https://indico.bnl.gov/event/27589/contributions/105659/attachments/60986/104773/tracking1_040325.pdf](https://indico.bnl.gov/event/27589/contributions/105659/attachments/60986/104773/tracking1_040325.pdf)), the updated 2D MPGD digitization leads to inefficiencies for the Barrel MPGD.
This PR restores the previous digitization scheme as the default, where the hits are used in the track reconstruction with high efficiency. Once the 2D readout can demonstrate comparable results, we will switch over.
Results with 2D digitization:
src="https://github.com/user-attachments/assets/5785ed7a-faa3-44d7-a8ba-b566edde82b8" />
Results with pixel-style (SVT-like) digitization:
src="https://github.com/user-attachments/assets/217d8ae4-7d7f-4a65-9b49-ce1b6a5bc4a7" …
=> [Backport v1.24] Use pixel-style MPDG readout for tracking until efficiency issues are resolved

src/algorithms/fardetectors/FarDetectorLinearTracking.cc
This PR modifies the maximum weight determination in the FarDetectorLinearTracking algorithm to allow the use of unsigned indices and avoid compiler warnings. This has (had) a possible corner case when all weights are zero or the number of entries is zero, when previous a negative index would be used. These are now skipped.
No.
No.
=> fix: slight modification of maximum weight with unsigned indices

src/algorithms/tracking/ActsGeometryProvider.h
This PR ensures that the ActsGeometryProvider gets a proper vtable by defining a virtual destructor.
No.
No.
=> fix: virtual destructor for ActsGeometryProvider to avoid warning

src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/SpacePoint.h, src/benchmarks/reconstruction/femc_studies/femc_studiesProcessor.cc, src/benchmarks/reconstruction/lfhcal_studies/clusterizer_MA.h, src/benchmarks/reconstruction/lfhcal_studies/lfhcal_studiesProcessor.cc
This PR fixes some remaining loose ends: unused variables with ifdefs, unused functions, unused arguments, casting to decltypes.
No.
No.
=> fix: a few loose ends to avoid compiler warnings

src/algorithms/calorimetry/TrackClusterMergeSplitter.cc, src/algorithms/calorimetry/TrackClusterMergeSplitter.h, src/factories/calorimetry/TrackClusterMergeSplitter_factory.h
This PR modifies the TrackClusterMerger to use the algorithms GeoSvc instead of getting the detector geometry by pointer through the init function.
No.
No.
=> fix: use GeoSvc in TrackClusterMerger instead of init(ptr)

cmake/jana_plugin.cmake, src/algorithms/pid/IrtCherenkovParticleID.cc, src/algorithms/pid/IrtCherenkovParticleID.h, src/algorithms/pid/IrtCherenkovParticleIDConfig.h, src/algorithms/pid/MergeParticleID.cc, src/algorithms/pid/MergeParticleID.h, src/algorithms/pid/MergeParticleIDConfig.h, src/algorithms/pid/Tools.h, src/global/pid/IrtCherenkovParticleID_factory.h, src/global/pid/MergeCherenkovParticleID_factory.h, src/tests/algorithms_test/pid_MergeParticleID.cc
This PR ensures that IrtCherenkovParticleID uses the algorithms logger, so it does not have to be passed by the factory.
No.
No.
=> feat: use algorithms logger service in IrtCherenkovParticleID

src/algorithms/digi/LGADChargeSharing.cc, src/algorithms/digi/LGADChargeSharing.h
This PR avoids a thread-unsafe geoManager->GetCurrentMatrix() call which relies on cached state in the geoManager object.
No.
No.
=> fix: avoid geoManager->GetCurrentMatrix in LGADChargeSharing::_global2Local

.github/workflows/linux-eic-shell.yml
This PR fixes a minor bug that causes the incorrect libraries to be picked up in the dynamic loader unresolved functions check for plugins. Now the libraries are resolved and only few undefined functions returned, e.g. https://github.com/eic/EICrecon/actions/runs/14891841097/job/41825513765?pr=1857#step:8:203.
No.
No.
=> fix(ci): LD_LIBRARY_PATH should be $PWD/install/lib

.github/workflows/linux-eic-shell.yml
This PR removes the g++ debug build which is unused by any subsequent jobs, and which consumes the [largest ccache chunks](https://github.com/eic/EICrecon/actions/caches?query=sort%3Asize-desc).
No.
No.
=> fix(ci): rm unused g++ Debug build

src/algorithms/tracking/TrackPropagation.cc
This updates the track propagation (projection) to use the track parameters determined on the outermost tracking layer.
No.
Yes, it will change the track propagation results.
=> fix: Propagate tracks from outermost surface

src/algorithms/tracking/TrackParamTruthInit.cc
This PR fixes an issue ([pointed out](https://github.com/eic/EICrecon/pull/1876#discussion_r2102977558) by @simonge) where neutrals are not skipped as intended in TrackParamTruthInit
No.
No.
=> fix: properly ignore neutrals in TrackParamTruthInit.cc

src/algorithms/pid_lut/PIDLookup.cc, src/algorithms/pid_lut/PIDLookup.h, src/algorithms/pid_lut/PIDLookupConfig.h, src/factories/pid_lut/PIDLookup_factory.h, src/global/pid_lut/pid_lut.cc, src/tests/algorithms_test/algorithmsInit.cc, src/tests/algorithms_test/pid_lut_PIDLookup.cc
Part of #1887. Moves the geometry plugin requirements out of the pid_lut plugin and into the algorithm.
No
No
=> Move pid_lut plugin detector constants into algorithm

src/algorithms/reco/MatchClusters.cc, src/algorithms/reco/MatchClusters.h
There were reports of ReconstructedParticle containing PDG=130 (K0L), which we don't identify. Convention is that we use PID information in Reconstructed* branches. That is already the case for tracks (ChargedParticles), but was never addressed for when we add in clusters in `MatchClusters`. For now the only clusters with PID are from EEEMCal, and only electron/pion separation is implemented which requires a track and does not belong in this branch, so we can't take that. So solution, for now, is to keep zero values.
Yes, users may observe missing PDG for neutral particles reconstructed.
Yes
=> MatchClusters: do not assign PDG code to trackless EM clusters

src/algorithms/tracking/ActsGeometryProvider.h
This PR fixes an RGB component from 280 to 180 (what was likely intended).
No.
No.
=> fix: don't use RGB component 280 > 255

src/algorithms/tracking/ActsToTracks.cc
=> [Backport v1.26] ActsToTracks: don't treat outliers as measurements

.github/tsan.supp
This PR suppresses a spurious data race warning in TSAN for `std::lgamma` which is technically not thread-safe (see note at https://en.cppreference.com/w/cpp/numeric/math/lgamma). Since `std::binomial_distribution` only uses the return value of `std::lgamma` without subsequent calls for the `signgam` value (https://github.com/gcc-mirror/gcc/blob/releases/gcc-12.2.0/libstdc%2B%2B-v3/include/bits/random.tcc#L1475), we can safely suppress the warning inside the two functions that call `std::lgamma`.
No.
No.
=> fix: suppress spurious `lgamma` data race warning

src/global/tracking/tracking.cc, src/services/io/podio/JEventProcessorPODIO.cc
This PR fixes an issue that snuck in with #1744, namely a duplicate factory name `CentralTrackVertices` which results in the warning:
```
14:47:13.866  [warn] Parameter 'tracking:CentralTrackVertices:InputTags' has conflicting defaults: 'CentralAndB0TrackerCKFActsTrajectories,ReconstructedChargedParticles' vs 'CentralCKFActsTrajectories,ReconstructedChargedParticles'
14:47:13.866  [warn] Parameter 'tracking:CentralTrackVertices:OutputTags' has conflicting defaults: 'CentralAndB0TrackerVertices' vs 'CentralTrackVertices'
```
We'll have to see how this affects the comment at https://github.com/eic/EICrecon/pull/1744#discussion_r2159507602 ...
No.
No.
=> fix: avoid duplicate factory name (CentralTrackVertices)

src/algorithms/reco/TrackClusterMatch.cc, src/algorithms/reco/TrackClusterMatchConfig.h, src/global/reco/reco.cc, src/services/io/podio/JEventProcessorPODIO.cc
A suggested in #1885, the track-cluster matching should be done separately for each calorimeter.  Later algorithms can then manage the merging and splitting of clusters and integration across calorimeters.  This also makes it simpler to tune the matching criteria separately for each subsystem. 
There is no longer a single TrackClusterMatches collection output, instead is is broken into separate collections for each calorimeter
```
EcalEndcapPTrackClusterMatches
EcalEndcapPInsertTrackClusterMatches
LFHCALTrackClusterMatches
HcalEndcapPInsertClusterMatches
EcalBarrelTrackClusterMatches
HcalBarrelTrackClusterMatches
EcalEndcapNTrackClusterMatches
HcalEndcapNTrackClusterMatches
```
See above
=> Run track-cluster matching separately for each calorimeter

src/services/io/podio/JEventProcessorPODIO.cc
This PR adds the functionality that allows for specifying regex patterns as `podio:output_collections`, e.g. `eicrecon -Ppodio:output_collections='EcalBarrel.*'` to select all `EcalBarrel` outputs. Note, it's a regex, not a glob.
No.
No.
=> feat: allow specifying regex for `podio:output_collections`

src/detectors/FOFFMTRK/FOFFMTRK.cc
This PR introduces the update OMD matrices to account for changes in the cryostat (PR: https://github.com/eic/epic/pull/893) that forced the OMD to move further from the IP.
No, this will allow PR https://github.com/eic/epic/pull/893 to be merged (at the same time as this one) without breaking the reconstruction.
When both PRs are merged, no, it returns things to default behavior.
=> updated the matrices for the OMD 130 GeV/n deuteron beams

src/detectors/FOFFMTRK/FOFFMTRK.cc
=> [Backport v1.27] updated the matrices for the OMD 130 GeV/n deuteron beams

src/algorithms/reco/ChargedMCParticleSelector.h, src/algorithms/reco/ChargedReconstructedParticleSelector.h, src/algorithms/reco/ElectronReconstruction.cc, src/algorithms/reco/ElectronReconstruction.h, src/factories/reco/ChargedMCParticleSelector_factory.h, src/factories/reco/ChargedReconstructedParticleSelector_factory.h, src/factories/reco/ReconstructedElectrons_factory.h
This PR switches the reco algorithms for charged MCParticle and ReconstructedParticle selection (could be a meta balgorithm) and for DIS electron selection over to the algorithms interface.
No.
No.
=> feat: switch remaining reco algorithms/factories to algorithms interface

.github/iwyu.imp, src/algorithms/tracking/CKFTracking.cc, src/algorithms/tracking/CKFTracking.h
This PR ensures that CI can run successfully with `-Wall`.
No.
No.
=> fix: avoid unused variable warnings with Acts 39

.github/workflows/linux-eic-shell.yml
eic-shell now ships with llvm/clang 18, so we started running into:
```
warning: src/tests/algorithms_test/algorithms_test.profraw: unsupported instrumentation profile format version
error: no profile can be merged
```
=> linux-eic-shell: update llvm-cov from 15 to 18

src/algorithms/digi/SiliconChargeSharing.cc, src/algorithms/digi/SiliconChargeSharingConfig.h, src/detectors/BTOF/BTOF.cc, src/factories/digi/SiliconChargeSharing_factory.h
I added an option in `SiliconChargeSharing `such that `sharing_sigma `can be defined relative to the cell size in the latest update, as per our agreement in the reconstruction meeting. BTOF now defaults to using this relative definition of charge sharing magnitude.
No
No
=> Added new mode to support charge sharing sigma in the units of cell dimension

src/algorithms/tracking/TrackPropagation.cc, src/algorithms/tracking/TrackPropagation.h
This PR adds an explicit Navigator with MaterialInteractor action for track propagation. This may impact how the material map is taken into account during propagation.
No.
No.
=> fix: use Navigator with MaterialInteractor action for track propagation

CMakeLists.txt, src/algorithms/CMakeLists.txt, src/detectors/LOWQ2/CMakeLists.txt, src/global/reco/CMakeLists.txt, src/global/reco/reco.cc
Since the EEMC doesn't use the option to turn off ONNX Runtime, we might as well not give the impression that it's supported.
No.
ONNX Runtime required now.
=> fix: just require ONNX Runtime everywhere

src/global/pid_lut/pid_lut.cc
Stops clang tidy suggesting replacing the value `2.7175` with `e` in the `pid_lut` plugin
No
No
=> Add NOLINT block to pid_lut

.github/workflows/linux-eic-shell.yml
This PR ensures that dependabot PRs don't fail due to insufficient permissions in the IWYU step. See https://github.com/eic/EICrecon/actions/runs/17245815142/job/48935888308?pr=2050.
No.
No.
=> fix: don't create IWYU PRs for dependabot (no permissions)

.github/lsan.supp
This PR fixes a rename of the leaking object from createBuffers to create{name}Buffers, see https://github.com/AIDASoft/podio/pull/746. This applies for podio-1.3. The pattern should still match the previous name too, used in podio-1.2.
No.
No.
=> fix: rename known-leaking suppressed object `edm4hep::create*Buffers`

src/algorithms/digi/SiliconChargeSharingConfig.h
This PR modifies the unscoped enum `ESigmaMode` to a scoped enum, and avoids the implicit integer conversion by correcting the `operator<<` signature. Before this fix, the output was `0` or `1` (since the incorrectly-signatured `operator<<` is not used); after this fix, the output is `abs` or `rel`.
The scoping of the enum adds a layer of safety since the symbol `abs` could previously shadow the standard function `std::abs`.
This aligns with the enabled clang-tidy check `cppcoreguidelines-use-enum-class`, https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/use-enum-class.html.
No.
No.
=> fix: enable strongly-typed enum SiliconChargeSharingConfig::ESigmaMode

src/algorithms/calorimetry/ImagingTopoCluster.cc, src/algorithms/calorimetry/ImagingTopoCluster.h, src/algorithms/calorimetry/ImagingTopoClusterConfig.h, src/detectors/BEMC/BEMC.cc, src/detectors/FHCAL/FHCAL.cc, src/detectors/ZDC/ZDC.cc, src/factories/calorimetry/ImagingTopoCluster_factory.h, src/tests/algorithms_test/calorimetry_ImagingTopoCluster.cc
Added Layer Modes to the helper function to group hits within the same layer for ImagingTopoCluster
=> fix: Add ImagingTopoCluster layer mode within same layers

.github/workflows/linux-eic-shell.yml
This PR fixes a failing CI check (for pragma once) when there are no header files in the modified file set.
No.
No.
=> ci: don't fail pragma once check when no headers changed

src/algorithms/calorimetry/CalorimeterHitDigi.cc
Added debug logging for hits retained despite exceeding `capTime`.
No.
Yes, multiple hits at different times inside a single calorimeter channel will be retained.
=> fix: Add debug logs for time cap exceedance in hits; don't skip them

src/algorithms/calorimetry/CalorimeterHitDigi.cc
=> [Backport v1.29] fix: Add debug logs for time cap exceedance in hits; don't skip them

src/services/pid_lut/PIDLookupTable.cc, src/services/pid_lut/PIDLookupTable.h
Removes filling of PID lookup tables outside of their theta bin range.
As noted in #2018 the `pfrich.lut` file contains entries out with the range of the binning defined for it in https://github.com/eic/EICrecon/blob/main/src/global/pid_lut/pid_lut.cc#L72. This has given access to a bin up to `theta<inf` so particles in the far-backward region are provided with a `ParticleID` from the `RichEndcapN`.
~~This PR attempts to remove this overflow bin using boost histograms own methods but if it doesn't work,~~ manual filtering is possibly simpler.
No
Stops the PID LUTs from assigning values outside of their range.
=> attempt to remove the pid_lut theta overflow bins
